// Build src/lib/venues/<slug>.ts for each reconstructed hospital sheet.
//
// For every sheet we: reconstruct the vector floor plan (scripts/maps/pdf2svg),
// pull grouped destination labels (scripts/maps/extract), and place each label
// as a waypoint at its position on the sheet. Geography is approximate by design
// — like the other sheet-derived venues, pin placement within the site is
// illustrative — but self-consistent: pins land on their labels because both
// come from the same coordinate extraction.
//
// `plan` crops waypoint extraction to the actual site-plan area so labels from a
// sheet's directory table / key / title band don't become stray waypoints; the
// floor-plan IMAGE is always the whole sheet. Bounds are anchored so the plan
// centre lands on the hospital's real coordinates.
//
// Run: node scripts/maps/build-venues.mjs
import { extractLabels } from "./extract.mjs"
import { readSheets } from "./sheets.mjs"
import { writeFileSync } from "fs"

const R = 111320 // metres per degree latitude

// The sheets to build, and how each one is anchored to the real world, now live
// in data/mapped-sites.json — see scripts/maps/sheets.mjs for the field notes.
// generate-all.mjs reads the same file, so a sheet can't be rasterised without a
// venue or vice versa.
const VENUES = readSheets()

function slugify(s) {
  return s.toLowerCase().replace(/['’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "wp"
}
const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
const r6 = (n) => Number(n.toFixed(6))

async function build(v) {
  const { labels, W, H } = await extractLabels(v.file, v.page)
  const [px0, py0, px1, py1] = v.plan
  const inPlan = labels.filter((l) => l.nx >= px0 && l.nx <= px1 && l.ny >= py0 && l.ny <= py1)

  // Bounds: full sheet spans dLng × dLat, anchored so the plan centre == center.
  const [lat0, lng0] = v.center
  const dLng = v.spanM / (R * Math.cos((lat0 * Math.PI) / 180))
  const dLat = (v.spanM * (H / W)) / R
  const pcx = (px0 + px1) / 2, pcy = (py0 + py1) / 2
  // Only the north-west corner is used — toLatLng walks south and east from it.
  // The other two edges were computed and never read.
  const lngW = lng0 - pcx * dLng
  const latN = lat0 + pcy * dLat

  const toLatLng = (nx, ny) => [r6(latN - ny * dLat), r6(lngW + nx * dLng)]

  // Waypoints, de-duplicated ids.
  const usedIds = {}
  const wps = inPlan.map((l) => {
    const base = `${slugify(l.text)}-f0`
    const n = usedIds[base] || 0
    usedIds[base] = n + 1
    const id = n === 0 ? base : `${base}-${n + 1}`
    const [lat, lng] = toLatLng(l.nx, l.ny)
    return { id, name: l.text, type: l.type, lat, lng }
  })

  const [bS, bW] = toLatLng(0, 1) // sheet bottom-left  -> [latS, lngW]
  const [bN, bE] = toLatLng(1, 0) // sheet top-right    -> [latN, lngE]

  const L = []
  L.push('import { Venue } from "../types"')
  L.push("")
  L.push(`// ${v.name} — reconstructed from the trust's own site map sheet`)
  L.push("// (${v.file}). Generated by scripts/maps/build-venues.mjs — edit that, not this.".replace("${v.file}", v.file))
  L.push("")
  L.push(`export const ${v.slug.toUpperCase().replace(/-/g, "_")}_VENUE: Venue = {`)
  L.push(`  id: "${v.id}",`)
  L.push(`  slug: "${v.slug}",`)
  L.push(`  name: "${esc(v.name)}",`)
  L.push(`  subtitle: "${esc(v.subtitle)}",`)
  L.push('  category: "hospital",')
  L.push(`  center: { lat: ${r6(lat0)}, lng: ${r6(lng0)} },`)
  L.push("  defaultZoom: 17,")
  L.push('  visibility: "public",')
  L.push("  verified: false,")
  L.push(`  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "${esc(v.notes)}" },`)
  L.push(`  quickAccess: [${v.quick.map((q) => `"${esc(q)}"`).join(", ")}],`)
  L.push("  floorPlans: [")
  L.push(`    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/${v.slug}/sitemap.svg", bounds: [[${r6(bS)}, ${r6(bW)}], [${r6(bN)}, ${r6(bE)}]] },`)
  L.push("  ],")
  L.push("  waypoints: [")
  for (const w of wps) {
    L.push(`    { id: "${w.id}", name: "${esc(w.name)}", type: "${w.type}", coordinates: { lat: ${w.lat}, lng: ${w.lng} }, floor: 0 },`)
  }
  L.push("  ],")
  L.push("}")
  L.push("")
  writeFileSync(`src/lib/venues/${v.slug}.ts`, L.join("\n"))
  return { slug: v.slug, count: wps.length }
}

for (const v of VENUES) {
  const r = await build(v)
  console.log(`${r.slug}: ${r.count} waypoints`)
}
