// Build src/lib/venues/<slug>.ts for each reconstructed hospital sheet.
//
// For every sheet we: reconstruct the vector floor plan (scripts/maps/pdf2svg),
// pull grouped destination labels (scripts/maps/extract), and place each label
// as a waypoint at its position on the sheet. Geography is approximate by design
// — like the other sheet-derived venues, pin placement within the site is
// illustrative — but self-consistent: pins land on their labels because both
// come from the same coordinate extraction.
//
// `plan` crops waypoint extraction to the actual site-plan area so labels from a
// sheet's directory table / key / title band don't become stray waypoints; the
// floor-plan IMAGE is always the whole sheet. Bounds are anchored so the plan
// centre lands on the hospital's real coordinates.
//
// Run: node scripts/maps/build-venues.mjs
import { extractLabels } from "./extract.mjs"
import { readSheets } from "./sheets.mjs"
import { writeFileSync } from "fs"

const R = 111320 // metres per degree latitude

// The sheets to build, and how each one is anchored to the real world, now live
// in data/mapped-sites.json — see scripts/maps/sheets.mjs for the field notes.
// generate-all.mjs reads the same file, so a sheet can't be rasterised without a
// venue or vice versa.
const VENUES = readSheets()

function slugify(s) {
  return s.toLowerCase().replace(/['’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "wp"
}
const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
const r6 = (n) => Number(n.toFixed(6))

// Place one floor: its bounds, and its labels as waypoints on that storey.
//
// Every floor of a building is anchored on the same centre, but each gets its
// own bounds from its OWN page dimensions. Sharing one aspect ratio across
// floors would stretch any sheet drawn at a different size — and trusts publish
// levels of one hospital at whatever size each drawing happened to be.
async function placeFloor(v, floor, usedIds) {
  const { labels, W, H } = await extractLabels(floor.file, floor.page)
  const [px0, py0, px1, py1] = floor.plan
  const inPlan = labels.filter((l) => l.nx >= px0 && l.nx <= px1 && l.ny >= py0 && l.ny <= py1)

  // Bounds: full sheet spans dLng × dLat, anchored so the plan centre == center.
  const [lat0, lng0] = v.center
  const dLng = v.spanM / (R * Math.cos((lat0 * Math.PI) / 180))
  const dLat = (v.spanM * (H / W)) / R
  const pcx = (px0 + px1) / 2, pcy = (py0 + py1) / 2
  // Only the north-west corner is used — toLatLng walks south and east from it.
  // The other two edges were computed and never read.
  const lngW = lng0 - pcx * dLng
  const latN = lat0 + pcy * dLat

  const toLatLng = (nx, ny) => [r6(latN - ny * dLat), r6(lngW + nx * dLng)]

  // Waypoint ids are de-duplicated across the WHOLE venue, not per floor: a
  // hospital has a "Reception" on several levels, and two waypoints sharing an
  // id would collide in routing.
  const wps = inPlan.map((l) => {
    const base = `${slugify(l.text)}-f${floor.floor}`
    const n = usedIds[base] || 0
    usedIds[base] = n + 1
    const id = n === 0 ? base : `${base}-${n + 1}`
    const [lat, lng] = toLatLng(l.nx, l.ny)
    // A storey read out of the label goes in the description, not the floor.
    // The pin has to stay on the sheet it was extracted from: a hospital that
    // publishes one site map listing "Allebone (Second Floor)" has no floor-2
    // plan to draw, so moving the waypoint there would hide it behind a floor
    // selector with nothing under it. In the description it still reaches the
    // destination card and search, and it is the record a later per-floor
    // ingest needs. Waypoints whose floor comes from the FILENAME are a
    // different case and are placed on their real storey, above.
    return {
      id, name: l.text, type: l.type, lat, lng, floor: floor.floor,
      description: l.storeyLabel ?? undefined,
    }
  })

  const [bS, bW] = toLatLng(0, 1) // sheet bottom-left  -> [latS, lngW]
  const [bN, bE] = toLatLng(1, 0) // sheet top-right    -> [latN, lngE]
  return { wps, bounds: [bS, bW, bN, bE] }
}

async function build(v) {
  const [lat0, lng0] = v.center
  const usedIds = {}
  const placed = []
  for (const floor of v.floors) placed.push({ floor, ...(await placeFloor(v, floor, usedIds)) })
  const wps = placed.flatMap((p) => p.wps)

  const L = []
  L.push('import { Venue } from "../types"')
  L.push("")
  L.push(`// ${v.name} — reconstructed from the trust's own map sheet${v.floors.length > 1 ? "s" : ""}`)
  L.push(`// (${v.floors.map((f) => f.file).join(", ")}).`)
  L.push("// Generated by scripts/maps/build-venues.mjs — edit that, not this.")
  L.push("")
  L.push(`export const ${v.slug.toUpperCase().replace(/-/g, "_")}_VENUE: Venue = {`)
  L.push(`  id: "${v.id}",`)
  L.push(`  slug: "${v.slug}",`)
  L.push(`  name: "${esc(v.name)}",`)
  L.push(`  subtitle: "${esc(v.subtitle)}",`)
  L.push('  category: "hospital",')
  L.push(`  center: { lat: ${r6(lat0)}, lng: ${r6(lng0)} },`)
  L.push("  defaultZoom: 17,")
  L.push('  visibility: "public",')
  L.push("  verified: false,")
  L.push(`  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "${esc(v.notes)}" },`)
  L.push(`  quickAccess: [${v.quick.map((q) => `"${esc(q)}"`).join(", ")}],`)
  L.push("  floorPlans: [")
  for (const { floor, bounds: [bS, bW, bN, bE] } of placed) {
    L.push(
      `    { id: "${floor.id}", floor: ${floor.floor}, label: "${esc(floor.label)}", ` +
        `imageUrl: "/floorplans/${v.slug}/${floor.image}.svg", bounds: [[${r6(bS)}, ${r6(bW)}], [${r6(bN)}, ${r6(bE)}]] },`
    )
  }
  L.push("  ],")
  L.push("  waypoints: [")
  for (const w of wps) {
    const desc = w.description ? `, description: "${esc(w.description)}"` : ""
    L.push(`    { id: "${w.id}", name: "${esc(w.name)}", type: "${w.type}", coordinates: { lat: ${w.lat}, lng: ${w.lng} }, floor: ${w.floor}${desc} },`)
  }
  L.push("  ],")
  L.push("}")
  L.push("")
  writeFileSync(`src/lib/venues/${v.slug}.ts`, L.join("\n"))
  return { slug: v.slug, count: wps.length }
}

for (const v of VENUES) {
  const r = await build(v)
  console.log(`${r.slug}: ${r.count} waypoints`)
}
