#!/usr/bin/env node
// One-off migration: apply the current label rules to venue modules that were
// generated under the old ones.
//
// The sheet-derived venue modules say "edit that, not this", and normally the
// fix for a bad waypoint name is to fix the extractor and re-run
// `npm run nhs:ingest`. That needs the source PDFs, which are not in the repo
// (`/map/` is gitignored). So the same rules that now run in
// scripts/maps/lib/labels.mjs are applied here directly to the committed
// output, and the two must agree: re-running the ingest after this must be a
// no-op on names and types. When the sheets have been re-ingested, delete this.
//
// What it does, per generated venue:
//   - drops waypoints the label rules now reject (sheet furniture, transport
//     interchanges, staff-only parking, undecodable text)
//   - title-cases labels the sheet set in capitals
//   - retypes labels the old rules mistyped (every STAIRWELL was "other")
//   - lifts a storey out of the name into the description
//   - repairs quickAccess entries so the shortcut chips resolve again
//
// Waypoint ids are deliberately left alone. They are slug-derived from the old
// name, so renaming would change them — and ids are what a shared link and a
// saved destination resolve against. A stale-looking id is worth an unbroken
// link.
//
// Run: node scripts/maps/normalise-venues.mjs [--dry-run]

import { readFileSync, writeFileSync, readdirSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { cleanLabel } from "./lib/labels.mjs"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..")
const VENUE_DIR = join(ROOT, "src", "lib", "venues")
const DRY = process.argv.includes("--dry-run")

const GENERATED = /Generated by scripts\/maps\/build-venues\.mjs/
const WAYPOINT =
  /^(\s*)\{ id: "([^"]+)", name: "((?:[^"\\]|\\.)*)", type: "([a-z]+)", coordinates: \{ lat: ([-\d.]+), lng: ([-\d.]+) \}, floor: (-?\d+)(, description: "(?:[^"\\]|\\.)*")? \},$/

const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
const unesc = (s) => s.replace(/\\"/g, '"').replace(/\\\\/g, "\\")

// Same measure search.ts uses for "did you mean", so a quickAccess entry is
// repaired the way the app would have judged it.
function similarity(a, b) {
  const norm = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "")
  const x = norm(a)
  const y = norm(b)
  if (x.length < 2 || y.length < 2) return x === y ? 1 : 0
  const counts = new Map()
  for (let i = 0; i < y.length - 1; i++) {
    const g = y.slice(i, i + 2)
    counts.set(g, (counts.get(g) ?? 0) + 1)
  }
  let common = 0
  for (let i = 0; i < x.length - 1; i++) {
    const g = x.slice(i, i + 2)
    const c = counts.get(g) ?? 0
    if (c > 0) {
      common++
      counts.set(g, c - 1)
    }
  }
  return (2 * common) / (x.length - 1 + (y.length - 1))
}

const totals = { files: 0, dropped: 0, renamed: 0, retyped: 0, described: 0, quickFixed: 0, quickDropped: 0 }
const detail = []

for (const file of readdirSync(VENUE_DIR).filter((f) => f.endsWith(".ts"))) {
  const path = join(VENUE_DIR, file)
  const src = readFileSync(path, "utf8")
  if (!GENERATED.test(src)) continue

  const out = []
  const names = []
  let dropped = 0
  let renamed = 0
  let retyped = 0
  let described = 0

  for (const line of src.split("\n")) {
    const m = line.match(WAYPOINT)
    if (!m) {
      out.push(line)
      continue
    }
    const [, indent, id, rawName, type, lat, lng, floor, existingDesc] = m
    const oldName = unesc(rawName)
    const clean = cleanLabel(oldName)

    if (!clean) {
      dropped++
      detail.push(`  ${file}: dropped "${oldName}"`)
      continue
    }
    if (clean.text !== oldName) {
      renamed++
      detail.push(`  ${file}: "${oldName}" -> "${clean.text}"`)
    }
    if (clean.type !== type) {
      retyped++
      detail.push(`  ${file}: "${clean.text}" ${type} -> ${clean.type}`)
    }

    // An existing description is venue-authored context and is never replaced;
    // the storey is only added where there was nothing.
    let desc = existingDesc ?? ""
    if (!desc && clean.storeyLabel) {
      desc = `, description: "${esc(clean.storeyLabel)}"`
      described++
    }

    names.push(clean.text)
    out.push(
      `${indent}{ id: "${id}", name: "${esc(clean.text)}", type: "${clean.type}", ` +
        `coordinates: { lat: ${lat}, lng: ${lng} }, floor: ${floor}${desc} },`
    )
  }

  // Repair quickAccess. SearchModal matches these against waypoint names
  // exactly (SearchModal.tsx:88), so an entry that is close but not equal
  // renders no chip at all and looks like the venue simply has no shortcuts.
  let quickFixed = 0
  let quickDropped = 0
  let text = out.join("\n")
  text = text.replace(/^(\s*quickAccess: )\[([^\]]*)\],$/m, (whole, head, body) => {
    const entries = [...body.matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((x) => unesc(x[1]))
    const kept = []
    for (const q of entries) {
      if (names.includes(q)) {
        kept.push(q)
        continue
      }
      // The entry may simply have been title-cased along with its waypoint.
      const cleaned = cleanLabel(q)
      if (cleaned && names.includes(cleaned.text)) {
        kept.push(cleaned.text)
        quickFixed++
        continue
      }
      const best = names
        .map((n) => ({ n, s: similarity(q, n) }))
        .sort((a, b) => b.s - a.s)[0]
      if (best && best.s >= 0.6) {
        kept.push(best.n)
        quickFixed++
        detail.push(`  ${file}: quickAccess "${q}" -> "${best.n}"`)
      } else {
        quickDropped++
        detail.push(`  ${file}: quickAccess "${q}" dropped (no waypoint)`)
      }
    }
    return `${head}[${[...new Set(kept)].map((q) => `"${esc(q)}"`).join(", ")}],`
  })

  if (dropped + renamed + retyped + described + quickFixed + quickDropped === 0) continue

  totals.files++
  totals.dropped += dropped
  totals.renamed += renamed
  totals.retyped += retyped
  totals.described += described
  totals.quickFixed += quickFixed
  totals.quickDropped += quickDropped
  if (!DRY) writeFileSync(path, text)
}

if (process.argv.includes("--verbose")) for (const d of detail) console.log(d)
console.log(
  `${DRY ? "[dry run] " : ""}${totals.files} venue modules updated: ` +
    `${totals.dropped} waypoints dropped, ${totals.renamed} renamed, ${totals.retyped} retyped, ` +
    `${totals.described} given a storey description, ` +
    `${totals.quickFixed} quickAccess entries repaired, ${totals.quickDropped} dropped`
)
