import { Venue } from "../types"

// Stratford Hospital — reconstructed from the trust's own map sheet
// (map/auto/a5-site-map-of-stratford-hospital-july-2025-update.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const A5_SITE_MAP_OF_STRATFORD_HOSPITAL_JULY_2025_UPDATE_VENUE: Venue = {
  id: "a5-site-map-of-stratford-hospital-july-2025-update-venue",
  slug: "a5-site-map-of-stratford-hospital-july-2025-update",
  name: "Stratford Hospital",
  subtitle: "South Warwickshire University NHS Foundation Trust · CV37 6NX",
  category: "hospital",
  center: { lat: 52.195279, lng: -1.713391 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by South Warwickshire University NHS Foundation Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["Outpatients", "Stratford Hospital", "Building Two", "Multi-Storey", "Radiology"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/a5-site-map-of-stratford-hospital-july-2025-update/sitemap.svg", bounds: [[52.194371, -1.715494], [52.196187, -1.711288]] },
  ],
  waypoints: [
    { id: "stratford-hospital-f0", name: "Stratford Hospital", type: "department", coordinates: { lat: 52.196045, lng: -1.713391 }, floor: 0 },
    { id: "building-two-f0", name: "Building Two", type: "department", coordinates: { lat: 52.195806, lng: -1.712742 }, floor: 0 },
    { id: "multi-storey-f0", name: "Multi-Storey", type: "other", coordinates: { lat: 52.195746, lng: -1.714736 }, floor: 0 },
    { id: "radiology-f0", name: "Radiology", type: "department", coordinates: { lat: 52.195739, lng: -1.712839 }, floor: 0 },
    { id: "car-park-f0", name: "Car Park", type: "other", coordinates: { lat: 52.195701, lng: -1.714736 }, floor: 0 },
    { id: "outpatients-f0", name: "Outpatients", type: "department", coordinates: { lat: 52.195681, lng: -1.712817 }, floor: 0 },
    { id: "minor-injuries-f0", name: "Minor Injuries", type: "other", coordinates: { lat: 52.195623, lng: -1.712793 }, floor: 0 },
    { id: "audiology-f0", name: "Audiology", type: "department", coordinates: { lat: 52.195565, lng: -1.712835 }, floor: 0 },
    { id: "nicol-unit-f0", name: "Nicol Unit", type: "department", coordinates: { lat: 52.195507, lng: -1.712842 }, floor: 0 },
    { id: "car-parking-f0", name: "Car Parking", type: "other", coordinates: { lat: 52.195452, lng: -1.714434 }, floor: 0 },
    { id: "physiotherapy-f0", name: "Physiotherapy", type: "department", coordinates: { lat: 52.195449, lng: -1.712789 }, floor: 0 },
    { id: "local-surgery-unit-f0", name: "Local Surgery Unit", type: "department", coordinates: { lat: 52.195391, lng: -1.712741 }, floor: 0 },
    { id: "community-diagnostic-centre-cdc-f0", name: "Community Diagnostic Centre (Cdc)", type: "department", coordinates: { lat: 52.195247, lng: -1.714945 }, floor: 0 },
    { id: "building-one-f0", name: "Building One", type: "department", coordinates: { lat: 52.195279, lng: -1.71275 }, floor: 0 },
    { id: "new-building-f0", name: "(New Building)", type: "department", coordinates: { lat: 52.195277, lng: -1.712331 }, floor: 0 },
    { id: "caf-lomas-f0", name: "Café Lomas", type: "canteen", coordinates: { lat: 52.195172, lng: -1.712822 }, floor: 0 },
    { id: "health-wellbeing-information-centre-f0", name: "Health & Wellbeing Information Centre", type: "department", coordinates: { lat: 52.195135, lng: -1.712495 }, floor: 0 },
    { id: "material-storage-f0", name: "Material Storage", type: "other", coordinates: { lat: 52.195103, lng: -1.714434 }, floor: 0 },
    { id: "welfare-facilities-f0", name: "Welfare Facilities", type: "other", coordinates: { lat: 52.195103, lng: -1.713971 }, floor: 0 },
    { id: "lomas-suite-f0", name: "Lomas Suite", type: "department", coordinates: { lat: 52.195077, lng: -1.712815 }, floor: 0 },
    { id: "pharmacy-f0", name: "Pharmacy", type: "pharmacy", coordinates: { lat: 52.195019, lng: -1.712843 }, floor: 0 },
    { id: "1st-floor-f0", name: "1st Floor", type: "other", coordinates: { lat: 52.194969, lng: -1.712843 }, floor: 0 },
    { id: "stratford-eye-unit-outpatients-f0", name: "Stratford Eye Unit-Outpatients", type: "department", coordinates: { lat: 52.194921, lng: -1.712595 }, floor: 0 },
    { id: "stratford-day-theatre-f0", name: "Stratford Day Theatre", type: "department", coordinates: { lat: 52.194863, lng: -1.7127 }, floor: 0 },
    { id: "2nd-floor-f0", name: "2nd Floor", type: "other", coordinates: { lat: 52.194813, lng: -1.712834 }, floor: 0 },
    { id: "building-one-new-building-f0", name: "Building One (New Building)", type: "department", coordinates: { lat: 52.194796, lng: -1.714384 }, floor: 0 },
    { id: "the-rigby-unit-f0", name: "The Rigby Unit", type: "department", coordinates: { lat: 52.194765, lng: -1.712783 }, floor: 0 },
    { id: "macmillan-information-support-centre-f0", name: "Macmillan Information & Support Centre", type: "department", coordinates: { lat: 52.194707, lng: -1.712477 }, floor: 0 },
    { id: "patient-drop-off-f0", name: "Patient Drop Off", type: "exit", coordinates: { lat: 52.194625, lng: -1.713981 }, floor: 0 },
  ],
}
