import { Venue } from "../types"

// Basildon & Thurrock University Hospital — Mid and South Essex NHS
// Foundation Trust. The floor plan is the trust's isometric site map; the
// buildings it labels are placed at their positions, and a set of wards from
// the Level/Area directory (Level A-D = floors 0-3) sits on the Ward Block.
// A curated set — extend via the in-app plan importer.
// Generated by scripts/sheets/generate-batch4.py — edit that, not this.

export const BASILDON_VENUE: Venue = {
  id: "basildon-hospital",
  slug: "basildon-hospital",
  name: "Basildon & Thurrock University Hospital",
  subtitle: "Mid and South Essex NHS Foundation Trust · Nethermayne, Basildon SS16 5NL",
  category: "hospital",
  center: { lat: 51.556289, lng: 0.461 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Level isometric site with marked entrances, accessible parking and information points; levels A-D served by lifts." },
  quickAccess: ["Main Entrance", "Emergency Department", "X-Ray", "The Essex Cardiothoracic Centre", "Outpatients Entrance"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/basildon/sitemap.svg", bounds: [[51.554789, 0.457], [51.557789, 0.465]] },
    { id: "f1", floor: 1, label: "First Floor", imageUrl: "/floorplans/basildon/sitemap.svg", bounds: [[51.554789, 0.457], [51.557789, 0.465]] },
    { id: "f2", floor: 2, label: "Second Floor", imageUrl: "/floorplans/basildon/sitemap.svg", bounds: [[51.554789, 0.457], [51.557789, 0.465]] },
    { id: "f3", floor: 3, label: "Third Floor", imageUrl: "/floorplans/basildon/sitemap.svg", bounds: [[51.554789, 0.457], [51.557789, 0.465]] },
  ],
  waypoints: [
    // ── Buildings & entrances ─────────────────────────────────────────
    { id: "main-entrance-f0", name: "Main Entrance", type: "exit", coordinates: { lat: 51.556069, lng: 0.460034 }, floor: 0 },
    { id: "emergency-department-f0", name: "Emergency Department", type: "department", coordinates: { lat: 51.55626, lng: 0.461015 }, floor: 0 },
    { id: "childrens-wards-f0", name: "Children's Wards", type: "ward", coordinates: { lat: 51.556853, lng: 0.459483 }, floor: 0 },
    { id: "ante-natal-f0", name: "Ante-Natal", type: "department", coordinates: { lat: 51.5567, lng: 0.459207 }, floor: 0 },
    { id: "childrens-outpatients-f0", name: "Children's Outpatients", type: "department", coordinates: { lat: 51.556585, lng: 0.458962 }, floor: 0 },
    { id: "renal-unit-f0", name: "Renal Unit", type: "department", coordinates: { lat: 51.556337, lng: 0.459115 }, floor: 0 },
    { id: "restaurant-f0", name: "Restaurant", type: "canteen", coordinates: { lat: 51.556566, lng: 0.459973 }, floor: 0 },
    { id: "x-ray-f0", name: "X-Ray", type: "department", coordinates: { lat: 51.556471, lng: 0.461506 }, floor: 0 },
    { id: "pharmacy-f0", name: "Pharmacy", type: "pharmacy", coordinates: { lat: 51.55649, lng: 0.461935 }, floor: 0 },
    { id: "ent-f0", name: "ENT", type: "department", coordinates: { lat: 51.556471, lng: 0.462395 }, floor: 0 },
    { id: "blood-testing-f0", name: "Blood Testing", type: "department", coordinates: { lat: 51.556337, lng: 0.4631 }, floor: 0 },
    { id: "fracture-clinic-f0", name: "Fracture Clinic", type: "department", coordinates: { lat: 51.556299, lng: 0.46405 }, floor: 0 },
    { id: "physiotherapy-f0", name: "Physiotherapy", type: "department", coordinates: { lat: 51.556146, lng: 0.464111 }, floor: 0 },
    { id: "breast-care-unit-f0", name: "Breast Care Unit", type: "department", coordinates: { lat: 51.555993, lng: 0.464111 }, floor: 0 },
    { id: "dermatology-unit-f0", name: "Dermatology Unit", type: "department", coordinates: { lat: 51.555859, lng: 0.463284 }, floor: 0 },
    { id: "ward-block-f0", name: "Ward Block", type: "ward", coordinates: { lat: 51.556757, lng: 0.462272 }, floor: 0 },
    { id: "jubilee-wing-f0", name: "Jubilee Wing", type: "ward", coordinates: { lat: 51.556738, lng: 0.463375 }, floor: 0 },
    { id: "the-essex-cardiothoracic-centre-f0", name: "The Essex Cardiothoracic Centre", type: "department", coordinates: { lat: 51.557139, lng: 0.462609 }, floor: 0 },
    { id: "basildon-day-unit-f0", name: "Basildon Day Unit", type: "department", coordinates: { lat: 51.556853, lng: 0.462057 }, floor: 0 },
    { id: "day-nursery-f0", name: "Day Nursery", type: "other", coordinates: { lat: 51.557426, lng: 0.460739 }, floor: 0 },
    { id: "education-centre-f0", name: "Education Centre", type: "department", coordinates: { lat: 51.556165, lng: 0.464847 }, floor: 0 },
    { id: "endoscopy-entrance-f0", name: "Endoscopy Entrance", type: "exit", coordinates: { lat: 51.555993, lng: 0.461782 }, floor: 0 },
    { id: "outpatients-entrance-f0", name: "Outpatients Entrance", type: "exit", coordinates: { lat: 51.556012, lng: 0.462609 }, floor: 0 },
    // ── Wards (Ward Block / Jubilee Wing) ─────────────────────────────
    { id: "orsett-ward-f2", name: "Orsett Ward", type: "ward", coordinates: { lat: 51.556719, lng: 0.46218 }, floor: 2, description: "Level C" },
    { id: "osler-ward-f0", name: "Osler Ward", type: "ward", coordinates: { lat: 51.556719, lng: 0.462364 }, floor: 0, description: "Level A" },
    { id: "katherine-monk-ward-f0", name: "Katherine Monk Ward", type: "ward", coordinates: { lat: 51.556719, lng: 0.462548 }, floor: 0, description: "Level A" },
    { id: "kingswood-ward-f0", name: "Kingswood Ward", type: "ward", coordinates: { lat: 51.556719, lng: 0.462732 }, floor: 0, description: "Level A" },
    { id: "laindon-ward-f0", name: "Laindon Ward", type: "ward", coordinates: { lat: 51.556643, lng: 0.46218 }, floor: 0, description: "Level A" },
    { id: "linford-ward-f0", name: "Linford Ward", type: "ward", coordinates: { lat: 51.556643, lng: 0.462364 }, floor: 0, description: "Level A" },
    { id: "nethermayne-ward-f3", name: "Nethermayne Ward", type: "ward", coordinates: { lat: 51.556643, lng: 0.462548 }, floor: 3, description: "Level D" },
    { id: "chelmer-ward-f3", name: "Chelmer Ward", type: "ward", coordinates: { lat: 51.556643, lng: 0.462732 }, floor: 3, description: "Level D" },
    { id: "cardiac-rehab-f0", name: "Cardiac Rehab", type: "ward", coordinates: { lat: 51.556566, lng: 0.46218 }, floor: 0, description: "Level A" },
    { id: "cardiac-catheter-labs-f1", name: "Cardiac Catheter Labs", type: "ward", coordinates: { lat: 51.556566, lng: 0.462364 }, floor: 1, description: "Level B" },
    { id: "neonatal-intensive-care-unit-nicu-f0", name: "Neonatal Intensive Care Unit (NICU)", type: "ward", coordinates: { lat: 51.556566, lng: 0.462548 }, floor: 0, description: "Level A" },
    { id: "critical-care-unit-f0", name: "Critical Care Unit", type: "ward", coordinates: { lat: 51.556566, lng: 0.462732 }, floor: 0, description: "Level A" },
    { id: "elizabeth-fry-ward-f3", name: "Elizabeth Fry Ward", type: "ward", coordinates: { lat: 51.55649, lng: 0.46218 }, floor: 3, description: "Level D" },
    { id: "edith-cavell-ward-f2", name: "Edith Cavell Ward", type: "ward", coordinates: { lat: 51.55649, lng: 0.462364 }, floor: 2, description: "Level C" },
  ],
}
