import { Venue } from "../types"

// Broomfield Hospital — Mid and South Essex NHS Foundation Trust. The floor
// plan is the trust's colour-zoned wayfinding map (Zones A-E, Levels 1-4).
// Each department sits on its zone; the trust's destination code (e.g. A204
// = Zone A, Level 2) gives the zone and floor. A curated set from the sheet's
// directory — extend via the in-app plan importer.
// Generated by scripts/sheets/generate-batch4.py — edit that, not this.

export const BROOMFIELD_VENUE: Venue = {
  id: "broomfield-hospital",
  slug: "broomfield-hospital",
  name: "Broomfield Hospital",
  subtitle: "Mid and South Essex NHS Foundation Trust · Court Road, Broomfield, Chelmsford CM1 7ET",
  category: "hospital",
  center: { lat: 51.766262, lng: 0.464002 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Colour-coded zones (A-E) with lifts and stairs in every zone; Blue Badge parking near the Main and A&E entrances." },
  quickAccess: ["Main Entrance", "A&E / Accident & Emergency", "Main Outpatients", "Maternity", "Radiology / X-ray Outpatients"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/broomfield/sitemap.png", bounds: [[51.764762, 0.460512], [51.767762, 0.467492]] },
    { id: "f1", floor: 1, label: "First Floor", imageUrl: "/floorplans/broomfield/sitemap.png", bounds: [[51.764762, 0.460512], [51.767762, 0.467492]] },
    { id: "f2", floor: 2, label: "Second Floor", imageUrl: "/floorplans/broomfield/sitemap.png", bounds: [[51.764762, 0.460512], [51.767762, 0.467492]] },
    { id: "f3", floor: 3, label: "Third Floor", imageUrl: "/floorplans/broomfield/sitemap.png", bounds: [[51.764762, 0.460512], [51.767762, 0.467492]] },
    { id: "f4", floor: 4, label: "Fourth Floor", imageUrl: "/floorplans/broomfield/sitemap.png", bounds: [[51.764762, 0.460512], [51.767762, 0.467492]] },
  ],
  waypoints: [
    // ── Entrances ─────────────────────────────────────────────────────
    { id: "main-entrance-f0", name: "Main Entrance", type: "exit", coordinates: { lat: 51.765198, lng: 0.462709 }, floor: 0 },
    { id: "south-entrance-f0", name: "South Entrance", type: "exit", coordinates: { lat: 51.767293, lng: 0.462129 }, floor: 0 },
    { id: "east-entrance-f0", name: "East Entrance", type: "exit", coordinates: { lat: 51.765584, lng: 0.464864 }, floor: 0 },
    { id: "a-e-entrance-f0", name: "A&E Entrance", type: "exit", coordinates: { lat: 51.765473, lng: 0.460885 }, floor: 0 },
    { id: "central-corridor-f0", name: "Central Corridor", type: "department", coordinates: { lat: 51.766052, lng: 0.462709 }, floor: 0 },
    // ── Zone A ────────────────────────────────────────────────────────
    { id: "a-e-accident-emergency-f1", name: "A&E / Accident & Emergency", type: "department", coordinates: { lat: 51.765832, lng: 0.461208 }, floor: 1, description: "Zone A · Level 2 (A200)" },
    { id: "acute-medical-unit-amu-f1", name: "Acute Medical Unit (AMU)", type: "ward", coordinates: { lat: 51.765832, lng: 0.461407 }, floor: 1, description: "Zone A · Level 2 (A204)" },
    { id: "ambulatory-care-unit-acu-f1", name: "Ambulatory Care Unit (ACU)", type: "ward", coordinates: { lat: 51.765832, lng: 0.461606 }, floor: 1, description: "Zone A · Level 2 (A205)" },
    { id: "main-outpatients-f0", name: "Main Outpatients", type: "department", coordinates: { lat: 51.765832, lng: 0.461805 }, floor: 0, description: "Zone A · Level 1 (A101)" },
    { id: "audiology-f0", name: "Audiology", type: "department", coordinates: { lat: 51.765777, lng: 0.461208 }, floor: 0, description: "Zone A · Level 1 (A101)" },
    { id: "birthing-unit-f3", name: "Birthing Unit", type: "ward", coordinates: { lat: 51.765777, lng: 0.461407 }, floor: 3, description: "Zone A · Level 4 (A402)" },
    { id: "labour-ward-f3", name: "Labour Ward", type: "ward", coordinates: { lat: 51.765777, lng: 0.461606 }, floor: 3, description: "Zone A · Level 4 (A402)" },
    { id: "neonatal-unit-f3", name: "Neonatal Unit", type: "ward", coordinates: { lat: 51.765777, lng: 0.461805 }, floor: 3, description: "Zone A · Level 4 (A406)" },
    { id: "antenatal-day-assessment-unit-f3", name: "Antenatal Day Assessment Unit", type: "ward", coordinates: { lat: 51.765722, lng: 0.461208 }, floor: 3, description: "Zone A · Level 4 (A404)" },
    { id: "maternity-f3", name: "Maternity", type: "department", coordinates: { lat: 51.765722, lng: 0.461407 }, floor: 3, description: "Zone A · Level 4 (A404)" },
    { id: "fracture-clinic-f0", name: "Fracture Clinic", type: "department", coordinates: { lat: 51.765722, lng: 0.461606 }, floor: 0, description: "Zone A · Level 1 (A111)" },
    { id: "gynaecology-outpatients-f0", name: "Gynaecology Outpatients", type: "department", coordinates: { lat: 51.765722, lng: 0.461805 }, floor: 0, description: "Zone A · Level 1 (A111)" },
    { id: "general-theatres-f2", name: "General Theatres", type: "department", coordinates: { lat: 51.765666, lng: 0.461208 }, floor: 2, description: "Zone A · Level 3 (A325)" },
    { id: "renal-unit-f1", name: "Renal Unit", type: "ward", coordinates: { lat: 51.765666, lng: 0.461407 }, floor: 1, description: "Zone A · Level 2 (A208)" },
    { id: "endoscopy-f2", name: "Endoscopy", type: "department", coordinates: { lat: 51.765666, lng: 0.461606 }, floor: 2, description: "Zone A · Level 3 (A301)" },
    { id: "cardiac-centre-f1", name: "Cardiac Centre", type: "department", coordinates: { lat: 51.765666, lng: 0.461805 }, floor: 1, description: "Zone A · Level 2 (A210)" },
    { id: "chemotherapy-day-unit-f1", name: "Chemotherapy Day Unit", type: "department", coordinates: { lat: 51.765611, lng: 0.461208 }, floor: 1, description: "Zone A · Level 2 (A206)" },
    { id: "breast-unit-f0", name: "Breast Unit", type: "ward", coordinates: { lat: 51.765611, lng: 0.461407 }, floor: 0, description: "Zone A · Level 1 (A104)" },
    // ── Zone E ────────────────────────────────────────────────────────
    { id: "childrens-ward-f0", name: "Children's Ward", type: "ward", coordinates: { lat: 51.765915, lng: 0.46411 }, floor: 0, description: "Zone E · Level 1 (E122)" },
    // ── Zone A ────────────────────────────────────────────────────────
    { id: "childrens-outpatients-f0", name: "Children's Outpatients", type: "department", coordinates: { lat: 51.765611, lng: 0.461606 }, floor: 0, description: "Zone A · Level 1 (A101)" },
    // ── Zone E ────────────────────────────────────────────────────────
    { id: "burns-adults-ward-f1", name: "Burns Adults' Ward", type: "ward", coordinates: { lat: 51.765915, lng: 0.464309 }, floor: 1, description: "Zone E · Level 2 (E221)" },
    { id: "burns-childrens-ward-f1", name: "Burns Children's Ward", type: "ward", coordinates: { lat: 51.765915, lng: 0.464508 }, floor: 1, description: "Zone E · Level 2 (E225)" },
    { id: "burns-itu-f1", name: "Burns ITU", type: "ward", coordinates: { lat: 51.765915, lng: 0.464707 }, floor: 1, description: "Zone E · Level 2 (E220)" },
    { id: "burns-outpatients-f1", name: "Burns Outpatients", type: "department", coordinates: { lat: 51.765859, lng: 0.46411 }, floor: 1, description: "Zone E · Level 2 (E224)" },
    { id: "phoenix-unit-childrens-ward-f0", name: "Phoenix Unit - Children's Ward", type: "ward", coordinates: { lat: 51.765859, lng: 0.464309 }, floor: 0, description: "Zone E · Level 1 (E122)" },
    // ── Zone A ────────────────────────────────────────────────────────
    { id: "gosfield-ward-f1", name: "Gosfield Ward", type: "ward", coordinates: { lat: 51.765611, lng: 0.461805 }, floor: 1, description: "Zone A · Level 2 (A203)" },
    { id: "heybridge-ward-f2", name: "Heybridge Ward", type: "ward", coordinates: { lat: 51.765556, lng: 0.461208 }, floor: 2, description: "Zone A · Level 3 (A303)" },
    // ── Zone C ────────────────────────────────────────────────────────
    { id: "braxted-ward-f1", name: "Braxted Ward", type: "ward", coordinates: { lat: 51.767431, lng: 0.461208 }, floor: 1, description: "Zone C · Level 2 (C254)" },
    { id: "baddow-ward-f1", name: "Baddow Ward", type: "ward", coordinates: { lat: 51.767431, lng: 0.461407 }, floor: 1, description: "Zone C · Level 2 (C250)" },
    { id: "bardfield-ward-f2", name: "Bardfield Ward", type: "ward", coordinates: { lat: 51.767431, lng: 0.461606 }, floor: 2, description: "Zone C · Level 3 (C350)" },
    // ── Zone E ────────────────────────────────────────────────────────
    { id: "billericay-ward-f2", name: "Billericay Ward", type: "ward", coordinates: { lat: 51.765859, lng: 0.464508 }, floor: 2, description: "Zone E · Level 3 (E321)" },
    // ── Zone C ────────────────────────────────────────────────────────
    { id: "writtle-ward-f3", name: "Writtle Ward", type: "ward", coordinates: { lat: 51.767431, lng: 0.461805 }, floor: 3, description: "Zone C · Level 4 (C450)" },
    // ── Zone A ────────────────────────────────────────────────────────
    { id: "wizard-ward-f2", name: "Wizard Ward", type: "ward", coordinates: { lat: 51.765556, lng: 0.461407 }, floor: 2, description: "Zone A · Level 3 (A301)" },
    { id: "village-room-f3", name: "Village Room", type: "department", coordinates: { lat: 51.765556, lng: 0.461606 }, floor: 3, description: "Zone A · Level 4 (A407)" },
    // ── Zone D ────────────────────────────────────────────────────────
    { id: "radiology-x-ray-outpatients-f0", name: "Radiology / X-ray Outpatients", type: "department", coordinates: { lat: 51.766549, lng: 0.462452 }, floor: 0, description: "Zone D · Level 1 (D140)" },
    // ── Zone B ────────────────────────────────────────────────────────
    { id: "x-ray-inpatients-f2", name: "X-ray Inpatients", type: "department", coordinates: { lat: 51.766907, lng: 0.460711 }, floor: 2, description: "Zone B · Level 3 (B343)" },
    { id: "mri-f2", name: "MRI", type: "department", coordinates: { lat: 51.766907, lng: 0.46091 }, floor: 2, description: "Zone B · Level 3 (B342)" },
    { id: "ct-scan-f3", name: "CT Scan", type: "department", coordinates: { lat: 51.766907, lng: 0.461109 }, floor: 3, description: "Zone B · Level 4 (B448)" },
    { id: "ultrasound-f3", name: "Ultrasound", type: "department", coordinates: { lat: 51.766907, lng: 0.461308 }, floor: 3, description: "Zone B · Level 4 (B446)" },
    // ── Zone D ────────────────────────────────────────────────────────
    { id: "pathology-f1", name: "Pathology", type: "department", coordinates: { lat: 51.766549, lng: 0.462651 }, floor: 1, description: "Zone D · Level 2 (D228)" },
    // ── Zone A ────────────────────────────────────────────────────────
    { id: "pharmacy-shop-f0", name: "Pharmacy Shop", type: "pharmacy", coordinates: { lat: 51.765556, lng: 0.461805 }, floor: 0, description: "Zone A · Level 1 (A103)" },
    { id: "discharge-lounge-f1", name: "Discharge Lounge", type: "department", coordinates: { lat: 51.765501, lng: 0.461208 }, floor: 1, description: "Zone A · Level 2 (A204)" },
    // ── Zone B ────────────────────────────────────────────────────────
    { id: "day-stay-unit-dsu-f3", name: "Day Stay Unit (DSU)", type: "ward", coordinates: { lat: 51.766852, lng: 0.460711 }, floor: 3, description: "Zone B · Level 4 (B448)" },
    // ── Zone A ────────────────────────────────────────────────────────
    { id: "stroke-unit-f2", name: "Stroke Unit", type: "ward", coordinates: { lat: 51.765501, lng: 0.461407 }, floor: 2, description: "Zone A · Level 3 (A302)" },
    { id: "emergency-department-f1", name: "Emergency Department", type: "department", coordinates: { lat: 51.765501, lng: 0.461606 }, floor: 1, description: "Zone A · Level 2 (A200)" },
    // ── Zone E ────────────────────────────────────────────────────────
    { id: "general-intensive-care-unit-gicu-f1", name: "General Intensive Care Unit (GICU)", type: "ward", coordinates: { lat: 51.765859, lng: 0.464707 }, floor: 1, description: "Zone E · Level 2 (E226)" },
    // ── Zone B ────────────────────────────────────────────────────────
    { id: "surgical-emergency-ward-sew-f2", name: "Surgical Emergency Ward (SEW)", type: "ward", coordinates: { lat: 51.766852, lng: 0.46091 }, floor: 2, description: "Zone B · Level 3 (B344)" },
    // ── Zone A ────────────────────────────────────────────────────────
    { id: "cardiology-f1", name: "Cardiology", type: "department", coordinates: { lat: 51.765501, lng: 0.461805 }, floor: 1, description: "Zone A · Level 2 (A210)" },
    // ── Zone C ────────────────────────────────────────────────────────
    { id: "diabetes-centre-f3", name: "Diabetes Centre", type: "department", coordinates: { lat: 51.767376, lng: 0.461208 }, floor: 3, description: "Zone C · Level 4 (C453)" },
  ],
}
