import { Venue } from "../types"

// Dewsbury & District Hospital-Combined Elective Surgical Hub — reconstructed from the trust's own map sheet
// (map/auto/community-diagnostic-centre-site-map.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const COMMUNITY_DIAGNOSTIC_CENTRE_SITE_MAP_VENUE: Venue = {
  id: "community-diagnostic-centre-site-map-venue",
  slug: "community-diagnostic-centre-site-map",
  name: "Dewsbury & District Hospital-Combined Elective Surgical Hub",
  subtitle: "Mid Yorkshire Teaching NHS Trust · WF13 4HS",
  category: "hospital",
  center: { lat: 53.702267, lng: -1.651881 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Mid Yorkshire Teaching NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["MiCAD LINK", "Wickes", "Kfc", "Subway", "Currys"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/community-diagnostic-centre-site-map/sitemap.svg", bounds: [[53.700168, -1.656896], [53.704366, -1.646866]] },
  ],
  trails: [
    { id: "c0-1", floor: 0, points: [{ lat: 53.702167, lng: -1.650807 }, { lat: 53.702109, lng: -1.650542 }] },
    { id: "c0-2", floor: 0, points: [{ lat: 53.702091, lng: -1.650549 }, { lat: 53.702041, lng: -1.650822 }, { lat: 53.702041, lng: -1.651513 }] },
    { id: "c0-3", floor: 0, points: [{ lat: 53.702041, lng: -1.651983 }, { lat: 53.702041, lng: -1.651649 }, { lat: 53.702032, lng: -1.651634 }] },
    { id: "c0-4", floor: 0, points: [{ lat: 53.701979, lng: -1.650959 }, { lat: 53.70192, lng: -1.651316 }] },
    { id: "c0-5", floor: 0, points: [{ lat: 53.701552, lng: -1.652234 }, { lat: 53.701498, lng: -1.651976 }] },
  ],
  waypoints: [
    { id: "micad-link-f0", name: "MiCAD LINK", type: "other", coordinates: { lat: 53.703701, lng: -1.648134 }, floor: 0 },
    { id: "wickes-f0", name: "Wickes", type: "other", coordinates: { lat: 53.702762, lng: -1.654589 }, floor: 0 },
    { id: "kfc-f0", name: "Kfc", type: "other", coordinates: { lat: 53.702542, lng: -1.650371 }, floor: 0 },
    { id: "subway-f0", name: "Subway", type: "other", coordinates: { lat: 53.702191, lng: -1.64976 }, floor: 0 },
    { id: "currys-f0", name: "Currys", type: "other", coordinates: { lat: 53.702026, lng: -1.651586 }, floor: 0 },
    { id: "rev-description-f0", name: "Rev Description", type: "other", coordinates: { lat: 53.701711, lng: -1.64839 }, floor: 0 },
    { id: "date-sig-f0", name: "Date/Sig", type: "other", coordinates: { lat: 53.701711, lng: -1.647849 }, floor: 0 },
    { id: "the-mid-yorkshire-teaching-f0", name: "The Mid Yorkshire Teaching", type: "other", coordinates: { lat: 53.701638, lng: -1.648243 }, floor: 0 },
    { id: "nhs-trust-f0", name: "NHS Trust", type: "other", coordinates: { lat: 53.701605, lng: -1.648054 }, floor: 0 },
    { id: "scs-sofas-flooring-furniture-f0", name: "ScS - Sofas, Flooring & Furniture", type: "other", coordinates: { lat: 53.701541, lng: -1.652459 }, floor: 0 },
    { id: "jysk-f0", name: "Jysk", type: "other", coordinates: { lat: 53.701246, lng: -1.655131 }, floor: 0 },
    { id: "pets-at-home-f0", name: "Pets at Home", type: "other", coordinates: { lat: 53.701232, lng: -1.652813 }, floor: 0 },
    { id: "smyths-toys-superstores-f0", name: "Smyths Toys Superstores", type: "other", coordinates: { lat: 53.701101, lng: -1.654547 }, floor: 0 },
    { id: "unit-9b-f0", name: "Unit 9B", type: "department", coordinates: { lat: 53.701113, lng: -1.648469 }, floor: 0 },
    { id: "next-f0", name: "Next", type: "other", coordinates: { lat: 53.701098, lng: -1.653759 }, floor: 0 },
    { id: "a1-plan-f0", name: "A1 Plan", type: "other", coordinates: { lat: 53.700872, lng: -1.648454 }, floor: 0 },
    { id: "wf-cdc-gf-f0", name: "Wf-Cdc-GF", type: "other", coordinates: { lat: 53.700621, lng: -1.648402 }, floor: 0 },
    { id: "nts-f0", name: "Nts", type: "other", coordinates: { lat: 53.700621, lng: -1.648069 }, floor: 0 },
  ],
}
