import { Venue } from "../types"

// Ealing Hospital — reconstructed from the trust's own map sheet
// (map/auto/ealing-hospital-site-map.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const EALING_HOSPITAL_SITE_MAP_VENUE: Venue = {
  id: "ealing-hospital-site-map-venue",
  slug: "ealing-hospital-site-map",
  name: "Ealing Hospital",
  subtitle: "London North West University Healthcare NHS Trust · UB1 3HW",
  category: "hospital",
  center: { lat: 51.507606, lng: -0.345474 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by London North West University Healthcare NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["Entrances", "A&E (no children’sA&E)", "Urgent care centre", "Outpatients", "Main entrance"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/ealing-hospital-site-map/sitemap.svg", bounds: [[51.503515, -0.350121], [51.511697, -0.340827]] },
  ],
  waypoints: [
    { id: "ealing-hospital-f0", name: "Ealing Hospital", type: "department", coordinates: { lat: 51.510344, lng: -0.347034 }, floor: 0 },
    { id: "entrances-f0", name: "Entrances", type: "exit", coordinates: { lat: 51.505899, lng: -0.349252 }, floor: 0 },
    { id: "other-options-f0", name: "Other options", type: "other", coordinates: { lat: 51.505899, lng: -0.343333 }, floor: 0 },
    { id: "a-e-no-childrensa-e-f0", name: "A&E (no children’sA&E)", type: "department", coordinates: { lat: 51.505746, lng: -0.34859 }, floor: 0 },
    { id: "195-207-483-n83-n207-sl8-f0", name: "195, 207, 483, N83, N207, SL8", type: "other", coordinates: { lat: 51.505746, lng: -0.345533 }, floor: 0 },
    { id: "urgent-care-centre-f0", name: "Urgent care centre", type: "department", coordinates: { lat: 51.5056, lng: -0.348776 }, floor: 0 },
    { id: "195-207-n207-sl8-f0", name: "195, 207, N207, SL8", type: "other", coordinates: { lat: 51.5056, lng: -0.345893 }, floor: 0 },
    { id: "walking-routes-f0", name: "Walking routes", type: "other", coordinates: { lat: 51.5056, lng: -0.343172 }, floor: 0 },
    { id: "outpatients-f0", name: "Outpatients", type: "department", coordinates: { lat: 51.505455, lng: -0.349024 }, floor: 0 },
    { id: "483-n83-f0", name: "483, N83", type: "other", coordinates: { lat: 51.505455, lng: -0.346275 }, floor: 0 },
    { id: "west-ealing-1-4-miles-f0", name: "West Ealing (1.4 miles)", type: "other", coordinates: { lat: 51.505455, lng: -0.342908 }, floor: 0 },
    { id: "main-entrance-f0", name: "Main entrance", type: "exit", coordinates: { lat: 51.505309, lng: -0.348928 }, floor: 0 },
    { id: "elizabeth-line-and-national-rail-f0", name: "Elizabeth Line and National Rail", type: "other", coordinates: { lat: 51.505309, lng: -0.342563 }, floor: 0 },
    { id: "all-wards-f0", name: "All wards", type: "ward", coordinates: { lat: 51.505163, lng: -0.349119 }, floor: 0 },
    { id: "ealing-broadway-2-miles-f0", name: "Ealing Broadway (2 miles)", type: "other", coordinates: { lat: 51.505163, lng: -0.342789 }, floor: 0 },
    { id: "ealing-community-f0", name: "Ealing Community", type: "department", coordinates: { lat: 51.505017, lng: -0.348789 }, floor: 0 },
    { id: "central-district-elizabeth-line-f0", name: "Central, District, Elizabeth Line,", type: "other", coordinates: { lat: 51.505017, lng: -0.342585 }, floor: 0 },
    { id: "92-195-207-282-483-n207-f0", name: "92, 195, 207, 282, 483, N207", type: "other", coordinates: { lat: 51.504871, lng: -0.34558 }, floor: 0 },
    { id: "meadow-house-hospice-f0", name: "Meadow House Hospice", type: "department", coordinates: { lat: 51.504726, lng: -0.348586 }, floor: 0 },
    { id: "drayton-green-1-5-miles-f0", name: "Drayton Green (1.5 miles)", type: "other", coordinates: { lat: 51.504726, lng: -0.342798 }, floor: 0 },
    { id: "renal-dialysis-f0", name: "Renal dialysis", type: "department", coordinates: { lat: 51.50458, lng: -0.348976 }, floor: 0 },
    { id: "rehabilitation-services-f0", name: "Rehabilitation services", type: "other", coordinates: { lat: 51.504434, lng: -0.348646 }, floor: 0 },
    { id: "moorfields-community-eye-clinic-f0", name: "Moorfields community eye clinic", type: "department", coordinates: { lat: 51.504288, lng: -0.348282 }, floor: 0 },
    { id: "not-to-scale-check-f0", name: "Not to scale. Check", type: "other", coordinates: { lat: 51.503917, lng: -0.348989 }, floor: 0 },
  ],
}
