import { Venue } from "../types"

// Fordcombe Hospital — reconstructed from the trust's own map sheet
// (map/auto/fordcombe-hospital-mappdf.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const FORDCOMBE_HOSPITAL_MAPPDF_VENUE: Venue = {
  id: "fordcombe-hospital-mappdf-venue",
  slug: "fordcombe-hospital-mappdf",
  name: "Fordcombe Hospital",
  subtitle: "Maidstone and Tunbridge Wells NHS Trust · TN3 0RD",
  category: "hospital",
  center: { lat: 51.134511, lng: 0.188172 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Maidstone and Tunbridge Wells NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale estimated) and has not been checked by eye." },
  quickAccess: ["Main entrance and reception", "Main entrance", "Welcome to Fordcombe Hospital", "Department", "Area"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/fordcombe-hospital-mappdf/sitemap.svg", bounds: [[51.133082, 0.184951], [51.13594, 0.191393]] },
  ],
  waypoints: [
    { id: "welcome-to-fordcombe-hospital-f0", name: "Welcome to Fordcombe Hospital", type: "department", coordinates: { lat: 51.135449, lng: 0.185878 }, floor: 0 },
    { id: "department-f0", name: "Department", type: "department", coordinates: { lat: 51.134844, lng: 0.185385 }, floor: 0 },
    { id: "area-f0", name: "Area", type: "other", coordinates: { lat: 51.134844, lng: 0.186567 }, floor: 0 },
    { id: "cardiology-f0", name: "Cardiology", type: "department", coordinates: { lat: 51.134772, lng: 0.185364 }, floor: 0 },
    { id: "consultation-rooms-1-3-8-10-f0", name: "Consultation rooms 1-3 & 8 -10", type: "other", coordinates: { lat: 51.1347, lng: 0.185682 }, floor: 0 },
    { id: "consultation-rooms-4-7-f0", name: "Consultation rooms 4-7", type: "other", coordinates: { lat: 51.134628, lng: 0.185567 }, floor: 0 },
    { id: "ct-mri-reception-f0", name: "CT & MRI reception", type: "reception", coordinates: { lat: 51.134556, lng: 0.185499 }, floor: 0 },
    { id: "endoscopy-f0", name: "Endoscopy", type: "department", coordinates: { lat: 51.134484, lng: 0.18536 }, floor: 0 },
    { id: "inpatient-physiotherapy-f0", name: "Inpatient physiotherapy", type: "department", coordinates: { lat: 51.134412, lng: 0.185574 }, floor: 0 },
    { id: "main-reception-f0", name: "Main reception", type: "reception", coordinates: { lat: 51.13434, lng: 0.185434 }, floor: 0 },
    { id: "orthopaedic-centre-reception-f0", name: "Orthopaedic centre reception", type: "reception", coordinates: { lat: 51.134268, lng: 0.185664 }, floor: 0 },
    { id: "pharmacy-f0", name: "Pharmacy", type: "pharmacy", coordinates: { lat: 51.134124, lng: 0.185345 }, floor: 0 },
    { id: "waiting-area-and-refreshments-f0", name: "Waiting area and refreshments", type: "other", coordinates: { lat: 51.134052, lng: 0.185688 }, floor: 0 },
    { id: "ward-inpatient-rooms-f0", name: "Ward – inpatient rooms", type: "ward", coordinates: { lat: 51.13398, lng: 0.18557 }, floor: 0 },
    { id: "x-ray-reception-f0", name: "X-ray reception", type: "reception", coordinates: { lat: 51.133908, lng: 0.185436 }, floor: 0 },
    { id: "main-entrance-and-reception-f0", name: "Main entrance and reception", type: "exit", coordinates: { lat: 51.133547, lng: 0.188997 }, floor: 0 },
    { id: "disabled-wc-f0", name: "Disabled WC", type: "toilet", coordinates: { lat: 51.133454, lng: 0.185857 }, floor: 0 },
    { id: "main-entrance-f0", name: "Main entrance", type: "exit", coordinates: { lat: 51.133454, lng: 0.186466 }, floor: 0 },
  ],
}
