import { Venue } from "../types"

// Hammersmith Hospital — reconstructed from the trust's own site map sheet
// (map/Hammersmith Hospital location map.pdf). Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const HAMMERSMITH_VENUE: Venue = {
  id: "hammersmith-hospital",
  slug: "hammersmith",
  name: "Hammersmith Hospital",
  subtitle: "Imperial College Healthcare NHS Trust · Du Cane Road, London W12 0HS",
  category: "hospital",
  center: { lat: 51.517422, lng: -0.234707 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map with lettered building zones, main and Urgent Treatment Centre entrances, and bus stops on Du Cane Road." },
  quickAccess: ["Main entrance", "Urgent Treatment Centre", "A Block", "Heart attack centre", "Outpatients, x-ray and pharmacy"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/hammersmith/sitemap.svg", bounds: [[51.516152, -0.237811], [51.518883, -0.231603]] },
  ],
  waypoints: [
    { id: "main-entrance-f0", name: "Main entrance", type: "exit", coordinates: { lat: 51.518387, lng: -0.234879 }, floor: 0 },
    { id: "catherine-lewis-centre-f0", name: "Catherine Lewis centre", type: "department", coordinates: { lat: 51.518302, lng: -0.234161 }, floor: 0 },
    { id: "wormwood-scrubs-car-park-f0", name: "Wormwood scrubs car park", type: "other", coordinates: { lat: 51.51825, lng: -0.237411 }, floor: 0 },
    { id: "garry-weston-centre-f0", name: "Garry Weston centre", type: "department", coordinates: { lat: 51.517989, lng: -0.234772 }, floor: 0 },
    { id: "mrc-clinical-sciences-centre-f0", name: "MRC Clinical Sciences centre", type: "department", coordinates: { lat: 51.517829, lng: -0.234842 }, floor: 0 },
    { id: "wolfson-education-centre-f0", name: "Wolfson education centre", type: "department", coordinates: { lat: 51.517806, lng: -0.234444 }, floor: 0 },
    { id: "commonwealth-building-f0", name: "Commonwealth building", type: "department", coordinates: { lat: 51.517815, lng: -0.233621 }, floor: 0 },
    { id: "restaurant-f0", name: "Restaurant", type: "canteen", coordinates: { lat: 51.517793, lng: -0.235405 }, floor: 0 },
    { id: "renal-building-f0", name: "Renal building", type: "department", coordinates: { lat: 51.517769, lng: -0.236104 }, floor: 0 },
    { id: "hammersmith-house-f0", name: "Hammersmith House", type: "department", coordinates: { lat: 51.517694, lng: -0.236374 }, floor: 0 },
    { id: "w12-conference-centre-f0", name: "W12 conference centre", type: "department", coordinates: { lat: 51.517664, lng: -0.237206 }, floor: 0 },
    { id: "heart-attack-centre-f0", name: "Heart attack centre", type: "department", coordinates: { lat: 51.517647, lng: -0.233542 }, floor: 0 },
    { id: "outpatients-x-ray-and-pharmacy-f0", name: "Outpatients, x-ray and pharmacy", type: "pharmacy", coordinates: { lat: 51.517563, lng: -0.233196 }, floor: 0 },
    { id: "robert-lisa-sainsbury-wing-f0", name: "Robert & Lisa Sainsbury wing", type: "department", coordinates: { lat: 51.517446, lng: -0.235428 }, floor: 0 },
    { id: "imperial-clinical-research-facility-f0", name: "Imperial Clinical Research Facility", type: "department", coordinates: { lat: 51.517302, lng: -0.233463 }, floor: 0 },
    { id: "dcc-f0", name: "DCC", type: "other", coordinates: { lat: 51.517204, lng: -0.236224 }, floor: 0 },
    { id: "queen-charlottes-chelsea-hospital-f0", name: "Queen Charlotte’s & Chelsea Hospital", type: "department", coordinates: { lat: 51.517167, lng: -0.237289 }, floor: 0 },
    { id: "burlington-danes-f0", name: "Burlington Danes", type: "other", coordinates: { lat: 51.517096, lng: -0.233804 }, floor: 0 },
    { id: "ccd-f0", name: "CCD", type: "other", coordinates: { lat: 51.517028, lng: -0.236286 }, floor: 0 },
    { id: "nursery-f0", name: "Nursery", type: "other", coordinates: { lat: 51.516946, lng: -0.232404 }, floor: 0 },
    { id: "south-admin-f0", name: "South admin", type: "other", coordinates: { lat: 51.516933, lng: -0.235631 }, floor: 0 },
    { id: "east-acton-f0", name: "East Acton", type: "other", coordinates: { lat: 51.516489, lng: -0.23759 }, floor: 0 },
    { id: "urgent-treatment-centre-f0", name: "URGENT TREATMENT CENTRE", type: "department", coordinates: { lat: 51.516378, lng: -0.234957 }, floor: 0 },
    { id: "white-city-f0", name: "White City", type: "other", coordinates: { lat: 51.516329, lng: -0.232013 }, floor: 0 },
  ],
}
