import { Venue } from "../types"

// West Hull Health Hub — reconstructed from the trust's own map sheet
// (map/auto/hull-royal-infirmary-site-map.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const HULL_ROYAL_INFIRMARY_SITE_MAP_VENUE: Venue = {
  id: "hull-royal-infirmary-site-map-venue",
  slug: "hull-royal-infirmary-site-map",
  name: "West Hull Health Hub",
  subtitle: "Hull University Teaching Hospitals NHS Trust · HU4 6BN",
  category: "hospital",
  center: { lat: 53.746397, lng: -0.394505 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Hull University Teaching Hospitals NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale estimated) and has not been checked by eye." },
  quickAccess: ["Emergency Department - Childrens", "Emergency Department", "Entrances", "Urgent Treatment Centre (UTC) - Building 7", "Hospital Car Park"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/hull-royal-infirmary-site-map/sitemap.svg", bounds: [[53.744917, -0.397923], [53.747877, -0.391087]] },
  ],
  waypoints: [
    { id: "hospital-car-park-f0", name: "Hospital Car Park", type: "other", coordinates: { lat: 53.747193, lng: -0.39588 }, floor: 0 },
    { id: "main-hospital-f0", name: "Main Hospital", type: "department", coordinates: { lat: 53.747066, lng: -0.3946 }, floor: 0 },
    { id: "emergency-department-childrens-f0", name: "Emergency Department - Childrens", type: "department", coordinates: { lat: 53.746953, lng: -0.394453 }, floor: 0 },
    { id: "emergency-department-f0", name: "Emergency Department", type: "department", coordinates: { lat: 53.746736, lng: -0.39467 }, floor: 0 },
    { id: "patient-drop-off-f0", name: "Patient Drop Off", type: "exit", coordinates: { lat: 53.746416, lng: -0.394874 }, floor: 0 },
    { id: "main-gate-f0", name: "Main Gate", type: "other", coordinates: { lat: 53.746258, lng: -0.394103 }, floor: 0 },
    { id: "pedestrian-walkways-f0", name: "Pedestrian Walkways", type: "other", coordinates: { lat: 53.745915, lng: -0.397094 }, floor: 0 },
    { id: "entrances-f0", name: "Entrances", type: "exit", coordinates: { lat: 53.745888, lng: -0.395414 }, floor: 0 },
    { id: "patient-visitor-parking-f0", name: "Patient/ Visitor Parking", type: "other", coordinates: { lat: 53.745819, lng: -0.396148 }, floor: 0 },
    { id: "neurophysiology-liaison-psychiatry-f0", name: "Neurophysiology & Liaison Psychiatry", type: "department", coordinates: { lat: 53.745609, lng: -0.392193 }, floor: 0 },
    { id: "allam-diabetes-centre-building-1-f0", name: "Allam Diabetes Centre - Building 1", type: "department", coordinates: { lat: 53.745576, lng: -0.397119 }, floor: 0 },
    { id: "eye-clinic-first-floor-clinical-skills-f0", name: "Eye Clinic (First Floor) & Clinical Skills", type: "department", coordinates: { lat: 53.745567, lng: -0.395452 }, floor: 0 },
    { id: "building-34-f0", name: "Building 34", type: "department", coordinates: { lat: 53.745551, lng: -0.392623 }, floor: 0 },
    { id: "building-31-f0", name: "Building 31", type: "department", coordinates: { lat: 53.745509, lng: -0.395848 }, floor: 0 },
    { id: "occupational-health-entrance-a-b-f0", name: "Occupational Health (Entrance A & B)", type: "exit", coordinates: { lat: 53.74548, lng: -0.39219 }, floor: 0 },
    { id: "alderson-house-building-11-f0", name: "Alderson House - Building 11", type: "department", coordinates: { lat: 53.74545, lng: -0.397199 }, floor: 0 },
    { id: "medical-education-centre-building-20-f0", name: "Medical Education Centre - Building 20", type: "department", coordinates: { lat: 53.74545, lng: -0.393778 }, floor: 0 },
    { id: "building-10-f0", name: "Building 10", type: "department", coordinates: { lat: 53.745423, lng: -0.392613 }, floor: 0 },
    { id: "eye-hospital-eye-clinic-ground-floor-f0", name: "Eye Hospital & Eye Clinic (Ground Floor)", type: "department", coordinates: { lat: 53.74539, lng: -0.39538 }, floor: 0 },
    { id: "mortuary-bereavement-services-f0", name: "Mortuary & Bereavement Services", type: "other", coordinates: { lat: 53.745357, lng: -0.393868 }, floor: 0 },
    { id: "building-30-f0", name: "Building 30", type: "department", coordinates: { lat: 53.745332, lng: -0.395847 }, floor: 0 },
    { id: "anlaby-suite-building-14-f0", name: "Anlaby Suite - Building 14", type: "department", coordinates: { lat: 53.745325, lng: -0.397254 }, floor: 0 },
    { id: "therapies-centre-building-17-f0", name: "Therapies Centre - Building 17", type: "department", coordinates: { lat: 53.745322, lng: -0.392313 }, floor: 0 },
    { id: "building-24-f0", name: "Building 24", type: "department", coordinates: { lat: 53.745299, lng: -0.394228 }, floor: 0 },
    { id: "urgent-treatment-centre-utc-building-7-f0", name: "Urgent Treatment Centre (UTC) - Building 7", type: "department", coordinates: { lat: 53.745206, lng: -0.392089 }, floor: 0 },
    { id: "dialysis-unit-fresenius-building-building-5-f0", name: "Dialysis Unit / Fresenius Building - Building 5", type: "department", coordinates: { lat: 53.7452, lng: -0.396947 }, floor: 0 },
    { id: "hull-york-medical-school-building-18-f0", name: "Hull York Medical School - Building 18", type: "department", coordinates: { lat: 53.7452, lng: -0.39542 }, floor: 0 },
  ],
}
