import { Venue } from "../types"

// Cuh at Doddington Hospital — reconstructed from the trust's own map sheet
// (map/auto/level-3-floorplan-cuh-map.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const LEVEL_3_FLOORPLAN_CUH_MAP_VENUE: Venue = {
  id: "level-3-floorplan-cuh-map-venue",
  slug: "level-3-floorplan-cuh-map",
  name: "Cuh at Doddington Hospital",
  subtitle: "Cambridge University Hospitals NHS Foundation Trust · PE15 0UG",
  category: "hospital",
  center: { lat: 52.499909, lng: 0.055868 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Cambridge University Hospitals NHS Foundation Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["Wards /clinics", "Wards / on", "Lifts", "Stairs", "Toilets with disabled access"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/level-3-floorplan-cuh-map/sitemap.svg", bounds: [[52.498862, 0.053433], [52.500956, 0.058303]] },
  ],
  waypoints: [
    { id: "wards-clinics-f0", name: "Wards /clinics", type: "ward", coordinates: { lat: 52.500701, lng: 0.057735 }, floor: 0 },
    { id: "wards-on-f0", name: "Wards / on", type: "ward", coordinates: { lat: 52.5006, lng: 0.057624 }, floor: 0 },
    { id: "lifts-f0", name: "Lifts", type: "lift", coordinates: { lat: 52.500508, lng: 0.057609 }, floor: 0 },
    { id: "stairs-f0", name: "Stairs", type: "stairs", coordinates: { lat: 52.500417, lng: 0.057627 }, floor: 0 },
    { id: "toilets-with-disabled-access-f0", name: "Toilets with disabled access", type: "toilet", coordinates: { lat: 52.50032, lng: 0.057737 }, floor: 0 },
    { id: "baby-change-f0", name: "Baby change", type: "other", coordinates: { lat: 52.500124, lng: 0.05773 }, floor: 0 },
    { id: "dxa-f0", name: "Dxa", type: "other", coordinates: { lat: 52.499798, lng: 0.055907 }, floor: 0 },
    { id: "clinic-4a-f0", name: "Clinic 4a", type: "department", coordinates: { lat: 52.499674, lng: 0.055734 }, floor: 0 },
    { id: "clinic-12-f0", name: "Clinic 12", type: "department", coordinates: { lat: 52.499675, lng: 0.05509 }, floor: 0 },
    { id: "a3-war-f0", name: "A3 war", type: "other", coordinates: { lat: 52.499635, lng: 0.05672 }, floor: 0 },
    { id: "radiology-day-f0", name: "Radiology day", type: "department", coordinates: { lat: 52.499596, lng: 0.056213 }, floor: 0 },
    { id: "speech-therapy-f0", name: "Speech therapy", type: "department", coordinates: { lat: 52.499586, lng: 0.054692 }, floor: 0 },
    { id: "fluoroscopy-f0", name: "Fluoroscopy", type: "other", coordinates: { lat: 52.499472, lng: 0.05608 }, floor: 0 },
    { id: "pai-f0", name: "Pai", type: "other", coordinates: { lat: 52.499254, lng: 0.053855 }, floor: 0 },
    { id: "medical-photography-f0", name: "Medical photography", type: "other", coordinates: { lat: 52.499174, lng: 0.053904 }, floor: 0 },
  ],
}
