import { Venue } from "../types"

// Lincoln County Hospital — reconstructed from the trust's own map sheet
// (map/auto/lincoln-hospital-map-level-3.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const LINCOLN_HOSPITAL_MAP_LEVEL_3_VENUE: Venue = {
  id: "lincoln-hospital-map-level-3-venue",
  slug: "lincoln-hospital-map-level-3",
  name: "Lincoln County Hospital",
  subtitle: "United Lincolnshire Teaching Hospitals NHS Trust · LN2 5QY",
  category: "hospital",
  center: { lat: 53.233597, lng: -0.519635 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by United Lincolnshire Teaching Hospitals NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale estimated) and has not been checked by eye." },
  quickAccess: ["Blood Tests", "Toilet Stairs Lift", "Macmilan", "Shop Cafe", "Dermatology"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/lincoln-hospital-map-level-3/sitemap.svg", bounds: [[53.232165, -0.523012], [53.235029, -0.516258]] },
  ],
  waypoints: [
    { id: "blood-tests-f0", name: "Blood Tests", type: "other", coordinates: { lat: 53.233916, lng: -0.518981 }, floor: 0 },
    { id: "toilet-stairs-lift-f0", name: "Toilet Stairs Lift", type: "toilet", coordinates: { lat: 53.233714, lng: -0.519146 }, floor: 0 },
    { id: "macmilan-f0", name: "Macmilan", type: "other", coordinates: { lat: 53.233741, lng: -0.518776 }, floor: 0 },
    { id: "shop-cafe-f0", name: "Shop Cafe", type: "canteen", coordinates: { lat: 53.233708, lng: -0.519022 }, floor: 0 },
    { id: "dermatology-f0", name: "Dermatology", type: "other", coordinates: { lat: 53.233537, lng: -0.518873 }, floor: 0 },
    { id: "pharmacy-f0", name: "Pharmacy", type: "pharmacy", coordinates: { lat: 53.233438, lng: -0.518744 }, floor: 0 },
    { id: "toilets-f0", name: "Toilets", type: "toilet", coordinates: { lat: 53.233368, lng: -0.519666 }, floor: 0 },
    { id: "nuclear-medicine-f0", name: "Nuclear Medicine", type: "department", coordinates: { lat: 53.233349, lng: -0.518534 }, floor: 0 },
    { id: "medical-day-unit-f0", name: "Medical Day Unit", type: "department", coordinates: { lat: 53.232848, lng: -0.517705 }, floor: 0 },
    { id: "toilet-f0", name: "Toilet", type: "toilet", coordinates: { lat: 53.232755, lng: -0.517775 }, floor: 0 },
    { id: "stairs-f0", name: "Stairs", type: "stairs", coordinates: { lat: 53.232735, lng: -0.517639 }, floor: 0 },
    { id: "lifts-f0", name: "Lifts", type: "lift", coordinates: { lat: 53.232667, lng: -0.517641 }, floor: 0 },
    { id: "county-restaurant-f0", name: "County Restaurant", type: "canteen", coordinates: { lat: 53.232523, lng: -0.517577 }, floor: 0 },
  ],
}
