import { Venue } from "../types"

// Lincoln County Hospital — reconstructed from the trust's own map sheet
// (map/auto/lincoln-hospital-map-level-1.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const LINCOLN_HOSPITAL_MAP_LEVEL_1_VENUE: Venue = {
  id: "lincoln-hospital-map-level-1-venue",
  slug: "lincoln-hospital-map-level-1",
  name: "Lincoln County Hospital",
  subtitle: "United Lincolnshire Teaching Hospitals NHS Trust · LN2 5QY",
  category: "hospital",
  center: { lat: 53.233597, lng: -0.519635 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by United Lincolnshire Teaching Hospitals NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale estimated) and has not been checked by eye." },
  quickAccess: ["Lincoln County Hospital", "Burton Ward", "Cardiac short stay", "Carlton Coleby Ward", "Digby Ward"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/lincoln-hospital-map-level-1/sitemap.svg", bounds: [[53.232165, -0.523012], [53.235029, -0.516258]] },
  ],
  waypoints: [
    { id: "lincoln-county-hospital-f0", name: "Lincoln County Hospital", type: "department", coordinates: { lat: 53.23487, lng: -0.517053 }, floor: 0 },
    { id: "burton-ward-f0", name: "Burton Ward", type: "ward", coordinates: { lat: 53.234549, lng: -0.517269 }, floor: 0 },
    { id: "cardiac-short-stay-f0", name: "Cardiac short stay", type: "other", coordinates: { lat: 53.234503, lng: -0.517211 }, floor: 0 },
    { id: "carlton-coleby-ward-f0", name: "Carlton Coleby Ward", type: "ward", coordinates: { lat: 53.234458, lng: -0.517177 }, floor: 0 },
    { id: "digby-ward-f0", name: "Digby Ward", type: "ward", coordinates: { lat: 53.234413, lng: -0.517281 }, floor: 0 },
    { id: "discharge-lounge-f0", name: "Discharge Lounge", type: "department", coordinates: { lat: 53.234367, lng: -0.517211 }, floor: 0 },
    { id: "dixon-ward-f0", name: "Dixon Ward", type: "ward", coordinates: { lat: 53.234322, lng: -0.517281 }, floor: 0 },
    { id: "endoscopy-unit-f0", name: "Endoscopy Unit", type: "department", coordinates: { lat: 53.234276, lng: -0.517238 }, floor: 0 },
    { id: "johnson-ward-f0", name: "Johnson Ward", type: "ward", coordinates: { lat: 53.234231, lng: -0.517253 }, floor: 0 },
    { id: "access-via-level-2-f0", name: "Access via Level 2", type: "other", coordinates: { lat: 53.234193, lng: -0.522262 }, floor: 0 },
    { id: "lancaster-ward-f0", name: "Lancaster Ward", type: "ward", coordinates: { lat: 53.234185, lng: -0.517239 }, floor: 0 },
    { id: "medical-emergency-admissions-unit-f0", name: "Medical Emergency Admissions Unit", type: "department", coordinates: { lat: 53.23414, lng: -0.516997 }, floor: 0 },
    { id: "navenby-ward-f0", name: "Navenby Ward", type: "ward", coordinates: { lat: 53.234094, lng: -0.517247 }, floor: 0 },
    { id: "oncology-radiotherapy-f0", name: "Oncology/Radiotherapy", type: "department", coordinates: { lat: 53.234049, lng: -0.517143 }, floor: 0 },
    { id: "peter-hodgkinson-centre-f0", name: "Peter Hodgkinson Centre", type: "department", coordinates: { lat: 53.234003, lng: -0.517127 }, floor: 0 },
    { id: "rainforest-ward-f0", name: "Rainforest Ward", type: "ward", coordinates: { lat: 53.233957, lng: -0.522145 }, floor: 0 },
    { id: "to-car-parks-f0", name: "To car parks", type: "other", coordinates: { lat: 53.233957, lng: -0.518453 }, floor: 0 },
    { id: "renal-unit-f0", name: "Renal Unit", type: "department", coordinates: { lat: 53.233913, lng: -0.517299 }, floor: 0 },
    { id: "resus-training-f0", name: "Resus training", type: "other", coordinates: { lat: 53.23387, lng: -0.520448 }, floor: 0 },
    { id: "respiratory-support-unit-f0", name: "Respiratory Support Unit", type: "department", coordinates: { lat: 53.233867, lng: -0.517128 }, floor: 0 },
    { id: "stroke-unit-f0", name: "Stroke Unit", type: "department", coordinates: { lat: 53.233822, lng: -0.517289 }, floor: 0 },
    { id: "witham-ward-f0", name: "Witham Ward", type: "ward", coordinates: { lat: 53.233776, lng: -0.517257 }, floor: 0 },
    { id: "oncology-radiotherapy-f0-2", name: "Oncology/ Radiotherapy", type: "department", coordinates: { lat: 53.23374, lng: -0.51881 }, floor: 0 },
    { id: "ingham-suite-f0", name: "Ingham Suite", type: "department", coordinates: { lat: 53.233604, lng: -0.518523 }, floor: 0 },
    { id: "stairs-f0", name: "Stairs", type: "stairs", coordinates: { lat: 53.233587, lng: -0.519392 }, floor: 0 },
    { id: "lifts-f0", name: "Lifts", type: "lift", coordinates: { lat: 53.233485, lng: -0.519314 }, floor: 0 },
  ],
}
