import { Venue } from "../types"

// The Maidstone Hospital - General Surgery — reconstructed from the trust's own map sheet
// (map/auto/maidstone-hospital-mappdf.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const MAIDSTONE_HOSPITAL_MAPPDF_VENUE: Venue = {
  id: "maidstone-hospital-mappdf-venue",
  slug: "maidstone-hospital-mappdf",
  name: "The Maidstone Hospital - General Surgery",
  subtitle: "Maidstone and Tunbridge Wells NHS Trust · ME16 9QQ",
  category: "hospital",
  center: { lat: 51.273661, lng: 0.484004 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Maidstone and Tunbridge Wells NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale estimated) and has not been checked by eye." },
  quickAccess: ["Main Entrance and Reception", "Accident & Emergency", "Welcome to Maidstone Hospital", "Staff", "Kent & Medway Orthopaedic Centre"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/maidstone-hospital-mappdf/sitemap.svg", bounds: [[51.272232, 0.480773], [51.27509, 0.487235]] },
  ],
  waypoints: [
    { id: "welcome-to-maidstone-hospital-f0", name: "Welcome to Maidstone Hospital", type: "department", coordinates: { lat: 51.27466, lng: 0.485116 }, floor: 0 },
    { id: "staff-f0", name: "Staff", type: "other", coordinates: { lat: 51.274222, lng: 0.485133 }, floor: 0 },
    { id: "kent-medway-orthopaedic-centre-f0", name: "Kent & Medway Orthopaedic Centre", type: "department", coordinates: { lat: 51.274057, lng: 0.484935 }, floor: 0 },
    { id: "rear-entrance-f0", name: "Rear Entrance", type: "exit", coordinates: { lat: 51.27401, lng: 0.485477 }, floor: 0 },
    { id: "renal-unit-f0", name: "Renal Unit", type: "department", coordinates: { lat: 51.273995, lng: 0.48414 }, floor: 0 },
    { id: "oncology-entrance-f0", name: "Oncology Entrance", type: "exit", coordinates: { lat: 51.273944, lng: 0.481701 }, floor: 0 },
    { id: "stairs-to-cardiac-catheter-lab-f0", name: "Stairs to Cardiac Catheter Lab", type: "other", coordinates: { lat: 51.273724, lng: 0.484501 }, floor: 0 },
    { id: "electric-vehicle-charging-point-f0", name: "Electric Vehicle Charging Point", type: "other", coordinates: { lat: 51.273673, lng: 0.483766 }, floor: 0 },
    { id: "cardiac-f0", name: "Cardiac", type: "other", coordinates: { lat: 51.273589, lng: 0.484477 }, floor: 0 },
    { id: "retail-area-f0", name: "Retail Area", type: "other", coordinates: { lat: 51.273421, lng: 0.486181 }, floor: 0 },
    { id: "academic-centre-f0", name: "Academic Centre", type: "department", coordinates: { lat: 51.273352, lng: 0.48131 }, floor: 0 },
    { id: "acute-assessment-unit-acute-stroke-unit-f0", name: "Acute Assessment Unit Acute Stroke Unit", type: "department", coordinates: { lat: 51.273271, lng: 0.481335 }, floor: 0 },
    { id: "main-entrance-and-reception-f0", name: "Main Entrance and Reception", type: "exit", coordinates: { lat: 51.273078, lng: 0.486173 }, floor: 0 },
    { id: "oncology-outpatients-unit-f0", name: "Oncology Outpatients Unit", type: "department", coordinates: { lat: 51.27283, lng: 0.482122 }, floor: 0 },
    { id: "accident-emergency-f0", name: "Accident & Emergency", type: "other", coordinates: { lat: 51.272825, lng: 0.485345 }, floor: 0 },
    { id: "diabetes-unit-paula-carr-centre-f0", name: "Diabetes Unit (Paula Carr Centre)", type: "department", coordinates: { lat: 51.272634, lng: 0.481415 }, floor: 0 },
    { id: "patient-advice-liaision-pals-f0", name: "Patient Advice & Liaision (PALS)", type: "other", coordinates: { lat: 51.272634, lng: 0.482142 }, floor: 0 },
    { id: "dietetics-f0", name: "Dietetics", type: "other", coordinates: { lat: 51.272601, lng: 0.481245 }, floor: 0 },
    { id: "eemu-ear-eye-mouth-unit-f0", name: "EEMU (Ear, Eye & Mouth Unit)", type: "department", coordinates: { lat: 51.272536, lng: 0.481401 }, floor: 0 },
    { id: "main-site-entrance-f0", name: "Main Site Entrance", type: "exit", coordinates: { lat: 51.272451, lng: 0.485987 }, floor: 0 },
  ],
}
