import { Venue } from "../types"

// Mile End Hospital — Barts Health NHS Trust. The floor plan is the trust's
// numbered-block site plan (from its cycle-parking sheet); each block's
// 'Building Contents' entry is a waypoint at the block's marker. Demolished
// or removed blocks (10, 26, 28) are omitted. Cycle-parking positions are
// approximate to the sheet's photo arrows.
// Generated by scripts/sheets/generate-batch2.py — edit that, not this.

export const MEH_VENUE: Venue = {
  id: "mile-end-hospital",
  slug: "mile-end-hospital",
  name: "Mile End Hospital",
  subtitle: "Barts Health NHS Trust · Bancroft Road, London E1 4DG",
  category: "hospital",
  center: { lat: 51.525047, lng: -0.042192 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Level site with marked pedestrian routes between blocks." },
  quickAccess: ["X-Ray / Theatres / Pharmacy", "Restaurant", "Therapy Unit", "Robinson Ward / Sports Medicine / PALS"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/meh/sitemap.png", bounds: [[51.52343, -0.044524], [51.526664, -0.03986]] },
  ],
  waypoints: [
    // ── Buildings ─────────────────────────────────────────────────────────
    { id: "thpct-headquarters-f0", name: "THPCT Headquarters", type: "other", coordinates: { lat: 51.524199, lng: -0.043569 }, floor: 0, description: "Block 1" },
    { id: "primary-care-building-f0", name: "Primary Care Building", type: "department", coordinates: { lat: 51.523918, lng: -0.043167 }, floor: 0, description: "Block 2" },
    { id: "emily-graham-building-f0", name: "Emily Graham Building", type: "department", coordinates: { lat: 51.524024, lng: -0.042765 }, floor: 0, description: "Block 3" },
    { id: "alderney-building-f0", name: "Alderney Building", type: "department", coordinates: { lat: 51.524437, lng: -0.043217 }, floor: 0, description: "Block 4" },
    { id: "bancroft-unit-f0", name: "Bancroft Unit", type: "department", coordinates: { lat: 51.525357, lng: -0.043871 }, floor: 0, description: "Block 5" },
    { id: "beaumont-house-sau-f0", name: "Beaumont House (SAU)", type: "other", coordinates: { lat: 51.523937, lng: -0.042413 }, floor: 0, description: "Block 6" },
    { id: "x-ray-theatres-pharmacy-f0", name: "X-Ray / Theatres / Pharmacy", type: "pharmacy", coordinates: { lat: 51.524819, lng: -0.042996 }, floor: 0, description: "Block 7" },
    { id: "rht-rheumatology-moorfields-eye-clinic-foot-health-well-women-f0", name: "RHT Rheumatology / Moorfields Eye Clinic / Foot Health / Well Women", type: "department", coordinates: { lat: 51.524562, lng: -0.042443 }, floor: 0, description: "Block 8" },
    { id: "hospital-generator-building-f0", name: "Hospital Generator Building", type: "department", coordinates: { lat: 51.524331, lng: -0.04176 }, floor: 0, description: "Block 9" },
    { id: "boiler-house-estates-workshops-f0", name: "Boiler House & Estates Workshops", type: "other", coordinates: { lat: 51.524625, lng: -0.041508 }, floor: 0, description: "Block 11" },
    { id: "the-wheelchair-centre-f0", name: "The Wheelchair Centre", type: "department", coordinates: { lat: 51.525, lng: -0.040855 }, floor: 0, description: "Block 12" },
    { id: "burdett-house-f0", name: "Burdett House", type: "other", coordinates: { lat: 51.525657, lng: -0.041066 }, floor: 0, description: "Block 13" },
    { id: "restaurant-f0", name: "Restaurant", type: "canteen", coordinates: { lat: 51.52602, lng: -0.041599 }, floor: 0, description: "Block 14" },
    { id: "therapy-unit-f0", name: "Therapy Unit", type: "department", coordinates: { lat: 51.526126, lng: -0.041991 }, floor: 0, description: "Block 15" },
    { id: "hydrotherapy-pool-f0", name: "Hydrotherapy Pool", type: "department", coordinates: { lat: 51.52622, lng: -0.042393 }, floor: 0, description: "Block 16" },
    { id: "mortuary-f0", name: "Mortuary", type: "other", coordinates: { lat: 51.52607, lng: -0.042705 }, floor: 0, description: "Block 17" },
    { id: "laundry-building-f0", name: "Laundry Building", type: "department", coordinates: { lat: 51.525719, lng: -0.043418 }, floor: 0, description: "Block 18" },
    { id: "physiotherapy-hastings-ward-public-health-improvement-f0", name: "Physiotherapy / Hastings Ward / Public Health & Improvement", type: "ward", coordinates: { lat: 51.525863, lng: -0.042413 }, floor: 0, description: "Block 19" },
    { id: "mhu-leadenhall-roman-ward-f0", name: "MHU — Leadenhall / Roman Ward", type: "ward", coordinates: { lat: 51.525582, lng: -0.041699 }, floor: 0, description: "Block 20" },
    { id: "catering-department-social-services-chapel-community-diabetics-f0", name: "Catering Department / Social Services / Chapel / Community Diabetics", type: "department", coordinates: { lat: 51.525701, lng: -0.042795 }, floor: 0, description: "Block 21" },
    { id: "mhu-globe-brick-lane-ward-f0", name: "MHU — Globe / Brick Lane Ward", type: "ward", coordinates: { lat: 51.525601, lng: -0.042102 }, floor: 0, description: "Block 22" },
    { id: "robinson-ward-sports-medicine-pals-f0", name: "Robinson Ward / Sports Medicine / PALS", type: "ward", coordinates: { lat: 51.525488, lng: -0.043087 }, floor: 0, description: "Block 23" },
    { id: "mhu-rosebank-millharbour-lea-ward-f0", name: "MHU — Rosebank / Millharbour / Lea Ward", type: "ward", coordinates: { lat: 51.525163, lng: -0.042514 }, floor: 0, description: "Block 24" },
    { id: "bancroft-generator-building-f0", name: "Bancroft Generator Building", type: "department", coordinates: { lat: 51.524556, lng: -0.044172 }, floor: 0, description: "Block 25" },
    { id: "main-corridor-f0", name: "Main Corridor", type: "other", coordinates: { lat: 51.525244, lng: -0.042865 }, floor: 0, description: "Block 27" },
    { id: "gsl-clinical-equipment-dietitian-f0", name: "GSL / Clinical Equipment / Dietitian", type: "department", coordinates: { lat: 51.525863, lng: -0.041991 }, floor: 0, description: "Block 29" },
    // ── Cycle parking ─────────────────────────────────────────────────────
    { id: "cycle-parking-20-spaces-f0", name: "Cycle parking (20 spaces)", type: "other", coordinates: { lat: 51.525131, lng: -0.041961 }, floor: 0 },
    { id: "cycle-parking-14-spaces-f0", name: "Cycle parking (14 spaces)", type: "other", coordinates: { lat: 51.525507, lng: -0.041358 }, floor: 0 },
    { id: "cycle-parking-10-spaces-f0", name: "Cycle parking (10 spaces)", type: "other", coordinates: { lat: 51.525006, lng: -0.040956 }, floor: 0 },
    { id: "cycle-parking-14-spaces-f0-2", name: "Cycle parking (14 spaces)", type: "other", coordinates: { lat: 51.525663, lng: -0.040855 }, floor: 0 },
    { id: "cycle-parking-6-spaces-f0", name: "Cycle parking (6 spaces)", type: "other", coordinates: { lat: 51.524381, lng: -0.04171 }, floor: 0 },
    { id: "cycle-parking-10-spaces-f0-2", name: "Cycle parking (10 spaces)", type: "other", coordinates: { lat: 51.52388, lng: -0.042514 }, floor: 0 },
    { id: "cycle-parking-4-spaces-f0", name: "Cycle parking (4 spaces)", type: "other", coordinates: { lat: 51.523849, lng: -0.043016 }, floor: 0 },
    { id: "cycle-parking-4-spaces-f0-2", name: "Cycle parking (4 spaces)", type: "other", coordinates: { lat: 51.524162, lng: -0.042664 }, floor: 0 },
    { id: "cycle-parking-8-spaces-f0", name: "Cycle parking (8 spaces)", type: "other", coordinates: { lat: 51.524318, lng: -0.04367 }, floor: 0 },
    { id: "cycle-parking-6-spaces-f0-2", name: "Cycle parking (6 spaces)", type: "other", coordinates: { lat: 51.524099, lng: -0.043418 }, floor: 0 },
  ],
}
