import { Venue } from "../types"

// North Manchester General Hospital — reconstructed from the trust's own site map sheet
// (map/NMGHMap_Flat_UpdateDec2023_External-VB-Block-Naviagation-V2_.pdf). Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const NMGH_VENUE: Venue = {
  id: "north-manchester-general-hospital",
  slug: "nmgh",
  name: "North Manchester General Hospital",
  subtitle: "Manchester University NHS FT · Delaunays Road, Crumpsall, Manchester M8 5RB",
  category: "hospital",
  center: { lat: 53.517887, lng: -2.229487 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map with lettered blocks A–J, colour-coded car parks and pedestrian/emergency entrances. Nearest Metrolink at Crumpsall." },
  quickAccess: ["Main Entrance", "Emergency Department (A&E)", "North Manchester General Hospital", "MRI Scanner"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/nmgh/sitemap.svg", bounds: [[53.516075, -2.235014], [53.520014, -2.225646]] },
  ],
  waypoints: [
    { id: "post-grad-f0", name: "Post-Grad", type: "other", coordinates: { lat: 53.519017, lng: -2.229995 }, floor: 0 },
    { id: "medical-centre-f0", name: "Medical Centre", type: "department", coordinates: { lat: 53.518976, lng: -2.229977 }, floor: 0 },
    { id: "main-entrance-f0", name: "Main Entrance", type: "exit", coordinates: { lat: 53.518893, lng: -2.228931 }, floor: 0 },
    { id: "volunteer-services-f0", name: "Volunteer Services", type: "other", coordinates: { lat: 53.518794, lng: -2.230389 }, floor: 0 },
    { id: "emergency-department-a-e-f0", name: "Emergency Department (A&E)", type: "department", coordinates: { lat: 53.51858, lng: -2.229698 }, floor: 0 },
    { id: "mri-scanning-f0", name: "MRI Scanning", type: "other", coordinates: { lat: 53.518344, lng: -2.230056 }, floor: 0 },
    { id: "parkhouse-f0", name: "Parkhouse", type: "department", coordinates: { lat: 53.518296, lng: -2.231865 }, floor: 0 },
    { id: "crumpsall-vale-medical-f0", name: "Crumpsall Vale Medical", type: "other", coordinates: { lat: 53.518227, lng: -2.226306 }, floor: 0 },
    { id: "estates-facilities-f0", name: "Estates & Facilities", type: "other", coordinates: { lat: 53.518025, lng: -2.232665 }, floor: 0 },
    { id: "central-stores-f0", name: "Central Stores", type: "other", coordinates: { lat: 53.517743, lng: -2.232928 }, floor: 0 },
    { id: "north-manchester-house-f0", name: "North Manchester House", type: "department", coordinates: { lat: 53.517541, lng: -2.232794 }, floor: 0 },
    { id: "diabetes-endocrinology-antenatal-clinic-f0", name: "Diabetes / Endocrinology & Antenatal Clinic", type: "department", coordinates: { lat: 53.517431, lng: -2.227402 }, floor: 0 },
    { id: "limbert-multi-storey-car-park-f0", name: "Limbert Multi-Storey Car Park", type: "other", coordinates: { lat: 53.51701, lng: -2.228304 }, floor: 0 },
    { id: "lilac-centre-f0", name: "Lilac Centre", type: "department", coordinates: { lat: 53.516625, lng: -2.230039 }, floor: 0 },
  ],
}
