import { Venue } from "../types"

// Northwick Park Hospital — reconstructed from the trust's own map sheet
// (map/auto/northwick-park-hospital-site-map.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const NORTHWICK_PARK_HOSPITAL_SITE_MAP_VENUE: Venue = {
  id: "northwick-park-hospital-site-map-venue",
  slug: "northwick-park-hospital-site-map",
  name: "Northwick Park Hospital",
  subtitle: "London North West University Healthcare NHS Trust · HA1 3UJ",
  category: "hospital",
  center: { lat: 51.575409, lng: -0.322015 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by London North West University Healthcare NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["Departments", "Blood Test Clinic - Phlebotomy", "Endoscopy Florence Ward", "Haematology Day Care & Assessment Chemotherapy", "Hydrotherapy Levi Lecture Theatre Lung Function Lab"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/northwick-park-hospital-site-map/sitemap.svg", bounds: [[51.573337, -0.326402], [51.577481, -0.317628]] },
  ],
  waypoints: [
    { id: "departments-f0", name: "Departments", type: "department", coordinates: { lat: 51.577355, lng: -0.326087 }, floor: 0 },
    { id: "blood-test-clinic-phlebotomy-f0", name: "Blood Test Clinic - Phlebotomy", type: "department", coordinates: { lat: 51.57701, lng: -0.325943 }, floor: 0 },
    { id: "endoscopy-florence-ward-f0", name: "Endoscopy Florence Ward", type: "ward", coordinates: { lat: 51.576365, lng: -0.326153 }, floor: 0 },
    { id: "haematology-day-care-assessment-chemotherapy-f0", name: "Haematology Day Care & Assessment Chemotherapy", type: "department", coordinates: { lat: 51.576198, lng: -0.325672 }, floor: 0 },
    { id: "hydrotherapy-levi-lecture-theatre-lung-function-lab-f0", name: "Hydrotherapy Levi Lecture Theatre Lung Function Lab", type: "department", coordinates: { lat: 51.576102, lng: -0.326097 }, floor: 0 },
    { id: "orthotics-f0", name: "Orthotics", type: "other", coordinates: { lat: 51.575624, lng: -0.326193 }, floor: 0 },
    { id: "patient-advice-liaison-service-pals-f0", name: "Patient Advice & Liaison Service (PALS)", type: "other", coordinates: { lat: 51.575577, lng: -0.325849 }, floor: 0 },
    { id: "surgical-intensive-recovery-unit-siru-f0", name: "Surgical Intensive Recovery Unit (SIRU)", type: "department", coordinates: { lat: 51.575147, lng: -0.32585 }, floor: 0 },
    { id: "x-ray-f0", name: "X-ray", type: "department", coordinates: { lat: 51.57486, lng: -0.32624 }, floor: 0 },
    { id: "wards-f0", name: "Wards", type: "ward", coordinates: { lat: 51.574769, lng: -0.326205 }, floor: 0 },
    { id: "ward-f0", name: "Ward", type: "ward", coordinates: { lat: 51.574711, lng: -0.326232 }, floor: 0 },
    { id: "carroll-assessment-unit-ed-observation-unit-f0", name: "Carroll Assessment Unit & ED Observation Unit", type: "department", coordinates: { lat: 51.574663, lng: -0.325747 }, floor: 0 },
    { id: "ccu-coronary-care-unit-jenner-f0", name: "CCU - Coronary Care Unit - Jenner", type: "department", coordinates: { lat: 51.574615, lng: -0.325889 }, floor: 0 },
    { id: "chaucer-f0", name: "Chaucer", type: "other", coordinates: { lat: 51.574567, lng: -0.326203 }, floor: 0 },
    { id: "crick-darwin-dickens-older-persons-short-stay-unit-f0", name: "Crick Darwin Dickens - Older Persons Short Stay Unit", type: "department", coordinates: { lat: 51.57452, lng: -0.325676 }, floor: 0 },
    { id: "dryden-f0", name: "Dryden", type: "other", coordinates: { lat: 51.574472, lng: -0.326217 }, floor: 0 },
    { id: "hardy-herrrick-f0", name: "Hardy Herrrick", type: "other", coordinates: { lat: 51.573922, lng: -0.326221 }, floor: 0 },
    { id: "hyper-acute-regional-rehabilitation-unit-f0", name: "Hyper Acute Regional Rehabilitation Unit", type: "department", coordinates: { lat: 51.573851, lng: -0.325817 }, floor: 0 },
    { id: "jonson-intestinal-failure-unit-ifu-f0", name: "Jonson - Intestinal Failure Unit IFU", type: "department", coordinates: { lat: 51.57366, lng: -0.325901 }, floor: 0 },
    { id: "lister-unit-f0", name: "Lister Unit", type: "department", coordinates: { lat: 51.573612, lng: -0.326183 }, floor: 0 },
    { id: "renal-dialysis-centre-f0", name: "Renal & Dialysis Centre", type: "department", coordinates: { lat: 51.573564, lng: -0.32603 }, floor: 0 },
    { id: "trust-plus-sainsbury-f0", name: "Trust Plus - Sainsbury", type: "other", coordinates: { lat: 51.573469, lng: -0.326054 }, floor: 0 },
  ],
}
