import { Venue } from "../types"

// Princess Anne Hospital — reconstructed from the trust's own map sheet
// (map/auto/pah-d-level-floor-plan.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const PAH_D_LEVEL_FLOOR_PLAN_VENUE: Venue = {
  id: "pah-d-level-floor-plan-venue",
  slug: "pah-d-level-floor-plan",
  name: "Princess Anne Hospital",
  subtitle: "Solent NHS Trust · SO16 5YA",
  category: "hospital",
  center: { lat: 50.935249, lng: -1.434855 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Solent NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["University Hospital Southampton", "STAIRWELL", "LIFT", "FEMALE WC", "UNISEX WC"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/pah-d-level-floor-plan/sitemap.svg", bounds: [[50.934217, -1.437171], [50.936281, -1.432539]] },
  ],
  waypoints: [
    { id: "university-hospital-southampton-f0", name: "University Hospital Southampton", type: "department", coordinates: { lat: 50.936229, lng: -1.433193 }, floor: 0 },
    { id: "stairwell-f0", name: "STAIRWELL", type: "other", coordinates: { lat: 50.936102, lng: -1.436816 }, floor: 0 },
    { id: "lift-f0", name: "LIFT", type: "lift", coordinates: { lat: 50.936027, lng: -1.436885 }, floor: 0 },
    { id: "female-wc-f0", name: "FEMALE WC", type: "toilet", coordinates: { lat: 50.935943, lng: -1.436812 }, floor: 0 },
    { id: "unisex-wc-f0", name: "UNISEX WC", type: "toilet", coordinates: { lat: 50.935866, lng: -1.436817 }, floor: 0 },
    { id: "accessible-wc-f0", name: "ACCESSIBLE WC", type: "toilet", coordinates: { lat: 50.935802, lng: -1.436766 }, floor: 0 },
    { id: "right-handed-transfer-f0", name: "(RIGHT HANDED TRANSFER)", type: "other", coordinates: { lat: 50.935776, lng: -1.43666 }, floor: 0 },
    { id: "accessible-wc-left-handed-transfer-f0", name: "ACCESSIBLE WC (LEFT HANDED TRANSFER)", type: "toilet", coordinates: { lat: 50.935717, lng: -1.436719 }, floor: 0 },
    { id: "day-surgery-unit-f0", name: "Day Surgery Unit", type: "department", coordinates: { lat: 50.935679, lng: -1.434834 }, floor: 0 },
    { id: "main-information-desk-f0", name: "MAIN INFORMATION DESK", type: "reception", coordinates: { lat: 50.935643, lng: -1.436683 }, floor: 0 },
    { id: "neonatal-unit-f0", name: "Neonatal Unit", type: "department", coordinates: { lat: 50.935576, lng: -1.435783 }, floor: 0 },
    { id: "baby-changing-room-f0", name: "BABY CHANGING ROOM", type: "other", coordinates: { lat: 50.935564, lng: -1.436702 }, floor: 0 },
    { id: "theatres-f0", name: "Theatres", type: "department", coordinates: { lat: 50.935516, lng: -1.434328 }, floor: 0 },
    { id: "refreshments-f0", name: "REFRESHMENTS", type: "other", coordinates: { lat: 50.935472, lng: -1.436768 }, floor: 0 },
    { id: "security-f0", name: "SECURITY", type: "other", coordinates: { lat: 50.935391, lng: -1.436827 }, floor: 0 },
    { id: "labour-ward-f0", name: "Labour Ward", type: "ward", coordinates: { lat: 50.934917, lng: -1.434016 }, floor: 0 },
    { id: "early-pregnancy-gynae-ward-f0", name: "Early Pregnancy & Gynae Ward", type: "ward", coordinates: { lat: 50.934787, lng: -1.434637 }, floor: 0 },
  ],
}
