import { Venue } from "../types"

// Princess Anne Hospital — reconstructed from the trust's own map sheet
// (map/auto/pah-e-level-floor-plan.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const PAH_E_LEVEL_FLOOR_PLAN_VENUE: Venue = {
  id: "pah-e-level-floor-plan-venue",
  slug: "pah-e-level-floor-plan",
  name: "Princess Anne Hospital",
  subtitle: "Solent NHS Trust · SO16 5YA",
  category: "hospital",
  center: { lat: 50.935249, lng: -1.434855 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Solent NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["Outpatients", "University Hospital Southampton", "STAIRWELL", "Broadlands Birth Centre", "LIFT"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/pah-e-level-floor-plan/sitemap.svg", bounds: [[50.934217, -1.437171], [50.936281, -1.432539]] },
  ],
  waypoints: [
    { id: "university-hospital-southampton-f0", name: "University Hospital Southampton", type: "department", coordinates: { lat: 50.936245, lng: -1.433166 }, floor: 0 },
    { id: "stairwell-f0", name: "STAIRWELL", type: "other", coordinates: { lat: 50.935974, lng: -1.436639 }, floor: 0 },
    { id: "broadlands-birth-centre-f0", name: "Broadlands Birth Centre", type: "department", coordinates: { lat: 50.935945, lng: -1.434504 }, floor: 0 },
    { id: "lift-f0", name: "LIFT", type: "lift", coordinates: { lat: 50.935898, lng: -1.436709 }, floor: 0 },
    { id: "male-wc-f0", name: "MALE WC", type: "toilet", coordinates: { lat: 50.935819, lng: -1.436659 }, floor: 0 },
    { id: "female-wc-f0", name: "FEMALE WC", type: "toilet", coordinates: { lat: 50.935742, lng: -1.436635 }, floor: 0 },
    { id: "unisex-wc-f0", name: "UNISEX WC", type: "toilet", coordinates: { lat: 50.935663, lng: -1.43664 }, floor: 0 },
    { id: "accessible-wc-f0", name: "ACCESSIBLE WC", type: "toilet", coordinates: { lat: 50.935599, lng: -1.436588 }, floor: 0 },
    { id: "right-handed-transfer-f0", name: "(RIGHT HANDED TRANSFER)", type: "other", coordinates: { lat: 50.935572, lng: -1.436481 }, floor: 0 },
    { id: "breast-feeding-unit-f0", name: "Breast feeding Unit", type: "department", coordinates: { lat: 50.935499, lng: -1.434519 }, floor: 0 },
    { id: "main-information-desk-f0", name: "MAIN INFORMATION DESK", type: "reception", coordinates: { lat: 50.935506, lng: -1.436504 }, floor: 0 },
    { id: "restaurant-f0", name: "RESTAURANT", type: "canteen", coordinates: { lat: 50.935434, lng: -1.436619 }, floor: 0 },
    { id: "public-telephone-f0", name: "PUBLIC TELEPHONE", type: "other", coordinates: { lat: 50.935356, lng: -1.436558 }, floor: 0 },
    { id: "breast-imaging-f0", name: "Breast Imaging", type: "department", coordinates: { lat: 50.935205, lng: -1.434621 }, floor: 0 },
    { id: "fetal-medicine-f0", name: "Fetal Medicine", type: "department", coordinates: { lat: 50.935064, lng: -1.434118 }, floor: 0 },
    { id: "ultra-sound-f0", name: "Ultra sound", type: "other", coordinates: { lat: 50.934758, lng: -1.434133 }, floor: 0 },
    { id: "outpatients-f0", name: "Outpatients", type: "department", coordinates: { lat: 50.934566, lng: -1.434994 }, floor: 0 },
  ],
}
