import { Venue } from "../types"

// Princess Anne Hospital — reconstructed from the trust's own map sheet
// (map/auto/pah-g-level-floor-plan.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const PAH_G_LEVEL_FLOOR_PLAN_VENUE: Venue = {
  id: "pah-g-level-floor-plan-venue",
  slug: "pah-g-level-floor-plan",
  name: "Princess Anne Hospital",
  subtitle: "Solent NHS Trust · SO16 5YA",
  category: "hospital",
  center: { lat: 50.935249, lng: -1.434855 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Solent NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["University Hospital Southampton", "LIFT", "STAIRWELL", "MALE WC", "FEMALE WC"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/pah-g-level-floor-plan/sitemap.svg", bounds: [[50.934217, -1.437171], [50.936281, -1.432539]] },
  ],
  waypoints: [
    { id: "university-hospital-southampton-f0", name: "University Hospital Southampton", type: "department", coordinates: { lat: 50.936243, lng: -1.433166 }, floor: 0 },
    { id: "lift-f0", name: "LIFT", type: "lift", coordinates: { lat: 50.93574, lng: -1.436871 }, floor: 0 },
    { id: "stairwell-f0", name: "STAIRWELL", type: "other", coordinates: { lat: 50.935664, lng: -1.436801 }, floor: 0 },
    { id: "male-wc-f0", name: "MALE WC", type: "toilet", coordinates: { lat: 50.935586, lng: -1.436821 }, floor: 0 },
    { id: "female-wc-f0", name: "FEMALE WC", type: "toilet", coordinates: { lat: 50.935509, lng: -1.436797 }, floor: 0 },
    { id: "unisex-wc-f0", name: "UNISEX WC", type: "toilet", coordinates: { lat: 50.93543, lng: -1.436802 }, floor: 0 },
    { id: "complete-fertility-f0", name: "Complete Fertility", type: "other", coordinates: { lat: 50.935412, lng: -1.434177 }, floor: 0 },
    { id: "physio-f0", name: "Physio", type: "department", coordinates: { lat: 50.935416, lng: -1.434844 }, floor: 0 },
    { id: "urodynamics-f0", name: "Urodynamics", type: "other", coordinates: { lat: 50.935415, lng: -1.435379 }, floor: 0 },
    { id: "accessible-wc-f0", name: "ACCESSIBLE WC", type: "toilet", coordinates: { lat: 50.935371, lng: -1.436748 }, floor: 0 },
    { id: "right-handed-transfer-f0", name: "(RIGHT HANDED TRANSFER)", type: "other", coordinates: { lat: 50.935344, lng: -1.436641 }, floor: 0 },
    { id: "genetics-f0", name: "Genetics", type: "other", coordinates: { lat: 50.934943, lng: -1.435501 }, floor: 0 },
  ],
}
