import { Venue } from "../types"

// Princess Anne Hospital — reconstructed from the trust's own map sheet
// (map/auto/pah-h-level-floor-plan.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const PAH_H_LEVEL_FLOOR_PLAN_VENUE: Venue = {
  id: "pah-h-level-floor-plan-venue",
  slug: "pah-h-level-floor-plan",
  name: "Princess Anne Hospital",
  subtitle: "Solent NHS Trust · SO16 5YA",
  category: "hospital",
  center: { lat: 50.935249, lng: -1.434855 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Solent NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["University Hospital Southampton", "LIFT", "STAIRWELL", "MALE WC", "Brooke Ward"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/pah-h-level-floor-plan/sitemap.svg", bounds: [[50.934217, -1.437171], [50.936281, -1.432539]] },
  ],
  waypoints: [
    { id: "university-hospital-southampton-f0", name: "University Hospital Southampton", type: "department", coordinates: { lat: 50.936245, lng: -1.433166 }, floor: 0 },
    { id: "lift-f0", name: "LIFT", type: "lift", coordinates: { lat: 50.935754, lng: -1.43681 }, floor: 0 },
    { id: "stairwell-f0", name: "STAIRWELL", type: "other", coordinates: { lat: 50.935678, lng: -1.43674 }, floor: 0 },
    { id: "male-wc-f0", name: "MALE WC", type: "toilet", coordinates: { lat: 50.9356, lng: -1.43676 }, floor: 0 },
    { id: "brooke-ward-f0", name: "Brooke Ward", type: "ward", coordinates: { lat: 50.935531, lng: -1.434158 }, floor: 0 },
    { id: "bramshaw-ward-f0", name: "Bramshaw Ward", type: "ward", coordinates: { lat: 50.93552, lng: -1.435542 }, floor: 0 },
    { id: "female-wc-f0", name: "FEMALE WC", type: "toilet", coordinates: { lat: 50.935523, lng: -1.436736 }, floor: 0 },
    { id: "unisex-wc-f0", name: "UNISEX WC", type: "toilet", coordinates: { lat: 50.935444, lng: -1.436741 }, floor: 0 },
    { id: "accessible-wc-left-handed-transfer-f0", name: "ACCESSIBLE WC (LEFT HANDED TRANSFER)", type: "toilet", coordinates: { lat: 50.935368, lng: -1.43664 }, floor: 0 },
    { id: "colposcopy-hysteroscopy-pmb-clinic-f0", name: "Colposcopy Hysteroscopy PMB Clinic", type: "department", coordinates: { lat: 50.935077, lng: -1.434227 }, floor: 0 },
  ],
}
