import { Venue } from "../types"

// Princess Anne Hospital — reconstructed from the trust's own map sheet
// (map/auto/pah-f-level-floor-plan.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const PAH_F_LEVEL_FLOOR_PLAN_VENUE: Venue = {
  id: "pah-f-level-floor-plan-venue",
  slug: "pah-f-level-floor-plan",
  name: "Princess Anne Hospital",
  subtitle: "Solent NHS Trust · SO16 5YA",
  category: "hospital",
  center: { lat: 50.935249, lng: -1.434855 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Solent NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["University Hospital Southampton", "STAIRWELL", "LIFT", "MALE WC", "FEMALE WC"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/pah-f-level-floor-plan/sitemap.svg", bounds: [[50.934217, -1.437171], [50.936281, -1.432539]] },
  ],
  waypoints: [
    { id: "university-hospital-southampton-f0", name: "University Hospital Southampton", type: "department", coordinates: { lat: 50.936229, lng: -1.433193 }, floor: 0 },
    { id: "stairwell-f0", name: "STAIRWELL", type: "other", coordinates: { lat: 50.936015, lng: -1.436394 }, floor: 0 },
    { id: "lift-f0", name: "LIFT", type: "lift", coordinates: { lat: 50.93594, lng: -1.436463 }, floor: 0 },
    { id: "male-wc-f0", name: "MALE WC", type: "toilet", coordinates: { lat: 50.935862, lng: -1.436414 }, floor: 0 },
    { id: "female-wc-f0", name: "FEMALE WC", type: "toilet", coordinates: { lat: 50.935787, lng: -1.43639 }, floor: 0 },
    { id: "unisex-wc-f0", name: "UNISEX WC", type: "toilet", coordinates: { lat: 50.935709, lng: -1.436395 }, floor: 0 },
    { id: "burley-ward-f0", name: "Burley Ward", type: "ward", coordinates: { lat: 50.935609, lng: -1.434272 }, floor: 0 },
    { id: "lyndhurst-ward-f0", name: "Lyndhurst Ward", type: "ward", coordinates: { lat: 50.935584, lng: -1.435825 }, floor: 0 },
    { id: "parent-education-centre-f0", name: "Parent Education Centre", type: "department", coordinates: { lat: 50.934526, lng: -1.434964 }, floor: 0 },
  ],
}
