import { Venue } from "../types"

// Dewsbury & District Hospital-Combined Elective Surgical Hub — reconstructed from the trust's own map sheet
// (map/auto/pinderfields-hospital-map.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const PINDERFIELDS_HOSPITAL_MAP_VENUE: Venue = {
  id: "pinderfields-hospital-map-venue",
  slug: "pinderfields-hospital-map",
  name: "Dewsbury & District Hospital-Combined Elective Surgical Hub",
  subtitle: "Mid Yorkshire Teaching NHS Trust · WF13 4HS",
  category: "hospital",
  center: { lat: 53.702267, lng: -1.651881 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Mid Yorkshire Teaching NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["Main Entrance", "Accident and Emerency Entrance (A&E)", "Pinderfields Hospital", "Drop off route to A&E", "Leeds Via M1"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/pinderfields-hospital-map/sitemap.svg", bounds: [[53.700168, -1.656896], [53.704366, -1.646866]] },
  ],
  waypoints: [
    { id: "pinderfields-hospital-f0", name: "Pinderfields Hospital", type: "department", coordinates: { lat: 53.70411, lng: -1.65576 }, floor: 0 },
    { id: "drop-off-route-to-a-e-f0", name: "Drop off route to A&E", type: "department", coordinates: { lat: 53.704109, lng: -1.652837 }, floor: 0 },
    { id: "leeds-via-m1-f0", name: "Leeds Via M1", type: "other", coordinates: { lat: 53.703697, lng: -1.655853 }, floor: 0 },
    { id: "pontefract-via-m62-f0", name: "Pontefract Via M62", type: "other", coordinates: { lat: 53.703697, lng: -1.652068 }, floor: 0 },
    { id: "visitors-pay-and-display-parkin-f0", name: "Visitors pay and display parkin", type: "other", coordinates: { lat: 53.703506, lng: -1.649141 }, floor: 0 },
    { id: "visitors-blue-bade-parkin-f0", name: "Visitors blue bade parkin", type: "other", coordinates: { lat: 53.703295, lng: -1.649303 }, floor: 0 },
    { id: "main-entrance-f0", name: "Main Entrance", type: "exit", coordinates: { lat: 53.703017, lng: -1.654357 }, floor: 0 },
    { id: "shuttle-bus-pick-up-drop-off-point-f0", name: "Shuttle bus pick up/drop off point", type: "exit", coordinates: { lat: 53.702879, lng: -1.649065 }, floor: 0 },
    { id: "eye-centre-footpath-f0", name: "Eye Centre footpath", type: "department", coordinates: { lat: 53.702661, lng: -1.649551 }, floor: 0 },
    { id: "bike-lockup-area-f0", name: "Bike lockup area", type: "other", coordinates: { lat: 53.702448, lng: -1.649683 }, floor: 0 },
    { id: "eye-centre-drop-off-only-f0", name: "Eye Centre Drop Off Only", type: "exit", coordinates: { lat: 53.702384, lng: -1.65255 }, floor: 0 },
    { id: "staff-parkin-f0", name: "Staff Parkin", type: "other", coordinates: { lat: 53.702245, lng: -1.649801 }, floor: 0 },
    { id: "patient-areas-f0", name: "Patient Areas", type: "other", coordinates: { lat: 53.702054, lng: -1.650279 }, floor: 0 },
    { id: "accident-and-emerency-entrance-a-e-f0", name: "Accident and Emerency Entrance (A&E)", type: "department", coordinates: { lat: 53.701916, lng: -1.64905 }, floor: 0 },
    { id: "closed-f0", name: "CLOSED", type: "other", coordinates: { lat: 53.70157, lng: -1.655318 }, floor: 0 },
    { id: "maternity-emerency-entrance-f0", name: "Maternity Emerency Entrance", type: "exit", coordinates: { lat: 53.701562, lng: -1.649362 }, floor: 0 },
    { id: "rehabilitation-department-entrance-f0", name: "Rehabilitation Department Entrance", type: "exit", coordinates: { lat: 53.701379, lng: -1.649209 }, floor: 0 },
    { id: "dermatoloy-ashton-centre-f0", name: "Dermatoloy (Ashton Centre)", type: "department", coordinates: { lat: 53.701199, lng: -1.649399 }, floor: 0 },
    { id: "diabetes-centre-f0", name: "Diabetes Centre", type: "department", coordinates: { lat: 53.701025, lng: -1.649817 }, floor: 0 },
    { id: "eye-centre-f0", name: "Eye Centre", type: "department", coordinates: { lat: 53.700843, lng: -1.649975 }, floor: 0 },
    { id: "clinical-research-innovation-buildin-crib-f0", name: "Clinical Research & Innovation Buildin (CRIB)", type: "department", coordinates: { lat: 53.700668, lng: -1.648947 }, floor: 0 },
    { id: "limited-access-delivery-f0", name: "Limited Access/Delivery", type: "other", coordinates: { lat: 53.700525, lng: -1.651749 }, floor: 0 },
    { id: "staff-areas-f0", name: "Staff areas", type: "other", coordinates: { lat: 53.700525, lng: -1.650352 }, floor: 0 },
    { id: "trust-hq-and-education-centre-f0", name: "Trust HQ and Education Centre", type: "department", coordinates: { lat: 53.70038, lng: -1.649391 }, floor: 0 },
  ],
}
