import { Venue } from "../types"

// Princess of Wales Hospital — reconstructed from the trust's own map sheet
// (map/auto/princess-of-wales-community-hospital-site-map.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const PRINCESS_OF_WALES_COMMUNITY_HOSPITAL_SITE_MAP_VENUE: Venue = {
  id: "princess-of-wales-community-hospital-site-map-venue",
  slug: "princess-of-wales-community-hospital-site-map",
  name: "Princess of Wales Hospital",
  subtitle: "Herefordshire and Worcestershire Health and Care NHS Trust · B61 0BB",
  category: "hospital",
  center: { lat: 52.34415, lng: -2.055657 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Herefordshire and Worcestershire Health and Care NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["Reception", "Entrances", "Main entrance", "Princess of Wales Community Hospital", "Lifts and stairs to 1st floor"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/princess-of-wales-community-hospital-site-map/sitemap.svg", bounds: [[52.342641, -2.059149], [52.345659, -2.052165]] },
  ],
  waypoints: [
    { id: "princess-of-wales-community-hospital-f0", name: "Princess of Wales Community Hospital", type: "department", coordinates: { lat: 52.345433, lng: -2.058215 }, floor: 0 },
    { id: "lifts-and-stairs-to-1st-floor-f0", name: "Lifts and stairs to 1st floor", type: "lift", coordinates: { lat: 52.345091, lng: -2.054863 }, floor: 0 },
    { id: "reception-f0", name: "Reception", type: "reception", coordinates: { lat: 52.344708, lng: -2.058443 }, floor: 0 },
    { id: "parking-f0", name: "Parking", type: "other", coordinates: { lat: 52.344444, lng: -2.058499 }, floor: 0 },
    { id: "entrances-f0", name: "Entrances", type: "exit", coordinates: { lat: 52.344313, lng: -2.058452 }, floor: 0 },
    { id: "therapies-paediatric-ot-physiotherapy-f0", name: "Therapies Paediatric OT Physiotherapy", type: "department", coordinates: { lat: 52.344184, lng: -2.056109 }, floor: 0 },
    { id: "toilets-f0", name: "Toilets", type: "toilet", coordinates: { lat: 52.344181, lng: -2.058527 }, floor: 0 },
    { id: "outpatient-clinics-dental-podiatry-audiology-orthoptist-f0", name: "Outpatient clinics Dental Podiatry Audiology Orthoptist", type: "department", coordinates: { lat: 52.343962, lng: -2.053417 }, floor: 0 },
    { id: "lifts-f0", name: "Lifts", type: "lift", coordinates: { lat: 52.344049, lng: -2.05858 }, floor: 0 },
    { id: "main-entrance-f0", name: "Main entrance", type: "exit", coordinates: { lat: 52.343978, lng: -2.055723 }, floor: 0 },
    { id: "league-of-friends-shop-f0", name: "League of Friends Shop", type: "other", coordinates: { lat: 52.343917, lng: -2.058133 }, floor: 0 },
    { id: "x-ray-reception-f0", name: "X-ray reception", type: "reception", coordinates: { lat: 52.343763, lng: -2.054903 }, floor: 0 },
    { id: "main-corridors-f0", name: "Main Corridors", type: "other", coordinates: { lat: 52.343785, lng: -2.05833 }, floor: 0 },
    { id: "drop-off-point-f0", name: "Drop off point", type: "exit", coordinates: { lat: 52.343685, lng: -2.055881 }, floor: 0 },
    { id: "minor-injuries-unit-f0", name: "Minor Injuries Unit", type: "department", coordinates: { lat: 52.343472, lng: -2.054542 }, floor: 0 },
    { id: "electric-charging-points-f0", name: "Electric charging points", type: "other", coordinates: { lat: 52.343416, lng: -2.057069 }, floor: 0 },
    { id: "miu-entrance-f0", name: "MIU entrance", type: "exit", coordinates: { lat: 52.343237, lng: -2.054773 }, floor: 0 },
  ],
}
