import { Venue } from "../types"

// Queen Charlotte's & Chelsea Hospital — reconstructed from the trust's own site map sheet
// (map/Queen Charlottes and Chelsea Hospital location map.pdf). Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const QCCH_VENUE: Venue = {
  id: "queen-charlottes-chelsea-hospital",
  slug: "qcch",
  name: "Queen Charlotte's & Chelsea Hospital",
  subtitle: "Imperial College Healthcare NHS Trust · Du Cane Road, London W12 0HS",
  category: "hospital",
  center: { lat: 51.51706, lng: -0.235544 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Maternity and neonatal hospital sharing the Hammersmith Hospital site; floor legend runs GF (main reception) up to level 4 (neonatal intensive care)." },
  quickAccess: ["Main entrance", "Delivery suite", "Birth centre", "Centre for fetal care", "Neonatal intensive Care - Unit"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/qcch/sitemap.svg", bounds: [[51.515818, -0.238648], [51.518548, -0.23244]] },
  ],
  waypoints: [
    { id: "catherine-lewis-centre-f0", name: "Catherine Lewis centre", type: "department", coordinates: { lat: 51.517967, lng: -0.23558 }, floor: 0 },
    { id: "garry-weston-centre-f0", name: "Garry Weston centre", type: "department", coordinates: { lat: 51.517652, lng: -0.23561 }, floor: 0 },
    { id: "mrc-clinical-sciences-centre-f0", name: "MRC Clinical Sciences centre", type: "department", coordinates: { lat: 51.517494, lng: -0.235679 }, floor: 0 },
    { id: "wolfson-education-centre-f0", name: "Wolfson education centre", type: "department", coordinates: { lat: 51.517472, lng: -0.235281 }, floor: 0 },
    { id: "neonatal-intensive-care-f0", name: "Neonatal intensive Care", type: "department", coordinates: { lat: 51.517486, lng: -0.233034 }, floor: 0 },
    { id: "restaurant-f0", name: "Restaurant", type: "canteen", coordinates: { lat: 51.517459, lng: -0.236277 }, floor: 0 },
    { id: "renal-building-f0", name: "Renal building", type: "department", coordinates: { lat: 51.517435, lng: -0.236941 }, floor: 0 },
    { id: "hammersmith-house-f0", name: "Hammersmith House", type: "department", coordinates: { lat: 51.517359, lng: -0.237211 }, floor: 0 },
    { id: "delivery-suite-f0", name: "Delivery suite", type: "department", coordinates: { lat: 51.517255, lng: -0.233233 }, floor: 0 },
    { id: "commonwealth-building-f0", name: "Commonwealth building", type: "department", coordinates: { lat: 51.517227, lng: -0.235624 }, floor: 0 },
    { id: "centre-for-fetal-care-early-pregnancy-unit-epu-f0", name: "Centre for fetal care Early pregnancy unit (EPU)", type: "department", coordinates: { lat: 51.517005, lng: -0.233068 }, floor: 0 },
    { id: "birth-centre-edith-dare-ward-f0", name: "Birth centre Edith Dare ward", type: "ward", coordinates: { lat: 51.51679, lng: -0.233228 }, floor: 0 },
    { id: "south-admin-f0", name: "South admin", type: "other", coordinates: { lat: 51.516601, lng: -0.236468 }, floor: 0 },
    { id: "imperial-clinical-research-facility-f0", name: "Imperial Clinical Research Facility", type: "department", coordinates: { lat: 51.516524, lng: -0.235161 }, floor: 0 },
    { id: "east-acton-f0", name: "East Acton", type: "other", coordinates: { lat: 51.516145, lng: -0.238432 }, floor: 0 },
    { id: "main-entrance-f0", name: "Main entrance", type: "exit", coordinates: { lat: 51.516143, lng: -0.237747 }, floor: 0 },
    { id: "south-west-f0", name: "South west", type: "other", coordinates: { lat: 51.516082, lng: -0.237747 }, floor: 0 },
    { id: "white-city-f0", name: "White City", type: "other", coordinates: { lat: 51.515986, lng: -0.234736 }, floor: 0 },
  ],
}
