import { Venue } from "../types"

// Queen Elizabeth Hospital, Woolwich — Lewisham and Greenwich NHS Trust. Tel: 020 8836 6000.
//
// This venue reproduces the trust's own designed wayfinding map: the floor
// plan (/floorplans/qeh/sitemap.svg) is the vector artwork of the trust's official
// site map sheet (colour-coded zones, buildings, roads, corridors and key,
// exactly as designed), and the waypoints are the sheet's full Floor/Zone
// directory. The sheet is drawn with North pointing right; the overlay keeps
// the designed orientation. Entries labelled on the sheet sit at their true
// position; the rest are placed within their colour zone's footprint on the
// correct floor (illustrative within the zone, like St George's).
//
// Generated by scripts/lgt/generate-lgt-venues.py — edit that, not this.

export const QEH_VENUE: Venue = {
  id: "qeh-woolwich",
  slug: "queen-elizabeth-hospital-woolwich",
  name: "Queen Elizabeth Hospital, Woolwich",
  subtitle: "Lewisham and Greenwich NHS Trust · Stadium Road, London SE18 4QH",
  category: "hospital",
  center: { lat: 51.478191, lng: 0.050057 },
  defaultZoom: 17,
  visibility: "public",
  // Real trust map data, but not owner-confirmed in-app — left unverified.
  verified: false,
  accessibility: {
    stepFreeRoute: true,
    accessibleToilets: true,
    notes: "Accessible (Blue Badge) parking by the main entrance and west car parks; help desks in Main Reception. Lifts serve the first floor.",
  },
  quickAccess: ["Main Entrance & Emergency Department", "A&E (Children’s and Adults)", "Outpatients Departments A - G", "Blood Tests", "Pharmacy", "Restaurant"],
  // The same designed site-map sheet serves every floor: wards above ground
  // are found by zone colour + floor, exactly how the trust's sheet works.
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/qeh/sitemap.svg", bounds: [[51.476925, 0.046235], [51.479457, 0.053879]] },
    { id: "f1", floor: 1, label: "First Floor", imageUrl: "/floorplans/qeh/sitemap.svg", bounds: [[51.476925, 0.046235], [51.479457, 0.053879]] },
  ],
  waypoints: [
    // ── Outpatients ─────────────────────────────────────────────────────────
    { id: "alexandra-clinic-f1", name: "Alexandra Clinic", type: "department", coordinates: { lat: 51.479009, lng: 0.050961 }, floor: 1, description: "Red zone" },
    { id: "ambulatory-care-unit-f0", name: "Ambulatory Care Unit", type: "department", coordinates: { lat: 51.478427, lng: 0.05031 }, floor: 0, description: "Green zone" },
    { id: "blood-tests-f0", name: "Blood Tests", type: "department", coordinates: { lat: 51.478573, lng: 0.050388 }, floor: 0, description: "Green zone" },
    { id: "cardiac-department-f0", name: "Cardiac Department", type: "department", coordinates: { lat: 51.478985, lng: 0.051389 }, floor: 0, description: "Red zone" },
    { id: "childrens-assessment-unit-f0", name: "Childrens Assessment Unit", type: "department", coordinates: { lat: 51.478742, lng: 0.049561 }, floor: 0, description: "Green zone" },
    { id: "clinical-decisions-unit-f0", name: "Clinical Decisions Unit", type: "department", coordinates: { lat: 51.478863, lng: 0.050767 }, floor: 0, description: "Red zone" },
    { id: "day-care-unit-f0", name: "Day Care Unit", type: "department", coordinates: { lat: 51.478912, lng: 0.051428 }, floor: 0, description: "Red zone" },
    { id: "delivery-suite-f1", name: "Delivery Suite", type: "department", coordinates: { lat: 51.478863, lng: 0.051739 }, floor: 1, description: "Red zone" },
    { id: "diabetic-day-care-f0", name: "Diabetic Day Care", type: "department", coordinates: { lat: 51.478742, lng: 0.050456 }, floor: 0, description: "Green zone" },
    { id: "discharge-lounge-f0", name: "Discharge Lounge", type: "department", coordinates: { lat: 51.479275, lng: 0.050028 }, floor: 0, description: "Blue zone" },
    { id: "dolphin-childrens-opd-f0", name: "Dolphin Childrens OPD", type: "department", coordinates: { lat: 51.478621, lng: 0.049328 }, floor: 0, description: "Green zone" },
    { id: "fracture-clinic-f0", name: "Fracture Clinic", type: "department", coordinates: { lat: 51.478694, lng: 0.051117 }, floor: 0, description: "Red zone" },
    { id: "general-ultrasound-f0", name: "General Ultrasound", type: "department", coordinates: { lat: 51.478718, lng: 0.051506 }, floor: 0, description: "Red zone" },
    { id: "imaging-x-ray-f0", name: "Imaging X-ray", type: "department", coordinates: { lat: 51.478621, lng: 0.050767 }, floor: 0, description: "Red zone" },
    { id: "kings-greenwich-renal-centre-f1", name: "Kings Greenwich Renal Centre", type: "department", coordinates: { lat: 51.478621, lng: 0.049872 }, floor: 1, description: "Green zone" },
    { id: "macmillan-brook-unit-f1", name: "Macmillan Brook Unit", type: "department", coordinates: { lat: 51.478573, lng: 0.050222 }, floor: 1, description: "Green zone" },
    { id: "maternity-opd-f1", name: "Maternity OPD", type: "department", coordinates: { lat: 51.47867, lng: 0.051234 }, floor: 1, description: "Red zone" },
    { id: "medical-diagnostic-centre-f0", name: "Medical Diagnostic Centre", type: "department", coordinates: { lat: 51.478427, lng: 0.049289 }, floor: 0, description: "Green zone" },
    { id: "medical-photography-ranken-house-f0", name: "Medical Photography (Ranken House)", type: "department", coordinates: { lat: 51.4781, lng: 0.048355 }, floor: 0, description: "Yellow zone" },
    { id: "obstetrics-ultrasound-f1", name: "Obstetrics Ultrasound", type: "department", coordinates: { lat: 51.478597, lng: 0.051662 }, floor: 1, description: "Red zone" },
    { id: "outpatients-departments-a-g-f0", name: "Outpatients Departments A - G", type: "department", coordinates: { lat: 51.478591, lng: 0.049726 }, floor: 0, description: "Green zone" },
    { id: "pathology-f0", name: "Pathology", type: "department", coordinates: { lat: 51.479178, lng: 0.049483 }, floor: 0, description: "Blue zone" },
    { id: "pharmacy-f0", name: "Pharmacy", type: "pharmacy", coordinates: { lat: 51.478524, lng: 0.049561 }, floor: 0, description: "Green zone" },
    { id: "physiotherapy-outpatients-f0", name: "Physiotherapy (Outpatients)", type: "department", coordinates: { lat: 51.478985, lng: 0.048618 }, floor: 0, description: "Yellow zone" },
    { id: "renal-centre-f1", name: "Renal Centre", type: "department", coordinates: { lat: 51.4785, lng: 0.049794 }, floor: 1, description: "Green zone" },
    { id: "respiratory-laboratory-f0", name: "Respiratory Laboratory", type: "department", coordinates: { lat: 51.478476, lng: 0.050028 }, floor: 0, description: "Green zone" },
    { id: "sleep-unit-f0", name: "Sleep Unit", type: "department", coordinates: { lat: 51.478476, lng: 0.050456 }, floor: 0, description: "Green zone" },
    { id: "theatres-f1", name: "Theatres", type: "department", coordinates: { lat: 51.478524, lng: 0.050845 }, floor: 1, description: "Red zone" },
    // ── Wards ───────────────────────────────────────────────────────────────
    { id: "a-e-childrens-and-adults-f0", name: "A&E (Children’s and Adults)", type: "department", coordinates: { lat: 51.478294, lng: 0.051409 }, floor: 0, description: "Red zone" },
    { id: "critical-care-centre-f1", name: "Critical Care Centre", type: "ward", coordinates: { lat: 51.4785, lng: 0.051273 }, floor: 1, description: "Red zone" },
    { id: "greenwich-birth-centre-f1", name: "Greenwich Birth Centre", type: "ward", coordinates: { lat: 51.478427, lng: 0.051817 }, floor: 1, description: "Red zone" },
    { id: "itu-hdu-ccu-f1", name: "ITU / HDU / CCU", type: "ward", coordinates: { lat: 51.478306, lng: 0.050689 }, floor: 1, description: "Red zone" },
    { id: "scbu-f1", name: "SCBU", type: "ward", coordinates: { lat: 51.478379, lng: 0.051039 }, floor: 1, description: "Red zone" },
    { id: "therapy-services-inpatients-f0", name: "Therapy Services (Inpatients)", type: "department", coordinates: { lat: 51.47833, lng: 0.04925 }, floor: 0, description: "Green zone" },
    { id: "therapy-services-inpatients-f1", name: "Therapy Services (Inpatients)", type: "department", coordinates: { lat: 51.478379, lng: 0.049561 }, floor: 1, description: "Green zone" },
    { id: "urgent-care-centre-f0", name: "Urgent Care Centre", type: "department", coordinates: { lat: 51.478136, lng: 0.050572 }, floor: 0, description: "Red zone" },
    { id: "ward-1-f0", name: "Ward 1", type: "ward", coordinates: { lat: 51.478112, lng: 0.051195 }, floor: 0, description: "Red zone" },
    { id: "ward-2-f0", name: "Ward 2", type: "ward", coordinates: { lat: 51.478136, lng: 0.052128 }, floor: 0, description: "Red zone" },
    { id: "wards-3-4-f0", name: "Wards 3 & 4", type: "ward", coordinates: { lat: 51.478258, lng: 0.049833 }, floor: 0, description: "Green zone" },
    { id: "ward-5-safari-childrens-ward-f0", name: "Ward 5 (Safari Childrens Ward)", type: "ward", coordinates: { lat: 51.478355, lng: 0.050145 }, floor: 0, description: "Green zone" },
    { id: "ward-7-f1", name: "Ward 7", type: "ward", coordinates: { lat: 51.47804, lng: 0.050417 }, floor: 1, description: "Red zone" },
    { id: "ward-12-coronary-care-unit-f1", name: "Ward 12 (Coronary Care Unit)", type: "ward", coordinates: { lat: 51.478064, lng: 0.051117 }, floor: 1, description: "Red zone" },
    { id: "ward-14-f1", name: "Ward 14", type: "ward", coordinates: { lat: 51.478233, lng: 0.049444 }, floor: 1, description: "Green zone" },
    { id: "ward-15-f1", name: "Ward 15", type: "ward", coordinates: { lat: 51.478161, lng: 0.04995 }, floor: 1, description: "Green zone" },
    { id: "ward-16-f1", name: "Ward 16", type: "ward", coordinates: { lat: 51.478136, lng: 0.050183 }, floor: 1, description: "Green zone" },
    { id: "ward-17-f1", name: "Ward 17", type: "ward", coordinates: { lat: 51.478015, lng: 0.049756 }, floor: 1, description: "Green zone" },
    { id: "ward-18-f1", name: "Ward 18", type: "ward", coordinates: { lat: 51.477991, lng: 0.049989 }, floor: 1, description: "Green zone" },
    { id: "ward-19-f1", name: "Ward 19", type: "ward", coordinates: { lat: 51.477943, lng: 0.049444 }, floor: 1, description: "Green zone" },
    { id: "ward-20-f1", name: "Ward 20", type: "ward", coordinates: { lat: 51.477821, lng: 0.049717 }, floor: 1, description: "Green zone" },
    { id: "ward-21-f1", name: "Ward 21", type: "ward", coordinates: { lat: 51.477943, lng: 0.049989 }, floor: 1, description: "Green zone" },
    { id: "ward-22-f0", name: "Ward 22", type: "ward", coordinates: { lat: 51.478015, lng: 0.051623 }, floor: 0, description: "Red zone" },
    { id: "ward-23-f0", name: "Ward 23", type: "ward", coordinates: { lat: 51.47804, lng: 0.05209 }, floor: 0, description: "Red zone" },
    // ── Services ────────────────────────────────────────────────────────────
    { id: "facilities-f0", name: "Facilities", type: "other", coordinates: { lat: 51.479178, lng: 0.050145 }, floor: 0, description: "Blue zone" },
    { id: "elixir-gallery-f0", name: "Elixir Gallery", type: "other", coordinates: { lat: 51.479227, lng: 0.050884 }, floor: 0, description: "Blue zone" },
    { id: "medical-records-education-centre-f0", name: "Medical Records (Education Centre)", type: "department", coordinates: { lat: 51.478397, lng: 0.048423 }, floor: 0, description: "Yellow zone" },
    { id: "pals-f0", name: "PALS", type: "reception", coordinates: { lat: 51.477894, lng: 0.051506 }, floor: 0, description: "Red zone" },
    { id: "patient-access-office-f1", name: "Patient Access Office", type: "department", coordinates: { lat: 51.477797, lng: 0.049483 }, floor: 1, description: "Green zone" },
    { id: "patient-transport-services-f0", name: "Patient & Transport Services", type: "department", coordinates: { lat: 51.479106, lng: 0.049639 }, floor: 0, description: "Blue zone" },
    { id: "prayer-room-f0", name: "Prayer Room", type: "other", coordinates: { lat: 51.477918, lng: 0.051856 }, floor: 0, description: "Red zone" },
    { id: "restaurant-f0", name: "Restaurant", type: "canteen", coordinates: { lat: 51.479009, lng: 0.050378 }, floor: 0, description: "Blue zone" },
    { id: "shop-f0", name: "Shop", type: "other", coordinates: { lat: 51.477749, lng: 0.051701 }, floor: 0, description: "Red zone" },
    { id: "mortuary-f0", name: "Mortuary", type: "other", coordinates: { lat: 51.478839, lng: 0.04995 }, floor: 0, description: "Blue zone" },
    // ── External ────────────────────────────────────────────────────────────
    { id: "brook-house-f0", name: "Brook House", type: "department", coordinates: { lat: 51.479021, lng: 0.047733 }, floor: 0, description: "Yellow zone" },
    { id: "education-centre-f0", name: "Education Centre", type: "department", coordinates: { lat: 51.478657, lng: 0.048316 }, floor: 0, description: "Yellow zone" },
    { id: "oxleas-mental-health-unit-f0", name: "Oxleas Mental Health Unit", type: "department", coordinates: { lat: 51.478676, lng: 0.046799 }, floor: 0, description: "Yellow zone" },
    { id: "trafalgar-clinic-f0", name: "Trafalgar Clinic", type: "department", coordinates: { lat: 51.478863, lng: 0.04711 }, floor: 0, description: "Yellow zone" },
    { id: "conference-centre-f0", name: "Conference Centre", type: "department", coordinates: { lat: 51.479094, lng: 0.048618 }, floor: 0, description: "Yellow zone" },
    { id: "health-care-library-f0", name: "Health Care Library", type: "department", coordinates: { lat: 51.4785, lng: 0.048306 }, floor: 0, description: "Yellow zone" },
    // ── Entrances & buildings ───────────────────────────────────────────────
    { id: "main-entrance-emergency-department-f0", name: "Main Entrance & Emergency Department", type: "exit", coordinates: { lat: 51.47784, lng: 0.050806 }, floor: 0, description: "Main entrance and Emergency Department entrance, off Stadium Road" },
    { id: "west-entrance-f0", name: "West Entrance", type: "exit", coordinates: { lat: 51.478815, lng: 0.0489 }, floor: 0, description: "West entrance, serving the outpatient areas" },
    { id: "childrens-unit-macmillan-brook-unit-entrance-f0", name: "Childrens Unit & Macmillan Brook Unit Entrance", type: "exit", coordinates: { lat: 51.477991, lng: 0.049036 }, floor: 0, description: "Entrance for the Childrens Unit and Macmillan Brook Unit" },
  ],
}
