import { Venue } from "../types"

// Queen Mary's Hospital, Roehampton — St George's University Hospitals NHS
// Foundation Trust, Roehampton Lane, London SW15 5PN. The Ground floor plan
// is the trust's own map; its numbered rooms are placed at their markers.
// Lower Ground/First/Second floor departments are searchable and floor-
// tagged (those floors have no drawn plan in the source booklet).
// Generated by scripts/sheets/generate-qmh.py.

export const QMH_VENUE: Venue = {
  id: "queen-marys-roehampton",
  slug: "queen-marys-roehampton",
  name: "Queen Mary's Hospital, Roehampton",
  subtitle: "St George's University Hospitals NHS Foundation Trust · Roehampton Lane, London SW15 5PN",
  category: "hospital",
  center: { lat: 51.455551, lng: -0.241715 },
  defaultZoom: 18,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Main lifts and stairs serve all floors from the ground-floor main entrance; accessible toilets on every floor; drop-off/pick-up point at the main entrance." },
  quickAccess: ["Information desk", "Minor injuries unit", "Pharmacy", "Radiology", "Courtyard Restaurant"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/qmh/ground.png", bounds: [[51.454051, -0.243715], [51.457051, -0.239715]] },
  ],
  waypoints: [
    // ── Ground Floor ────────────────────────────────────────────────
    { id: "suite-1-f0", name: "Suite 1", type: "department", coordinates: { lat: 51.456441, lng: -0.241041 }, floor: 0, description: "Room 1" },
    { id: "audiology-f0", name: "Audiology", type: "department", coordinates: { lat: 51.456556, lng: -0.241505 }, floor: 0, description: "Room 2" },
    { id: "opthalmology-f0", name: "Opthalmology", type: "department", coordinates: { lat: 51.456589, lng: -0.241064 }, floor: 0, description: "Room 3" },
    { id: "assisted-conception-unit-f0", name: "Assisted conception unit", type: "department", coordinates: { lat: 51.456589, lng: -0.240553 }, floor: 0, description: "Room 4" },
    { id: "nutrition-dietetics-f0", name: "Nutrition & dietetics", type: "department", coordinates: { lat: 51.456441, lng: -0.240926 }, floor: 0, description: "Room 5" },
    { id: "podiatry-f0", name: "Podiatry", type: "department", coordinates: { lat: 51.456359, lng: -0.240881 }, floor: 0, description: "Room 5" },
    { id: "speech-language-therapy-f0", name: "Speech & language therapy", type: "department", coordinates: { lat: 51.456276, lng: -0.240835 }, floor: 0, description: "Room 5" },
    { id: "beta-cell-f0", name: "Beta cell", type: "department", coordinates: { lat: 51.456078, lng: -0.242115 }, floor: 0, description: "Room 6" },
    { id: "medical-photography-f0", name: "Medical photography", type: "department", coordinates: { lat: 51.456458, lng: -0.239784 }, floor: 0, description: "Room 7" },
    { id: "suite-4-f0", name: "Suite 4", type: "department", coordinates: { lat: 51.456441, lng: -0.241368 }, floor: 0, description: "Room 8" },
    { id: "children-s-services-f0", name: "Children's services", type: "department", coordinates: { lat: 51.456111, lng: -0.24261 }, floor: 0, description: "Room 9" },
    { id: "league-of-friends-f0", name: "League of Friends", type: "department", coordinates: { lat: 51.456919, lng: -0.242351 }, floor: 0, description: "Room 10" },
    { id: "clinical-nurse-specialist-f0", name: "Clinical nurse specialist", type: "department", coordinates: { lat: 51.456919, lng: -0.242123 }, floor: 0, description: "Room 11" },
    { id: "pathology-f0", name: "Pathology", type: "department", coordinates: { lat: 51.456754, lng: -0.241742 }, floor: 0, description: "Room 12" },
    { id: "suite-2-f0", name: "Suite 2", type: "department", coordinates: { lat: 51.456507, lng: -0.241147 }, floor: 0, description: "Room 13" },
    { id: "suite-3-f0", name: "Suite 3", type: "department", coordinates: { lat: 51.456507, lng: -0.241262 }, floor: 0, description: "Room 14" },
    { id: "dermatology-suite-f0", name: "Dermatology suite", type: "department", coordinates: { lat: 51.454776, lng: -0.242496 }, floor: 0, description: "Room 15" },
    { id: "children-s-play-area-f0", name: "Children's play area", type: "department", coordinates: { lat: 51.456491, lng: -0.242123 }, floor: 0, description: "Room 16" },
    { id: "patient-advice-liaison-service-pals-f0", name: "Patient Advice & Liaison Service (PALS)", type: "department", coordinates: { lat: 51.455716, lng: -0.243014 }, floor: 0, description: "Room 17" },
    { id: "cashier-patient-affairs-f0", name: "Cashier & patient affairs", type: "department", coordinates: { lat: 51.455716, lng: -0.242862 }, floor: 0, description: "Room 18" },
    { id: "pharmacy-f0", name: "Pharmacy", type: "pharmacy", coordinates: { lat: 51.455716, lng: -0.242694 }, floor: 0, description: "Room 19" },
    { id: "rapid-diagnostic-centre-rdc-reception-f0", name: "Rapid Diagnostic Centre (RDC) reception", type: "reception", coordinates: { lat: 51.455732, lng: -0.242344 }, floor: 0, description: "Room 20" },
    { id: "suite-5-f0", name: "Suite 5", type: "department", coordinates: { lat: 51.455914, lng: -0.241643 }, floor: 0, description: "Room 21" },
    { id: "suite-6-f0", name: "Suite 6", type: "department", coordinates: { lat: 51.456078, lng: -0.240736 }, floor: 0, description: "Room 22" },
    { id: "burns-dressing-clinic-f0", name: "Burns dressing clinic", type: "department", coordinates: { lat: 51.455304, lng: -0.243532 }, floor: 0, description: "Room 23" },
    { id: "addiction-treatment-centre-f0", name: "Addiction treatment centre", type: "department", coordinates: { lat: 51.455122, lng: -0.242595 }, floor: 0, description: "Room 24" },
    { id: "information-desk-f0", name: "Information desk", type: "reception", coordinates: { lat: 51.455337, lng: -0.242298 }, floor: 0, description: "Room 25" },
    { id: "minor-injuries-unit-f0", name: "Minor injuries unit", type: "department", coordinates: { lat: 51.454694, lng: -0.241978 }, floor: 0, description: "Room 26" },
    { id: "radiology-f0", name: "Radiology", type: "department", coordinates: { lat: 51.45504, lng: -0.241323 }, floor: 0, description: "Room 27" },
    { id: "cardiology-f0", name: "Cardiology", type: "department", coordinates: { lat: 51.455172, lng: -0.240782 }, floor: 0, description: "Room 28" },
    { id: "endoscopy-minor-operations-f0", name: "Endoscopy & minor operations", type: "department", coordinates: { lat: 51.4556, lng: -0.240165 }, floor: 0, description: "Room 29" },
    // ── Lower Ground Floor ──────────────────────────────────────────
    { id: "bader-gymnasium-f-1", name: "Bader gymnasium", type: "department", coordinates: { lat: 51.456688, lng: -0.241726 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "brysson-whyte-rehabilitation-unit-f-1", name: "Brysson Whyte rehabilitation unit", type: "department", coordinates: { lat: 51.456688, lng: -0.241528 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "paediatric-prosthetic-occupational-therapy-f-1", name: "Paediatric prosthetic occupational therapy", type: "department", coordinates: { lat: 51.456688, lng: -0.24133 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "douglas-bader-rehabilitation-unit-reception-f-1", name: "Douglas Bader rehabilitation unit reception", type: "reception", coordinates: { lat: 51.456688, lng: -0.241132 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "gait-laboratory-f-1", name: "Gait laboratory", type: "department", coordinates: { lat: 51.456359, lng: -0.241726 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "gwynne-holford-ward-f-1", name: "Gwynne Holford ward", type: "ward", coordinates: { lat: 51.456359, lng: -0.241528 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "limbless-association-douglas-bader-offices-f-1", name: "Limbless Association / Douglas Bader offices", type: "department", coordinates: { lat: 51.456359, lng: -0.24133 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "mary-seacole-ward-f-1", name: "Mary Seacole ward", type: "ward", coordinates: { lat: 51.456359, lng: -0.241132 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "patient-transport-waiting-area-f-1", name: "Patient transport waiting area", type: "department", coordinates: { lat: 51.456029, lng: -0.241726 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "physiotherapy-outpatients-f-1", name: "Physiotherapy outpatients", type: "department", coordinates: { lat: 51.456029, lng: -0.241528 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "prosthetics-orthotics-departments-f-1", name: "Prosthetics & orthotics departments", type: "department", coordinates: { lat: 51.456029, lng: -0.24133 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "rehabilitation-gymnasium-f-1", name: "Rehabilitation gymnasium", type: "department", coordinates: { lat: 51.456029, lng: -0.241132 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "the-sanctuary-f-1", name: "The Sanctuary", type: "department", coordinates: { lat: 51.455699, lng: -0.241726 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "wheelchair-special-seating-services-f-1", name: "Wheelchair & special seating services", type: "department", coordinates: { lat: 51.455699, lng: -0.241528 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "vitali-unit-formerly-wilson-unit-f-1", name: "Vitali unit (formerly Wilson unit)", type: "department", coordinates: { lat: 51.455699, lng: -0.24133 }, floor: -1, description: "Lower Ground — via main lifts" },
    { id: "courtyard-restaurant-f-1", name: "Courtyard Restaurant", type: "canteen", coordinates: { lat: 51.455699, lng: -0.241132 }, floor: -1, description: "Lower Ground — via main lifts" },
    // ── First Floor ─────────────────────────────────────────────────
    { id: "laurel-ward-f1", name: "Laurel ward", type: "ward", coordinates: { lat: 51.456359, lng: -0.241726 }, floor: 1, description: "First Floor — via main lifts" },
    { id: "lavender-ward-f1", name: "Lavender ward", type: "ward", coordinates: { lat: 51.456359, lng: -0.241528 }, floor: 1, description: "First Floor — via main lifts" },
    { id: "rose-ward-f1", name: "Rose ward", type: "ward", coordinates: { lat: 51.456359, lng: -0.24133 }, floor: 1, description: "First Floor — via main lifts" },
    { id: "sandalwood-suite-f1", name: "Sandalwood suite", type: "department", coordinates: { lat: 51.456359, lng: -0.241132 }, floor: 1, description: "First Floor — via main lifts" },
    // ── Second Floor ────────────────────────────────────────────────
    { id: "education-suite-f2", name: "Education suite", type: "department", coordinates: { lat: 51.456359, lng: -0.241726 }, floor: 2, description: "Second Floor — via main lifts" },
    { id: "putney-roehampton-sexual-health-gum-f2", name: "Putney & Roehampton sexual health / GUM", type: "department", coordinates: { lat: 51.456359, lng: -0.241528 }, floor: 2, description: "Second Floor — via main lifts" },
    { id: "community-mental-health-teams-f2", name: "Community Mental Health Teams", type: "department", coordinates: { lat: 51.456359, lng: -0.24133 }, floor: 2, description: "Second Floor — via main lifts" },
    { id: "roehampton-clinic-f2", name: "Roehampton Clinic", type: "department", coordinates: { lat: 51.456359, lng: -0.241132 }, floor: 2, description: "Second Floor — via main lifts" },
    // ── Ground Floor ────────────────────────────────────────────────
    { id: "main-entrance-f0", name: "Main Entrance", type: "department", coordinates: { lat: 51.454133, lng: -0.241734 }, floor: 0, description: "Ground floor main entrance" },
  ],
}
