import { Venue } from "../types"

// Queen's Hospital, Romford — Barking, Havering and Redbridge University
// Hospitals NHS Trust. The floor plan is the trust's site map; entrances sit
// at their exact positions and the tower wards (from the sheet's floor
// schematic) are grouped by floor at the tower. A curated set — extend via
// the in-app plan importer.
// Generated by scripts/sheets/generate-batch4.py — edit that, not this.

export const QUEENS_VENUE: Venue = {
  id: "queens-hospital-romford",
  slug: "queens-hospital-romford",
  name: "Queen's Hospital, Romford",
  subtitle: "Barking, Havering and Redbridge University Hospitals NHS Trust · Rom Valley Way, Romford RM7 0AG",
  category: "hospital",
  center: { lat: 51.569427, lng: 0.180405 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Blue Badge and drop-off bays at the main and maternity entrances; step-free routes marked on the site map. Lifts to all tower floors." },
  quickAccess: ["Main Entrance", "Urgent and Emergency Care", "Maternity Emergency Entrance", "Coronary Care Unit", "Multi-storey paid parking"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/queens/sitemap.svg", bounds: [[51.567927, 0.176515], [51.570927, 0.184295]] },
    { id: "f1", floor: 1, label: "First Floor", imageUrl: "/floorplans/queens/sitemap.svg", bounds: [[51.567927, 0.176515], [51.570927, 0.184295]] },
    { id: "f2", floor: 2, label: "Second Floor", imageUrl: "/floorplans/queens/sitemap.svg", bounds: [[51.567927, 0.176515], [51.570927, 0.184295]] },
    { id: "f3", floor: 3, label: "Third Floor", imageUrl: "/floorplans/queens/sitemap.svg", bounds: [[51.567927, 0.176515], [51.570927, 0.184295]] },
    { id: "f4", floor: 4, label: "Fourth Floor", imageUrl: "/floorplans/queens/sitemap.svg", bounds: [[51.567927, 0.176515], [51.570927, 0.184295]] },
  ],
  waypoints: [
    // ── Entrances & site ──────────────────────────────────────────────
    { id: "main-entrance-f0", name: "Main Entrance", type: "exit", coordinates: { lat: 51.569581, lng: 0.180225 }, floor: 0 },
    { id: "renal-unit-entrance-f0", name: "Renal Unit Entrance", type: "exit", coordinates: { lat: 51.569581, lng: 0.180774 }, floor: 0 },
    { id: "maternity-emergency-entrance-f0", name: "Maternity Emergency Entrance", type: "exit", coordinates: { lat: 51.56922, lng: 0.180722 }, floor: 0 },
    { id: "urgent-and-emergency-care-f0", name: "Urgent and Emergency Care", type: "department", coordinates: { lat: 51.569223, lng: 0.181656 }, floor: 0 },
    { id: "haematology-f0", name: "Haematology", type: "department", coordinates: { lat: 51.56971, lng: 0.183309 }, floor: 0 },
    { id: "oncology-f0", name: "Oncology", type: "department", coordinates: { lat: 51.569647, lng: 0.183309 }, floor: 0 },
    { id: "multi-storey-paid-parking-f0", name: "Multi-storey paid parking", type: "other", coordinates: { lat: 51.569581, lng: 0.179415 }, floor: 0 },
    { id: "little-explorers-creche-f0", name: "Little Explorers Creche", type: "other", coordinates: { lat: 51.569203, lng: 0.1782 }, floor: 0 },
    { id: "bus-station-5-128-175-193-365-496-498-499-f0", name: "Bus Station (5, 128, 175, 193, 365, 496, 498, 499)", type: "other", coordinates: { lat: 51.569369, lng: 0.181088 }, floor: 0 },
    // ── Tower wards & departments ─────────────────────────────────────
    { id: "harvest-a-f4", name: "Harvest A", type: "department", coordinates: { lat: 51.569604, lng: 0.181767 }, floor: 4, description: "Tower — floor 4" },
    { id: "harvest-b-f4", name: "Harvest B", type: "department", coordinates: { lat: 51.569604, lng: 0.181989 }, floor: 4, description: "Tower — floor 4" },
    { id: "sky-a-f4", name: "Sky A", type: "department", coordinates: { lat: 51.569604, lng: 0.182211 }, floor: 4, description: "Tower — floor 4" },
    { id: "sky-b-f4", name: "Sky B", type: "department", coordinates: { lat: 51.569525, lng: 0.181767 }, floor: 4, description: "Tower — floor 4" },
    { id: "sunrise-a-f3", name: "Sunrise A", type: "department", coordinates: { lat: 51.569671, lng: 0.181741 }, floor: 3, description: "Tower — floor 3" },
    { id: "sunrise-b-f3", name: "Sunrise B", type: "department", coordinates: { lat: 51.569671, lng: 0.181963 }, floor: 3, description: "Tower — floor 3" },
    { id: "early-pregnancy-unit-f3", name: "Early Pregnancy Unit", type: "ward", coordinates: { lat: 51.569671, lng: 0.182185 }, floor: 3, description: "Tower — floor 3" },
    { id: "coronary-care-unit-f3", name: "Coronary Care Unit", type: "ward", coordinates: { lat: 51.569591, lng: 0.181741 }, floor: 3, description: "Tower — floor 3" },
    { id: "mandarin-a-f3", name: "Mandarin A", type: "department", coordinates: { lat: 51.569591, lng: 0.181963 }, floor: 3, description: "Tower — floor 3" },
    { id: "mandarin-b-f3", name: "Mandarin B", type: "department", coordinates: { lat: 51.569591, lng: 0.182185 }, floor: 3, description: "Tower — floor 3" },
    { id: "cornflower-a-f3", name: "Cornflower A", type: "department", coordinates: { lat: 51.569512, lng: 0.181741 }, floor: 3, description: "Tower — floor 3" },
    { id: "cornflower-b-f3", name: "Cornflower B", type: "department", coordinates: { lat: 51.569512, lng: 0.181963 }, floor: 3, description: "Tower — floor 3" },
    { id: "jubilee-itu-f3", name: "Jubilee ITU", type: "ward", coordinates: { lat: 51.569512, lng: 0.182185 }, floor: 3, description: "Tower — floor 3" },
    { id: "frailty-units-f2", name: "Frailty Units", type: "department", coordinates: { lat: 51.569604, lng: 0.181715 }, floor: 2, description: "Tower — floor 2" },
    { id: "medical-receiving-f2", name: "Medical Receiving", type: "department", coordinates: { lat: 51.569604, lng: 0.181937 }, floor: 2, description: "Tower — floor 2" },
    { id: "amber-a-f2", name: "Amber A", type: "department", coordinates: { lat: 51.569604, lng: 0.182159 }, floor: 2, description: "Tower — floor 2" },
    { id: "amber-b-f2", name: "Amber B", type: "department", coordinates: { lat: 51.569525, lng: 0.181715 }, floor: 2, description: "Tower — floor 2" },
    { id: "ambulatory-care-unit-f1", name: "Ambulatory Care Unit", type: "ward", coordinates: { lat: 51.569604, lng: 0.181689 }, floor: 1, description: "Tower — floor 1" },
    { id: "antenatal-f1", name: "Antenatal", type: "department", coordinates: { lat: 51.569604, lng: 0.181911 }, floor: 1, description: "Tower — floor 1" },
    { id: "sahara-a-f1", name: "Sahara A", type: "department", coordinates: { lat: 51.569604, lng: 0.182133 }, floor: 1, description: "Tower — floor 1" },
    { id: "sahara-b-f1", name: "Sahara B", type: "department", coordinates: { lat: 51.569525, lng: 0.181689 }, floor: 1, description: "Tower — floor 1" },
    { id: "sunflower-suite-outpatient-clinic-f0", name: "Sunflower Suite Outpatient Clinic", type: "department", coordinates: { lat: 51.569671, lng: 0.181662 }, floor: 0, description: "Tower — floor G" },
    { id: "nuclear-medicine-f0", name: "Nuclear Medicine", type: "department", coordinates: { lat: 51.569671, lng: 0.181885 }, floor: 0, description: "Tower — floor G" },
    { id: "majors-f0", name: "Majors", type: "department", coordinates: { lat: 51.569671, lng: 0.182107 }, floor: 0, description: "Tower — floor G" },
    { id: "resus-f0", name: "Resus", type: "department", coordinates: { lat: 51.569591, lng: 0.181662 }, floor: 0, description: "Tower — floor G" },
    { id: "rafting-f0", name: "RAFTing", type: "department", coordinates: { lat: 51.569591, lng: 0.181885 }, floor: 0, description: "Tower — floor G" },
    { id: "sdec-f0", name: "SDEC", type: "department", coordinates: { lat: 51.569591, lng: 0.182107 }, floor: 0, description: "Tower — floor G" },
    { id: "urgent-treatment-centre-f0", name: "Urgent Treatment Centre", type: "department", coordinates: { lat: 51.569512, lng: 0.181662 }, floor: 0, description: "Tower — floor G" },
    { id: "discharge-lounge-f0", name: "Discharge Lounge", type: "department", coordinates: { lat: 51.569512, lng: 0.181885 }, floor: 0, description: "Tower — floor G" },
    { id: "medical-incident-office-f0", name: "Medical Incident Office", type: "department", coordinates: { lat: 51.569512, lng: 0.182107 }, floor: 0, description: "Tower — floor G" },
  ],
}
