import { Venue } from "../types"

// The Royal London Hospital, Whitechapel — Barts Health NHS Trust. The floor
// plan is the trust's cycle-parking site map: numbered buildings, lettered
// main-building entrances (A-E) and cycle parking, all at the sheet's marked
// positions. NOTE: the sheet is drawn SOUTH-UP (its compass points N down);
// kept in the designed orientation like the other trust sheets.
// Generated by scripts/sheets/generate-batch2.py — edit that, not this.

export const RLH_VENUE: Venue = {
  id: "royal-london",
  slug: "royal-london-hospital",
  name: "The Royal London Hospital",
  subtitle: "Barts Health NHS Trust · Whitechapel Road, London E1 1BB",
  category: "hospital",
  center: { lat: 51.51886, lng: -0.05913 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Blue Badge drop-off by the main entrances; step-free entrances marked on the sheet." },
  quickAccess: ["Main Entrance", "Emergency Entrance", "Outpatients Department", "Dental Hospital"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/rlh/sitemap.png", bounds: [[51.516479, -0.062176], [51.521241, -0.056084]] },
  ],
  waypoints: [
    // ── Buildings ─────────────────────────────────────────────────────────
    { id: "main-building-f0", name: "Main Building", type: "department", coordinates: { lat: 51.518962, lng: -0.060584 }, floor: 0 },
    { id: "main-building-south-f0", name: "Main Building (South)", type: "department", coordinates: { lat: 51.518394, lng: -0.060213 }, floor: 0 },
    { id: "grahame-hayton-unit-f0", name: "Grahame Hayton Unit", type: "department", coordinates: { lat: 51.518137, lng: -0.057888 }, floor: 0, description: "Building 1" },
    { id: "ambrose-king-centre-f0", name: "Ambrose King Centre", type: "department", coordinates: { lat: 51.518044, lng: -0.057888 }, floor: 0, description: "Building 2" },
    { id: "outpatients-department-f0", name: "Outpatients Department", type: "department", coordinates: { lat: 51.518434, lng: -0.057538 }, floor: 0, description: "Building 3" },
    { id: "outpatients-annexe-f0", name: "Outpatients Annexe", type: "department", coordinates: { lat: 51.518216, lng: -0.057241 }, floor: 0, description: "Building 4" },
    { id: "museum-f0", name: "Museum", type: "other", coordinates: { lat: 51.518995, lng: -0.058663 }, floor: 0, description: "Building 5" },
    { id: "dental-hospital-f0", name: "Dental Hospital", type: "department", coordinates: { lat: 51.51891, lng: -0.057379 }, floor: 0, description: "Building 6" },
    { id: "mortuary-service-f0", name: "Mortuary Service", type: "other", coordinates: { lat: 51.519445, lng: -0.060871 }, floor: 0, description: "Building 7" },
    { id: "east-london-counselling-services-f0", name: "East London Counselling Services", type: "department", coordinates: { lat: 51.519471, lng: -0.059395 }, floor: 0, description: "Building 8" },
    { id: "health-and-wellness-centre-f0", name: "Health and Wellness Centre", type: "department", coordinates: { lat: 51.519497, lng: -0.058833 }, floor: 0, description: "Building 9" },
    { id: "smokers-clinic-f0", name: "Smokers Clinic", type: "department", coordinates: { lat: 51.51996, lng: -0.059438 }, floor: 0, description: "Building 10" },
    { id: "weight-clinic-f0", name: "Weight Clinic", type: "department", coordinates: { lat: 51.519927, lng: -0.059353 }, floor: 0, description: "Building 10" },
    { id: "james-hora-home-f0", name: "James Hora Home", type: "other", coordinates: { lat: 51.519841, lng: -0.058833 }, floor: 0, description: "Building 11" },
    // ── Entrances ─────────────────────────────────────────────────────────
    { id: "emergency-entrance-f0", name: "Emergency Entrance", type: "exit", coordinates: { lat: 51.518183, lng: -0.060499 }, floor: 0, description: "Main Building entrance A" },
    { id: "main-entrance-f0", name: "Main Entrance", type: "exit", coordinates: { lat: 51.518183, lng: -0.060287 }, floor: 0, description: "Main Building entrance B" },
    { id: "stepney-way-entrance-f0", name: "Stepney Way Entrance", type: "exit", coordinates: { lat: 51.518441, lng: -0.059629 }, floor: 0, description: "Main Building entrance C" },
    { id: "luckes-entrance-f0", name: "Luckes Entrance", type: "exit", coordinates: { lat: 51.518784, lng: -0.060743 }, floor: 0, description: "Main Building entrance D" },
    { id: "clinics-2-and-3-entrance-f0", name: "Clinics 2 and 3 Entrance", type: "exit", coordinates: { lat: 51.518896, lng: -0.060117 }, floor: 0, description: "Main Building entrance E" },
    { id: "drop-off-blue-badge-f0", name: "Drop Off (Blue Badge)", type: "other", coordinates: { lat: 51.518606, lng: -0.060011 }, floor: 0 },
    // ── Cycle parking ─────────────────────────────────────────────────────
    { id: "cycle-parking-varden-street-f0", name: "Cycle parking — Varden Street", type: "other", coordinates: { lat: 51.520204, lng: -0.059406 }, floor: 0 },
    { id: "cycle-parking-clinics-2-3-f0", name: "Cycle parking — Clinics 2 & 3", type: "other", coordinates: { lat: 51.518989, lng: -0.05999 }, floor: 0 },
    { id: "cycle-parking-stepney-way-f0", name: "Cycle parking — Stepney Way", type: "other", coordinates: { lat: 51.518229, lng: -0.059523 }, floor: 0 },
    { id: "cycle-parking-cavell-street-f0", name: "Cycle parking — Cavell Street", type: "other", coordinates: { lat: 51.518731, lng: -0.061178 }, floor: 0 },
    { id: "cycle-parking-mount-terrace-f0", name: "Cycle parking — Mount Terrace", type: "other", coordinates: { lat: 51.517688, lng: -0.057167 }, floor: 0 },
    { id: "cycle-parking-newark-street-f0", name: "Cycle parking — Newark Street", type: "other", coordinates: { lat: 51.519141, lng: -0.057347 }, floor: 0 },
  ],
}
