import { Venue } from "../types"

// P Rbh Virtual Hospital — reconstructed from the trust's own map sheet
// (map/auto/royal-berkshire-hospital-map-jan23.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const ROYAL_BERKSHIRE_HOSPITAL_MAP_JAN23_VENUE: Venue = {
  id: "royal-berkshire-hospital-map-jan23-venue",
  slug: "royal-berkshire-hospital-map-jan23",
  name: "P Rbh Virtual Hospital",
  subtitle: "Royal Berkshire NHS Foundation Trust · RG1 5AN",
  category: "hospital",
  center: { lat: 51.451023, lng: -0.95931 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Royal Berkshire NHS Foundation Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["Emergency", "Emergency Departments External buildings / access", "Dept/Ward Accident", "Dept/Ward ECG", "Disorders"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/royal-berkshire-hospital-map-jan23/sitemap.svg", bounds: [[51.448466, -0.965112], [51.45358, -0.953508]] },
  ],
  waypoints: [
    { id: "dept-ward-accident-f0", name: "Dept/Ward Accident", type: "ward", coordinates: { lat: 51.453337, lng: -0.964524 }, floor: 0 },
    { id: "dept-ward-ecg-f0", name: "Dept/Ward ECG", type: "ward", coordinates: { lat: 51.453337, lng: -0.961762 }, floor: 0 },
    { id: "emergency-f0", name: "Emergency", type: "other", coordinates: { lat: 51.453282, lng: -0.964063 }, floor: 0 },
    { id: "disorders-f0", name: "Disorders", type: "other", coordinates: { lat: 51.452698, lng: -0.958492 }, floor: 0 },
    { id: "clinic-f0", name: "Clinic", type: "department", coordinates: { lat: 51.452698, lng: -0.958158 }, floor: 0 },
    { id: "suite-f0", name: "Suite", type: "department", coordinates: { lat: 51.452347, lng: -0.955933 }, floor: 0 },
    { id: "mortuary-f0", name: "(Mortuary)", type: "other", coordinates: { lat: 51.452347, lng: -0.955552 }, floor: 0 },
    { id: "emergency-departments-external-buildings-access-f0", name: "Emergency Departments External buildings / access", type: "department", coordinates: { lat: 51.450043, lng: -0.955052 }, floor: 0 },
    { id: "eye-block-main-entrance-f0", name: "Eye Block Main Entrance", type: "exit", coordinates: { lat: 51.449015, lng: -0.955548 }, floor: 0 },
    { id: "marsh-marsh-f0", name: "Marsh Marsh", type: "other", coordinates: { lat: 51.449018, lng: -0.961889 }, floor: 0 },
    { id: "patient-information-january-2023-f0", name: "Patient Information, January 2023", type: "other", coordinates: { lat: 51.448778, lng: -0.954616 }, floor: 0 },
  ],
}
