import { Venue } from "../types"

// Sexual Health Sheffield — reconstructed from the trust's own map sheet
// (map/auto/sheffield-teaching-hospitals-nhs-foundation-trust-map.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const SHEFFIELD_TEACHING_HOSPITALS_NHS_FOUNDATION_TRUST_MAP_VENUE: Venue = {
  id: "sheffield-teaching-hospitals-nhs-foundation-trust-map-venue",
  slug: "sheffield-teaching-hospitals-nhs-foundation-trust-map",
  name: "Sexual Health Sheffield",
  subtitle: "Sheffield Teaching Hospitals NHS Foundation Trust · S10 2JF",
  category: "hospital",
  center: { lat: 53.378373, lng: -1.493331 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Sheffield Teaching Hospitals NHS Foundation Trust. Placement is derived automatically (centre from the NHS ODS register, scale estimated) and has not been checked by eye." },
  quickAccess: ["Reaching us by car", "Public transport", "From the M1", "Exit the motorway at"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/sheffield-teaching-hospitals-nhs-foundation-trust-map/sitemap.svg", bounds: [[53.376913, -1.496719], [53.379833, -1.489943]] },
  ],
  waypoints: [
    { id: "reaching-us-by-car-f0", name: "Reaching us by car", type: "other", coordinates: { lat: 53.379566, lng: -1.495727 }, floor: 0 },
    { id: "public-transport-f0", name: "Public transport", type: "other", coordinates: { lat: 53.379566, lng: -1.494297 }, floor: 0 },
    { id: "from-the-m1-f0", name: "From the M1", type: "other", coordinates: { lat: 53.379443, lng: -1.496181 }, floor: 0 },
    { id: "exit-the-motorway-at-f0", name: "Exit the motorway at", type: "other", coordinates: { lat: 53.379443, lng: -1.495516 }, floor: 0 },
    { id: "j33-and-follow-the-a630-and-a57-into-f0", name: "J33 and follow the A630 and A57 into", type: "other", coordinates: { lat: 53.379383, lng: -1.495762 }, floor: 0 },
    { id: "sheffield-f0", name: "Sheffield.", type: "other", coordinates: { lat: 53.379323, lng: -1.496267 }, floor: 0 },
    { id: "central-campus-f0", name: "Central Campus", type: "other", coordinates: { lat: 53.378932, lng: -1.49257 }, floor: 0 },
    { id: "from-the-a61-south-f0", name: "From the A61 South", type: "other", coordinates: { lat: 53.378826, lng: -1.496042 }, floor: 0 },
    { id: "follow-the-a61-f0", name: "Follow the A61", type: "other", coordinates: { lat: 53.378826, lng: -1.495341 }, floor: 0 },
    { id: "this-leaflet-covers-f0", name: "This leaflet covers:", type: "other", coordinates: { lat: 53.378772, lng: -1.492789 }, floor: 0 },
    { id: "the-royal-hallamshire-hospital-f0", name: "The Royal Hallamshire Hospital", type: "department", coordinates: { lat: 53.378681, lng: -1.492591 }, floor: 0 },
    { id: "charles-clifford-dental-hospital-f0", name: "Charles Clifford Dental Hospital", type: "department", coordinates: { lat: 53.378595, lng: -1.492579 }, floor: 0 },
    { id: "weston-park-cancer-centre-f0", name: "Weston Park Cancer Centre", type: "department", coordinates: { lat: 53.37851, lng: -1.492648 }, floor: 0 },
    { id: "travel-line-tel-f0", name: "Travel Line tel:", type: "other", coordinates: { lat: 53.378485, lng: -1.494641 }, floor: 0 },
    { id: "jessop-wing-maternity-hospital-f0", name: "Jessop Wing Maternity Hospital", type: "department", coordinates: { lat: 53.378424, lng: -1.492574 }, floor: 0 },
    { id: "the-f0", name: "The", type: "other", coordinates: { lat: 53.378294, lng: -1.496366 }, floor: 0 },
    { id: "help-with-your-travel-expenses-f0", name: "Help with your travel expenses", type: "other", coordinates: { lat: 53.377953, lng: -1.491 }, floor: 0 },
    { id: "the-northern-general-hospital-f0", name: "The Northern General Hospital", type: "department", coordinates: { lat: 53.377893, lng: -1.492595 }, floor: 0 },
    { id: "10-30am-and-3pm-f0", name: "10.30am and 3pm", type: "other", coordinates: { lat: 53.377768, lng: -1.494073 }, floor: 0 },
    { id: "pil627-f0", name: "Pil627", type: "other", coordinates: { lat: 53.37714, lng: -1.494707 }, floor: 0 },
    { id: "pd6466-sku-32s02sthrhhmap-f0", name: "Pd6466. Sku 32s02sthrhhmap", type: "other", coordinates: { lat: 53.377094, lng: -1.493839 }, floor: 0 },
  ],
}
