import { Venue } from "../types"

// Macclesfield District General Hospital — reconstructed from the trust's own map sheet
// (map/auto/site-2025-05-05-mdgh-first-floor-patients.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const SITE_2025_05_05_MDGH_FIRST_FLOOR_PATIENTS_VENUE: Venue = {
  id: "site-2025-05-05-mdgh-first-floor-patients-venue",
  slug: "site-2025-05-05-mdgh-first-floor-patients",
  name: "Macclesfield District General Hospital",
  subtitle: "Manchester University NHS Foundation Trust · SK10 3BL",
  category: "hospital",
  center: { lat: 53.262339, lng: -2.141072 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by Manchester University NHS Foundation Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["NHS", "East Cheshire", "Welcome to Macclesfield District General Hospital", "NHS Trust", "Ambulances"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/site-2025-05-05-mdgh-first-floor-patients/sitemap.svg", bounds: [[53.259456, -2.148033], [53.265222, -2.134111]] },
  ],
  waypoints: [
    { id: "nhs-f0", name: "NHS", type: "other", coordinates: { lat: 53.26505, lng: -2.134626 }, floor: 0 },
    { id: "east-cheshire-f0", name: "East Cheshire", type: "other", coordinates: { lat: 53.26487, lng: -2.1349 }, floor: 0 },
    { id: "welcome-to-macclesfield-district-general-hospital-f0", name: "Welcome to Macclesfield District General Hospital", type: "department", coordinates: { lat: 53.264904, lng: -2.141841 }, floor: 0 },
    { id: "nhs-trust-f0", name: "NHS Trust", type: "other", coordinates: { lat: 53.264751, lng: -2.134578 }, floor: 0 },
    { id: "ambulances-f0", name: "Ambulances", type: "other", coordinates: { lat: 53.263959, lng: -2.141795 }, floor: 0 },
    { id: "corridor-f0", name: "Corridor", type: "other", coordinates: { lat: 53.262897, lng: -2.141472 }, floor: 0 },
    { id: "staff-f0", name: "Staff", type: "other", coordinates: { lat: 53.262808, lng: -2.139104 }, floor: 0 },
    { id: "the-christie-f0", name: "The Christie", type: "other", coordinates: { lat: 53.262131, lng: -2.144348 }, floor: 0 },
    { id: "silk-ward-f0", name: "Silk Ward", type: "ward", coordinates: { lat: 53.261579, lng: -2.1434 }, floor: 0 },
    { id: "pond-f0", name: "Pond", type: "other", coordinates: { lat: 53.261443, lng: -2.139565 }, floor: 0 },
    { id: "patient-parking-ground-floor-p-f0", name: "Patient parking - Ground Floor P", type: "other", coordinates: { lat: 53.261357, lng: -2.137772 }, floor: 0 },
    { id: "first-floor-key-f0", name: "FIRST FLOOR KEY:", type: "other", coordinates: { lat: 53.260996, lng: -2.144495 }, floor: 0 },
    { id: "treetops-resturant-f0", name: "Treetops Resturant", type: "other", coordinates: { lat: 53.260849, lng: -2.146707 }, floor: 0 },
    { id: "maternity-f0", name: "Maternity", type: "department", coordinates: { lat: 53.260848, lng: -2.144561 }, floor: 0 },
    { id: "orthopaedics-fracture-clinic-xray-f0", name: "Orthopaedics Fracture Clinic/Xray", type: "department", coordinates: { lat: 53.260847, lng: -2.141921 }, floor: 0 },
    { id: "lecture-theatre-f0", name: "Lecture Theatre", type: "department", coordinates: { lat: 53.260669, lng: -2.146815 }, floor: 0 },
    { id: "surgical-treatment-unit-f0", name: "Surgical Treatment Unit", type: "department", coordinates: { lat: 53.260661, lng: -2.144141 }, floor: 0 },
    { id: "pre-op-assessment-f0", name: "Pre Op Assessment", type: "other", coordinates: { lat: 53.260492, lng: -2.146709 }, floor: 0 },
    { id: "cri-f0", name: "Cri", type: "other", coordinates: { lat: 53.26048, lng: -2.144781 }, floor: 0 },
    { id: "endoscopy-treatment-unit-f0", name: "Endoscopy Treatment Unit", type: "department", coordinates: { lat: 53.260305, lng: -2.144142 }, floor: 0 },
    { id: "ante-natal-f0", name: "Ante Natal", type: "other", coordinates: { lat: 53.260302, lng: -2.146963 }, floor: 0 },
    { id: "theatres-f0", name: "Theatres", type: "department", coordinates: { lat: 53.260131, lng: -2.144592 }, floor: 0 },
    { id: "toilets-f0", name: "Toilets", type: "toilet", coordinates: { lat: 53.260087, lng: -2.142741 }, floor: 0 },
    { id: "coronary-care-unit-ccu-f0", name: "Coronary Care Unit (CCU)", type: "department", coordinates: { lat: 53.259945, lng: -2.144086 }, floor: 0 },
    { id: "ward-10-f0", name: "Ward 10", type: "ward", coordinates: { lat: 53.259578, lng: -2.144604 }, floor: 0 },
    { id: "patient-map-april-2025-f0", name: "Patient Map April 2025", type: "other", coordinates: { lat: 53.259494, lng: -2.134662 }, floor: 0 },
  ],
}
