import { Venue } from "../types"

// West Park Hospital — reconstructed from the trust's own map sheet
// (map/auto/site-6458-west-park-rehabilitation-hospital.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const SITE_6458_WEST_PARK_REHABILITATION_HOSPITAL_VENUE: Venue = {
  id: "site-6458-west-park-rehabilitation-hospital-venue",
  slug: "site-6458-west-park-rehabilitation-hospital",
  name: "West Park Hospital",
  subtitle: "The Royal Wolverhampton NHS Trust · WV1 4PW",
  category: "hospital",
  center: { lat: 52.587798, lng: -2.14125 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Site map published by The Royal Wolverhampton NHS Trust. Placement is derived automatically (centre from the NHS ODS register, scale from the OpenStreetMap footprint) and has not been checked by eye." },
  quickAccess: ["Main Entrance & Reception", "Outpatients", "Lifts to Ward 2", "Staff", "Stroke Rehabilitation Unit Ward 2"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/site-6458-west-park-rehabilitation-hospital/sitemap.svg", bounds: [[52.585988, -2.143453], [52.589608, -2.139047]] },
  ],
  waypoints: [
    { id: "lifts-to-ward-2-f0", name: "Lifts to Ward 2", type: "ward", coordinates: { lat: 52.589503, lng: -2.141724 }, floor: 0 },
    { id: "staff-f0", name: "Staff", type: "other", coordinates: { lat: 52.589211, lng: -2.142683 }, floor: 0 },
    { id: "stroke-rehabilitation-unit-ward-2-f0", name: "Stroke Rehabilitation Unit Ward 2", type: "ward", coordinates: { lat: 52.589048, lng: -2.14207 }, floor: 0 },
    { id: "main-entrance-reception-f0", name: "Main Entrance & Reception", type: "exit", coordinates: { lat: 52.589009, lng: -2.141185 }, floor: 0 },
    { id: "1st-floor-f0", name: "(1st floor)", type: "other", coordinates: { lat: 52.589027, lng: -2.141875 }, floor: 0 },
    { id: "care-of-the-elderly-ot-f0", name: "Care of the Elderly / OT", type: "other", coordinates: { lat: 52.588945, lng: -2.139948 }, floor: 0 },
    { id: "physiotherapy-ocas-f0", name: "Physiotherapy & OCAS", type: "department", coordinates: { lat: 52.588938, lng: -2.140369 }, floor: 0 },
    { id: "outpatients-f0", name: "Outpatients", type: "department", coordinates: { lat: 52.588933, lng: -2.140746 }, floor: 0 },
    { id: "physio-treatment-room-5-f0", name: "(Physio Treatment Room 5)", type: "department", coordinates: { lat: 52.588876, lng: -2.139945 }, floor: 0 },
    { id: "ambulance-bay-f0", name: "Ambulance Bay", type: "other", coordinates: { lat: 52.588722, lng: -2.141468 }, floor: 0 },
    { id: "hgv-bay-f0", name: "HGV Bay", type: "other", coordinates: { lat: 52.588608, lng: -2.141197 }, floor: 0 },
    { id: "physiotherapy-f0", name: "Physiotherapy", type: "department", coordinates: { lat: 52.588606, lng: -2.142679 }, floor: 0 },
    { id: "retreat-garden-f0", name: "Retreat Garden", type: "other", coordinates: { lat: 52.588542, lng: -2.140382 }, floor: 0 },
    { id: "generator-oxygen-store-f0", name: "Generator & Oxygen Store", type: "other", coordinates: { lat: 52.588251, lng: -2.140586 }, floor: 0 },
    { id: "boiler-room-f0", name: "Boiler Room", type: "other", coordinates: { lat: 52.588207, lng: -2.140163 }, floor: 0 },
    { id: "west-park-surgery-f0", name: "West Park Surgery", type: "department", coordinates: { lat: 52.588087, lng: -2.141936 }, floor: 0 },
    { id: "west-park-surgery-patient-car-park-f0", name: "West Park Surgery Patient Car Park", type: "other", coordinates: { lat: 52.588009, lng: -2.142714 }, floor: 0 },
    { id: "hearing-services-f0", name: "Hearing Services", type: "other", coordinates: { lat: 52.58768, lng: -2.140945 }, floor: 0 },
    { id: "marson-wing-admin-f0", name: "Marson Wing (Admin)", type: "department", coordinates: { lat: 52.587496, lng: -2.141914 }, floor: 0 },
    { id: "meeting-room-f0", name: "Meeting Room", type: "other", coordinates: { lat: 52.587354, lng: -2.142988 }, floor: 0 },
    { id: "coach-house-f0", name: "Coach House", type: "department", coordinates: { lat: 52.587296, lng: -2.141069 }, floor: 0 },
    { id: "neuro-rehab-unit-f0", name: "Neuro Rehab Unit", type: "department", coordinates: { lat: 52.586937, lng: -2.141658 }, floor: 0 },
    { id: "cleveland-house-f0", name: "Cleveland House", type: "department", coordinates: { lat: 52.586927, lng: -2.140933 }, floor: 0 },
    { id: "leasowes-house-f0", name: "Leasowes House", type: "department", coordinates: { lat: 52.586842, lng: -2.140324 }, floor: 0 },
    { id: "district-nurse-clinic-f0", name: "District Nurse Clinic", type: "department", coordinates: { lat: 52.586622, lng: -2.142233 }, floor: 0 },
    { id: "speech-language-therapy-f0", name: "Speech & Language Therapy", type: "department", coordinates: { lat: 52.586466, lng: -2.141959 }, floor: 0 },
    { id: "mi-625614-10-04-17-v2-f0", name: "Mi_625614_10.04.17_v2", type: "other", coordinates: { lat: 52.586048, lng: -2.139456 }, floor: 0 },
  ],
}
