import { Venue } from "../types"

// St Mary's Hospital, Paddington — Imperial College Healthcare NHS Trust.
// The floor plan is the trust's own site map sheet (February 2024 update);
// every building label on the sheet is a waypoint at its printed position.
// Generated by scripts/sheets/generate-batch2.py — edit that, not this.

export const ST_MARYS_VENUE: Venue = {
  id: "st-marys-paddington",
  slug: "st-marys-paddington",
  name: "St Mary's Hospital, Paddington",
  subtitle: "Imperial College Healthcare NHS Trust · Praed Street, London W2 1NY",
  category: "hospital",
  center: { lat: 51.516972, lng: -0.173555 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Step-free routes shown on the trust's site map; nearest step-free stations at Paddington." },
  quickAccess: ["Queen Elizabeth the Queen Mother Building (Main Reception)", "A&E", "Urgent Treatment Centre", "Main Outpatients", "Lindo Wing"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/smh/sitemap.svg", bounds: [[51.515321, -0.176802], [51.518623, -0.170308]] },
  ],
  waypoints: [
    { id: "queen-elizabeth-the-queen-mother-building-main-reception-f0", name: "Queen Elizabeth the Queen Mother Building (Main Reception)", type: "reception", coordinates: { lat: 51.517071, lng: -0.17365 }, floor: 0 },
    { id: "a-e-f0", name: "A&E", type: "department", coordinates: { lat: 51.517454, lng: -0.174351 }, floor: 0, description: "Emergency Department" },
    { id: "urgent-treatment-centre-f0", name: "Urgent Treatment Centre", type: "department", coordinates: { lat: 51.516965, lng: -0.172717 }, floor: 0 },
    { id: "main-outpatients-f0", name: "Main Outpatients", type: "department", coordinates: { lat: 51.516345, lng: -0.175412 }, floor: 0 },
    { id: "fracture-clinic-f0", name: "Fracture Clinic", type: "department", coordinates: { lat: 51.516001, lng: -0.171974 }, floor: 0 },
    { id: "lindo-wing-f0", name: "Lindo Wing", type: "department", coordinates: { lat: 51.516629, lng: -0.174223 }, floor: 0 },
    { id: "paterson-building-f0", name: "Paterson Building", type: "department", coordinates: { lat: 51.517778, lng: -0.175497 }, floor: 0 },
    { id: "jefferiss-wing-f0", name: "Jefferiss Wing", type: "department", coordinates: { lat: 51.516021, lng: -0.175274 }, floor: 0 },
    { id: "mary-stanford-building-f0", name: "Mary Stanford Building", type: "department", coordinates: { lat: 51.51647, lng: -0.17468 }, floor: 0 },
    { id: "cambridge-wing-f0", name: "Cambridge Wing", type: "ward", coordinates: { lat: 51.516166, lng: -0.174064 }, floor: 0 },
    { id: "clarence-wing-f0", name: "Clarence Wing", type: "ward", coordinates: { lat: 51.515724, lng: -0.174202 }, floor: 0 },
    { id: "albert-ward-f0", name: "Albert Ward", type: "ward", coordinates: { lat: 51.515724, lng: -0.171401 }, floor: 0 },
    { id: "salton-house-f0", name: "Salton House", type: "other", coordinates: { lat: 51.51583, lng: -0.171985 }, floor: 0 },
    { id: "winston-churchill-wing-f0", name: "Winston Churchill Wing", type: "other", coordinates: { lat: 51.515638, lng: -0.175327 }, floor: 0 },
    { id: "dumbell-house-f0", name: "Dumbell House", type: "other", coordinates: { lat: 51.515631, lng: -0.170828 }, floor: 0 },
    { id: "mint-wing-f0", name: "Mint Wing", type: "department", coordinates: { lat: 51.517025, lng: -0.176208 }, floor: 0 },
    { id: "mint-wing-south-f0", name: "Mint Wing (South)", type: "department", coordinates: { lat: 51.516728, lng: -0.175592 }, floor: 0 },
    { id: "the-bays-f0", name: "The Bays", type: "other", coordinates: { lat: 51.518161, lng: -0.176038 }, floor: 0 },
    { id: "mortuary-f0", name: "Mortuary", type: "other", coordinates: { lat: 51.51643, lng: -0.171327 }, floor: 0 },
    { id: "imperial-college-medical-school-f0", name: "Imperial College Medical School", type: "other", coordinates: { lat: 51.515955, lng: -0.172823 }, floor: 0 },
  ],
}
