import { Venue } from "../types"

// Trafford General Hospital — reconstructed from the trust's own site map sheet
// (map/Trafford-General-Hospital-map.pdf). Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const TRAFFORD_VENUE: Venue = {
  id: "trafford-general-hospital",
  slug: "trafford",
  name: "Trafford General Hospital",
  subtitle: "Manchester University NHS FT · Moorside Road, Davyhulme, Manchester M41 5SL",
  category: "hospital",
  center: { lat: 53.45619, lng: -2.35566 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Colour-zoned map (Blue / Green / Red) with a ground and first-floor plan and a full department directory. AccessAble accessibility guide available." },
  quickAccess: ["Main Entrance", "Blue Zone", "Green Zone", "Red Zone", "Urgent Care Centre"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/trafford/sitemap.svg", bounds: [[53.455216, -2.356791], [53.457203, -2.352266]] },
  ],
  waypoints: [
    { id: "bereavement-centre-f0", name: "Bereavement Centre", type: "department", coordinates: { lat: 53.456888, lng: -2.355731 }, floor: 0 },
    { id: "greenway-building-f0", name: "Greenway Building", type: "department", coordinates: { lat: 53.456754, lng: -2.3548 }, floor: 0 },
    { id: "pathology-f0", name: "Pathology", type: "department", coordinates: { lat: 53.456625, lng: -2.355906 }, floor: 0 },
    { id: "diabetes-centre-f0", name: "Diabetes Centre", type: "department", coordinates: { lat: 53.456521, lng: -2.356396 }, floor: 0 },
    { id: "childrens-resource-centre-f0", name: "Children’s Resource Centre", type: "department", coordinates: { lat: 53.456501, lng: -2.354876 }, floor: 0 },
    { id: "green-outpatients-f0", name: "Green Outpatients", type: "department", coordinates: { lat: 53.456486, lng: -2.355261 }, floor: 0 },
    { id: "cardio-respiratory-f0", name: "Cardio- Respiratory", type: "department", coordinates: { lat: 53.456479, lng: -2.355817 }, floor: 0 },
    { id: "community-diagnostic-centre-f0", name: "Community Diagnostic Centre", type: "department", coordinates: { lat: 53.456458, lng: -2.356077 }, floor: 0 },
    { id: "chapel-f0", name: "Chapel", type: "other", coordinates: { lat: 53.45645, lng: -2.356361 }, floor: 0 },
    { id: "manchester-orthopaedic-centre-f0", name: "Manchester Orthopaedic Centre", type: "department", coordinates: { lat: 53.45636, lng: -2.354784 }, floor: 0 },
    { id: "ward-11-f0", name: "Ward 11", type: "ward", coordinates: { lat: 53.456328, lng: -2.355188 }, floor: 0 },
    { id: "main-entrance-f0", name: "Main Entrance", type: "exit", coordinates: { lat: 53.456311, lng: -2.355656 }, floor: 0 },
    { id: "pre-op-assessment-f0", name: "Pre Op Assessment", type: "other", coordinates: { lat: 53.456259, lng: -2.35483 }, floor: 0 },
    { id: "acute-medical-unit-f0", name: "Acute Medical Unit", type: "department", coordinates: { lat: 53.45603, lng: -2.354738 }, floor: 0 },
    { id: "phlebotomy-blood-tests-f0", name: "Phlebotomy (Blood Tests)", type: "department", coordinates: { lat: 53.456012, lng: -2.355108 }, floor: 0 },
    { id: "antenatal-f0", name: "Antenatal", type: "other", coordinates: { lat: 53.45596, lng: -2.354564 }, floor: 0 },
    { id: "urgent-care-centre-f0", name: "Urgent Care Centre", type: "department", coordinates: { lat: 53.455899, lng: -2.355314 }, floor: 0 },
    { id: "radiology-x-ray-f0", name: "Radiology (X-Ray)", type: "department", coordinates: { lat: 53.455844, lng: -2.355486 }, floor: 0 },
    { id: "red-outpatients-f0", name: "Red Outpatients", type: "department", coordinates: { lat: 53.455853, lng: -2.355007 }, floor: 0 },
    { id: "moorside-unit-f0", name: "Moorside Unit", type: "department", coordinates: { lat: 53.455795, lng: -2.356455 }, floor: 0 },
    { id: "park-unit-f0", name: "Park Unit", type: "department", coordinates: { lat: 53.455755, lng: -2.354698 }, floor: 0 },
    { id: "macmillan-unit-f0", name: "Macmillan Unit", type: "department", coordinates: { lat: 53.455668, lng: -2.355943 }, floor: 0 },
  ],
}
