import { Venue } from "../types"

// Western Eye Hospital — reconstructed from the trust's own map sheet
// (map/Western Eye Hospital location map.pdf).
// Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const WESTERN_EYE_VENUE: Venue = {
  id: "western-eye-hospital",
  slug: "western-eye",
  name: "Western Eye Hospital",
  subtitle: "Imperial College Healthcare NHS Trust · 153-173 Marylebone Road, London NW1 5QH",
  category: "hospital",
  center: { lat: 51.520702, lng: -0.163316 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "24-hour eye A&E. Nearest stations Marylebone, Baker Street and Edgware Road; floor legend GF–4." },
  quickAccess: ["Eye A&E department", "Macular clinic Optician Toilets", "Day care unit Theatres"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/western-eye/sitemap.svg", bounds: [[51.519835, -0.165482], [51.521741, -0.16115]] },
  ],
  trails: [
    { id: "c0-1", floor: 0, points: [{ lat: 51.521451, lng: -0.162873 }, { lat: 51.521424, lng: -0.162649 }] },
    { id: "c0-2", floor: 0, points: [{ lat: 51.521415, lng: -0.165219 }, { lat: 51.52137, lng: -0.165471 }] },
    { id: "c0-3", floor: 0, points: [{ lat: 51.520885, lng: -0.165038 }, { lat: 51.520773, lng: -0.165096 }] },
    { id: "c0-4", floor: 0, points: [{ lat: 51.520697, lng: -0.164583 }, { lat: 51.520585, lng: -0.164583 }] },
    { id: "c0-5", floor: 0, points: [{ lat: 51.520234, lng: -0.16498 }, { lat: 51.520225, lng: -0.16485 }, { lat: 51.520189, lng: -0.164822 }] },
    { id: "c0-6", floor: 0, points: [{ lat: 51.519987, lng: -0.164843 }, { lat: 51.519969, lng: -0.164655 }, { lat: 51.519974, lng: -0.164605 }] },
    { id: "c0-7", floor: 0, points: [{ lat: 51.519956, lng: -0.164468 }, { lat: 51.519938, lng: -0.164258 }] },
    { id: "c0-8", floor: 0, points: [{ lat: 51.51992, lng: -0.162374 }, { lat: 51.519884, lng: -0.162057 }, { lat: 51.519861, lng: -0.162021 }] },
    { id: "c0-9", floor: 0, points: [{ lat: 51.519884, lng: -0.165132 }, { lat: 51.519884, lng: -0.164966 }, { lat: 51.519861, lng: -0.16493 }] },
    { id: "c0-10", floor: 0, points: [{ lat: 51.519839, lng: -0.164078 }, { lat: 51.519839, lng: -0.16389 }] },
  ],
  waypoints: [
    { id: "day-care-unit-theatres-f0", name: "Day care unit Theatres", type: "department", coordinates: { lat: 51.521028, lng: -0.161672 }, floor: 0 },
    { id: "staff-access-only-f0", name: "Staff access only", type: "other", coordinates: { lat: 51.520911, lng: -0.161606 }, floor: 0 },
    { id: "alex-cross-ward-pre-assessment-clinic-f0", name: "Alex Cross ward Pre-assessment clinic", type: "ward", coordinates: { lat: 51.520768, lng: -0.16158 }, floor: 0 },
    { id: "west-london-day-centre-f0", name: "West London Day Centre", type: "department", coordinates: { lat: 51.52073, lng: -0.162932 }, floor: 0 },
    { id: "cafeteria-toilets-f0", name: "Cafeteria Toilets", type: "canteen", coordinates: { lat: 51.520637, lng: -0.16171 }, floor: 0 },
    { id: "orthoptics-and-visual-fields-outpatients-f0", name: "Orthoptics and visual fields (outpatients)", type: "department", coordinates: { lat: 51.520565, lng: -0.161561 }, floor: 0 },
    { id: "gf-a-e-f0", name: "GF a&E", type: "department", coordinates: { lat: 51.520433, lng: -0.162207 }, floor: 0 },
    { id: "stop-n-main-entrance-ground-floor-f0", name: "Stop N Main entrance Ground floor", type: "exit", coordinates: { lat: 51.520422, lng: -0.165015 }, floor: 0 },
    { id: "eye-a-e-department-f0", name: "Eye A&E department", type: "department", coordinates: { lat: 51.520374, lng: -0.164239 }, floor: 0 },
    { id: "macular-clinic-optician-toilets-f0", name: "Macular clinic Optician Toilets", type: "toilet", coordinates: { lat: 51.520177, lng: -0.161689 }, floor: 0 },
    { id: "marylebone-f0", name: "Marylebone", type: "other", coordinates: { lat: 51.519973, lng: -0.1648 }, floor: 0 },
  ],
}
