import { Venue } from "../types"

// Whipps Cross Hospital — Barts Health NHS Trust. The floor plan is the
// trust's colour-zoned site map (from its cycle-parking sheet): red
// (emergency), orange/pink (diagnostics), green (wards), yellow
// (outpatients) and purple (maternity) zones with numbered wayfinding
// junctions. Departments are placed at their labels; the sheet notes they
// reflect the ground floor, so all waypoints are floor 0.
// Generated by scripts/sheets/generate-batch2.py — edit that, not this.

export const WXH_VENUE: Venue = {
  id: "whipps-cross-hospital",
  slug: "whipps-cross-hospital",
  name: "Whipps Cross Hospital",
  subtitle: "Barts Health NHS Trust · Whipps Cross Road, Leytonstone, London E11 1NR",
  category: "hospital",
  center: { lat: 51.578831, lng: 0.002653 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Colour-coded zones with numbered wayfinding junctions; disabled parking marked; step-free routes along Hospital Road." },
  quickAccess: ["Main Entrance", "A&E", "Urgent Care Centre (UCC)", "Outpatients Reception", "Maternity"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/wxh/sitemap.png", bounds: [[51.577666, -0.000602], [51.579996, 0.005908]] },
  ],
  waypoints: [
    // ── Emergency & assessment ────────────────────────────────────────────
    { id: "a-e-f0", name: "A&E", type: "department", coordinates: { lat: 51.579484, lng: 0.003231 }, floor: 0, description: "Red zone" },
    { id: "childrens-a-e-f0", name: "Children's A&E", type: "department", coordinates: { lat: 51.579553, lng: 0.003176 }, floor: 0, description: "Red zone" },
    { id: "urgent-care-centre-ucc-f0", name: "Urgent Care Centre (UCC)", type: "department", coordinates: { lat: 51.579559, lng: 0.003488 }, floor: 0, description: "Red zone" },
    { id: "aau1-acute-assessment-unit-f0", name: "AAU1 (Acute Assessment Unit)", type: "department", coordinates: { lat: 51.579423, lng: 0.002546 }, floor: 0, description: "Red zone" },
    { id: "aau2-acute-assessment-unit-f0", name: "AAU2 (Acute Assessment Unit)", type: "department", coordinates: { lat: 51.579194, lng: 0.002053 }, floor: 0, description: "Red zone" },
    { id: "ambulatory-care-f0", name: "Ambulatory Care", type: "department", coordinates: { lat: 51.579297, lng: 0.002491 }, floor: 0, description: "Red zone" },
    { id: "forest-assessment-f0", name: "Forest Assessment", type: "department", coordinates: { lat: 51.579184, lng: 0.002437 }, floor: 0, description: "Red zone" },
    { id: "clinical-decisions-unit-cdu-f0", name: "Clinical Decisions Unit (CDU)", type: "department", coordinates: { lat: 51.579116, lng: 0.00271 }, floor: 0, description: "Red zone" },
    { id: "a-e-x-ray-f0", name: "A&E X-Ray", type: "department", coordinates: { lat: 51.579205, lng: 0.002727 }, floor: 0, description: "Red zone" },
    { id: "ct-interventional-f0", name: "CT & Interventional", type: "department", coordinates: { lat: 51.579109, lng: 0.002136 }, floor: 0, description: "Red zone" },
    // ── Diagnostics & clinics ─────────────────────────────────────────────
    { id: "mri-f0", name: "MRI", type: "department", coordinates: { lat: 51.579194, lng: 0.001396 }, floor: 0, description: "Orange zone" },
    { id: "ultrasound-f0", name: "Ultrasound", type: "department", coordinates: { lat: 51.579259, lng: 0.001654 }, floor: 0, description: "Orange zone" },
    { id: "medical-photography-f0", name: "Medical Photography", type: "department", coordinates: { lat: 51.579109, lng: 0.001522 }, floor: 0, description: "Orange zone" },
    { id: "nuclear-medicine-f0", name: "Nuclear Medicine", type: "department", coordinates: { lat: 51.579126, lng: 0.003001 }, floor: 0, description: "Pink zone" },
    { id: "theatres-3-4-f0", name: "Theatres 3 & 4", type: "department", coordinates: { lat: 51.579126, lng: 0.00311 }, floor: 0, description: "Pink zone" },
    { id: "x-ray-f0", name: "X-Ray", type: "department", coordinates: { lat: 51.579102, lng: 0.003324 }, floor: 0, description: "Pink zone" },
    { id: "breast-clinic-f0", name: "Breast Clinic", type: "department", coordinates: { lat: 51.57887, lng: 0.003012 }, floor: 0, description: "Pink zone" },
    { id: "gp-opd-x-ray-f0", name: "GP-OPD X-Ray", type: "department", coordinates: { lat: 51.578877, lng: 0.003285 }, floor: 0, description: "Pink zone" },
    { id: "orthodontics-f0", name: "Orthodontics", type: "department", coordinates: { lat: 51.578904, lng: 0.001435 }, floor: 0, description: "Orange zone" },
    { id: "endoscopy-f0", name: "Endoscopy", type: "department", coordinates: { lat: 51.578898, lng: 0.001577 }, floor: 0, description: "Orange zone" },
    { id: "bereavement-chaplaincy-f0", name: "Bereavement & Chaplaincy", type: "other", coordinates: { lat: 51.578829, lng: 0.001741 }, floor: 0, description: "Orange zone" },
    { id: "learning-centre-f0", name: "Learning Centre", type: "department", coordinates: { lat: 51.578724, lng: 0.001698 }, floor: 0, description: "Orange zone" },
    { id: "gillian-hanson-unit-f0", name: "Gillian Hanson Unit", type: "department", coordinates: { lat: 51.578898, lng: 0.002053 }, floor: 0, description: "Red zone" },
    { id: "chest-clinic-f0", name: "Chest Clinic", type: "department", coordinates: { lat: 51.578734, lng: 0.000986 }, floor: 0, description: "Grey zone" },
    // ── Wards & units ─────────────────────────────────────────────────────
    { id: "intensive-care-unit-icu-f0", name: "Intensive Care Unit (ICU)", type: "ward", coordinates: { lat: 51.579143, lng: 0.003669 }, floor: 0, description: "Green zone" },
    { id: "high-dependency-unit-hdu-f0", name: "High Dependency Unit (HDU)", type: "ward", coordinates: { lat: 51.578802, lng: 0.003669 }, floor: 0, description: "Green zone" },
    { id: "curie-ward-f0", name: "Curie Ward", type: "ward", coordinates: { lat: 51.579143, lng: 0.003942 }, floor: 0, description: "Green zone" },
    { id: "nightingale-ward-f0", name: "Nightingale Ward", type: "ward", coordinates: { lat: 51.57915, lng: 0.0042 }, floor: 0, description: "Green zone" },
    { id: "cath-labs-f0", name: "Cath Labs", type: "department", coordinates: { lat: 51.579126, lng: 0.004337 }, floor: 0, description: "Green zone" },
    { id: "byron-ward-f0", name: "Byron Ward", type: "ward", coordinates: { lat: 51.57917, lng: 0.004463 }, floor: 0, description: "Green zone" },
    { id: "elm-lodge-f0", name: "Elm Lodge", type: "ward", coordinates: { lat: 51.578802, lng: 0.003899 }, floor: 0, description: "Green zone" },
    { id: "mary-ward-f0", name: "Mary Ward", type: "ward", coordinates: { lat: 51.578795, lng: 0.003986 }, floor: 0, description: "Green zone" },
    { id: "willow-lodge-f0", name: "Willow Lodge", type: "ward", coordinates: { lat: 51.578802, lng: 0.004216 }, floor: 0, description: "Green zone" },
    { id: "faraday-ward-f0", name: "Faraday Ward", type: "ward", coordinates: { lat: 51.578809, lng: 0.00426 }, floor: 0, description: "Green zone" },
    { id: "acorn-unit-f0", name: "Acorn Unit", type: "ward", coordinates: { lat: 51.578768, lng: 0.004337 }, floor: 0, description: "Green zone" },
    { id: "lister-ward-f0", name: "Lister Ward", type: "ward", coordinates: { lat: 51.578802, lng: 0.004474 }, floor: 0, description: "Green zone" },
    { id: "pre-assessment-f0", name: "Pre-Assessment", type: "department", coordinates: { lat: 51.578795, lng: 0.004369 }, floor: 0, description: "Green zone" },
    { id: "aspen-house-f0", name: "Aspen House", type: "ward", coordinates: { lat: 51.578614, lng: 0.004446 }, floor: 0, description: "Green zone" },
    { id: "margaret-centre-f0", name: "Margaret Centre", type: "department", coordinates: { lat: 51.579116, lng: 0.004884 }, floor: 0, description: "Green zone" },
    { id: "woodlands-day-unit-f0", name: "Woodlands Day Unit", type: "department", coordinates: { lat: 51.579143, lng: 0.005174 }, floor: 0, description: "Green zone" },
    { id: "connaught-day-hospital-f0", name: "Connaught Day Hospital", type: "department", coordinates: { lat: 51.578932, lng: 0.005229 }, floor: 0, description: "Green zone" },
    // ── Outpatients & maternity ───────────────────────────────────────────
    { id: "eye-treatment-centre-f0", name: "Eye Treatment Centre", type: "department", coordinates: { lat: 51.578369, lng: 0.003242 }, floor: 0, description: "Yellow zone" },
    { id: "childrens-outpatients-f0", name: "Children's Outpatients", type: "department", coordinates: { lat: 51.578365, lng: 0.003696 }, floor: 0, description: "Yellow zone" },
    { id: "outpatients-reception-f0", name: "Outpatients Reception", type: "reception", coordinates: { lat: 51.578273, lng: 0.004271 }, floor: 0, description: "Yellow zone" },
    { id: "outpatients-a-b-f0", name: "Outpatients A & B", type: "department", coordinates: { lat: 51.578079, lng: 0.003543 }, floor: 0, description: "Yellow zone" },
    { id: "outpatients-1-5-f0", name: "Outpatients 1-5", type: "department", coordinates: { lat: 51.578069, lng: 0.004118 }, floor: 0, description: "Yellow zone" },
    { id: "plane-tree-ward-f0", name: "Plane Tree Ward", type: "ward", coordinates: { lat: 51.578069, lng: 0.003012 }, floor: 0, description: "Yellow zone" },
    { id: "renal-unit-f0", name: "Renal Unit", type: "department", coordinates: { lat: 51.577942, lng: 0.003258 }, floor: 0, description: "Yellow zone" },
    { id: "phlebotomy-f0", name: "Phlebotomy", type: "department", coordinates: { lat: 51.578086, lng: 0.00386 }, floor: 0, description: "Yellow zone" },
    { id: "audiology-f0", name: "Audiology", type: "department", coordinates: { lat: 51.578051, lng: 0.004408 }, floor: 0, description: "Yellow zone" },
    { id: "maternity-f0", name: "Maternity", type: "department", coordinates: { lat: 51.578324, lng: 0.004994 }, floor: 0, description: "Purple zone" },
    { id: "antenatal-f0", name: "Antenatal", type: "department", coordinates: { lat: 51.578502, lng: 0.005037 }, floor: 0, description: "Purple zone" },
    { id: "egu-emergency-gynaecology-unit-f0", name: "EGU (Emergency Gynaecology Unit)", type: "department", coordinates: { lat: 51.578096, lng: 0.004736 }, floor: 0, description: "Purple zone" },
    { id: "restaurant-f0", name: "Restaurant", type: "canteen", coordinates: { lat: 51.578761, lng: 0.002491 }, floor: 0, description: "Red zone" },
    // ── Entrances & parking ───────────────────────────────────────────────
    { id: "main-entrance-f0", name: "Main Entrance", type: "exit", coordinates: { lat: 51.579102, lng: 0.001068 }, floor: 0 },
    { id: "sorbus-house-f0", name: "Sorbus House", type: "other", coordinates: { lat: 51.579518, lng: 0.000794 }, floor: 0 },
    { id: "gate-lodge-f0", name: "Gate Lodge", type: "other", coordinates: { lat: 51.579518, lng: 0.001041 }, floor: 0 },
    { id: "tarnswood-health-wellbeing-f0", name: "Tarnswood Health & Wellbeing", type: "department", coordinates: { lat: 51.57973, lng: 0.004463 }, floor: 0 },
    { id: "woodbury-unit-f0", name: "Woodbury Unit", type: "department", coordinates: { lat: 51.579546, lng: 0.004818 }, floor: 0 },
    { id: "m-s-f0", name: "M&S", type: "other", coordinates: { lat: 51.578471, lng: 0.004829 }, floor: 0 },
    { id: "cycle-parking-main-entrance-12-spaces-f0", name: "Cycle parking — Main entrance (12 spaces)", type: "other", coordinates: { lat: 51.578973, lng: 0.001041 }, floor: 0 },
    { id: "cycle-parking-a-e-6-spaces-f0", name: "Cycle parking — A&E (6 spaces)", type: "other", coordinates: { lat: 51.579433, lng: 0.002902 }, floor: 0 },
    { id: "cycle-parking-hospital-road-18-spaces-f0", name: "Cycle parking — Hospital road (18 spaces)", type: "other", coordinates: { lat: 51.578393, lng: 0.004107 }, floor: 0 },
    { id: "cycle-parking-eye-treatment-centre-8-spaces-f0", name: "Cycle parking — Eye Treatment Centre (8 spaces)", type: "other", coordinates: { lat: 51.578427, lng: 0.003176 }, floor: 0 },
    { id: "cycle-parking-childrens-outpatients-12-spaces-f0", name: "Cycle parking — Children's Outpatients (12 spaces)", type: "other", coordinates: { lat: 51.57829, lng: 0.003723 }, floor: 0 },
  ],
}
