import { Venue } from "../types"

// Wythenshawe Hospital — reconstructed from the trust's own site map sheet
// (map/wythenshawe-hospital-sitemap-updated-logo.pdf). Generated by scripts/maps/build-venues.mjs — edit that, not this.

export const WYTHENSHAWE_VENUE: Venue = {
  id: "wythenshawe-hospital",
  slug: "wythenshawe",
  name: "Wythenshawe Hospital",
  subtitle: "Manchester University NHS FT · Southmoor Road, Wythenshawe, Manchester M23 9LT",
  category: "hospital",
  center: { lat: 53.38757, lng: -2.29174 },
  defaultZoom: 17,
  visibility: "public",
  verified: false,
  accessibility: { stepFreeRoute: true, accessibleToilets: true, notes: "Colour-zoned campus (purple, green, blue, yellow, orange) with numbered entrances; specialist heart, lung and cystic-fibrosis centres." },
  quickAccess: ["Main Entrance", "Acute Block", "North West Heart Centre", "Treatment & Diagnostic Centre", "Education & Research Centre"],
  floorPlans: [
    { id: "f0", floor: 0, label: "Ground Floor", imageUrl: "/floorplans/wythenshawe/sitemap.svg", bounds: [[53.385368, -2.297012], [53.388864, -2.286468]] },
  ],
  waypoints: [
    { id: "pain-clinic-f0", name: "Pain Clinic", type: "department", coordinates: { lat: 53.388228, lng: -2.292671 }, floor: 0 },
    { id: "baguley-suite-f0", name: "Baguley Suite", type: "department", coordinates: { lat: 53.388099, lng: -2.292156 }, floor: 0 },
    { id: "maternity-unit-f0", name: "Maternity Unit", type: "department", coordinates: { lat: 53.388104, lng: -2.291115 }, floor: 0 },
    { id: "medical-illustration-f0", name: "Medical Illustration", type: "other", coordinates: { lat: 53.38794, lng: -2.292007 }, floor: 0 },
    { id: "children-s-department-f0", name: "Children s Department", type: "department", coordinates: { lat: 53.387931, lng: -2.289202 }, floor: 0 },
    { id: "education-research-centre-f0", name: "Education Research Centre", type: "department", coordinates: { lat: 53.387805, lng: -2.291996 }, floor: 0 },
    { id: "admissions-lounge-first-floor-f0", name: "Admissions Lounge (first floor)", type: "department", coordinates: { lat: 53.387773, lng: -2.289999 }, floor: 0 },
    { id: "acute-block-f0", name: "Acute Block", type: "department", coordinates: { lat: 53.387737, lng: -2.293073 }, floor: 0 },
    { id: "transplant-unit-f0", name: "Transplant Unit", type: "department", coordinates: { lat: 53.387713, lng: -2.289189 }, floor: 0 },
    { id: "treatment-diagnostic-centre-f0", name: "Treatment & Diagnostic Centre", type: "department", coordinates: { lat: 53.387507, lng: -2.290618 }, floor: 0 },
    { id: "north-west-heart-centre-f0", name: "North West Heart Centre", type: "department", coordinates: { lat: 53.387508, lng: -2.289067 }, floor: 0 },
    { id: "outpatients-first-floor-f0", name: "Outpatients (first floor)", type: "department", coordinates: { lat: 53.387385, lng: -2.290622 }, floor: 0 },
    { id: "accident-emergency-entrance-f0", name: "Accident & Emergency Entrance", type: "exit", coordinates: { lat: 53.387288, lng: -2.293845 }, floor: 0 },
    { id: "entrance-3-main-entrance-f0", name: "Entrance 3 Main Entrance", type: "exit", coordinates: { lat: 53.387267, lng: -2.292245 }, floor: 0 },
    { id: "manchester-cystic-fibrosis-centre-f0", name: "Manchester Cystic Fibrosis Centre", type: "department", coordinates: { lat: 53.387151, lng: -2.290847 }, floor: 0 },
    { id: "entrance-5-outpatients-f0", name: "Entrance 5 Outpatients", type: "exit", coordinates: { lat: 53.387146, lng: -2.290098 }, floor: 0 },
    { id: "north-west-lung-research-centre-f0", name: "North West Lung Research Centre", type: "department", coordinates: { lat: 53.387115, lng: -2.29152 }, floor: 0 },
    { id: "outpatients-car-park-f0", name: "Outpatients Car Park", type: "other", coordinates: { lat: 53.386965, lng: -2.289961 }, floor: 0 },
    { id: "clinical-sciences-building-f0", name: "Clinical Sciences Building", type: "department", coordinates: { lat: 53.386928, lng: -2.288568 }, floor: 0 },
    { id: "medicines-evaluation-unit-f0", name: "Medicines Evaluation Unit", type: "department", coordinates: { lat: 53.386841, lng: -2.291583 }, floor: 0 },
    { id: "clinical-research-centre-f0", name: "Clinical Research Centre", type: "department", coordinates: { lat: 53.386841, lng: -2.291136 }, floor: 0 },
    { id: "nightingale-centre-f0", name: "Nightingale Centre", type: "department", coordinates: { lat: 53.386487, lng: -2.293088 }, floor: 0 },
  ],
}
