#!/usr/bin/env python3
# Generates five venue modules from each hospital's own published map sheet —
# every sheet is a different design, and each venue reproduces its sheet's way
# of working rather than forcing one template:
#
#   barts.ts    St Bartholomew's Hospital (Barts Health) — "Getting around the
#               hospital site": building-code zones (KGV, K&L, SW, EW, WW, GW,
#               RBC, NW, MA) + a Clinical Services / Wards / Other Services
#               directory. Directory entries sit on their wing: KGV (the big
#               building, dozens of entries) is pixel-sampled like QEH/UHL;
#               the small wings anchor at their label; lettered spots (A-F)
#               anchor exactly.
#   st-marys.ts St Mary's Hospital, Paddington (Imperial) — a clean site map
#               with buildings labelled in place; each label becomes a
#               waypoint at its true position.
#   rlh.ts      The Royal London Hospital — the trust's cycle-parking map:
#               numbered buildings (legend), lettered main-building entrances,
#               and cycle parking. NOTE: the sheet is drawn SOUTH-UP (its own
#               compass points N downward); kept as designed.
#   nuh.ts      Newham University Hospital — "Welcome" sheet with a full
#               Department/Floor/Zone directory where zones are NUMBERED
#               points (1-12) along the main building; every directory row is
#               placed at its zone circle, plus entrances, outbuildings and
#               cycle parking.
#   meh.ts      Mile End Hospital — numbered-block site plan; each block's
#               "Building Contents" becomes waypoints at the block's marker
#               (demolished/removed blocks skipped), plus cycle parking.
#
# Positions of raster-map markers (RLH/NUH/MEH) were read off the sheets at
# high zoom; like St George's, positions are faithful to the sheet, and pin
# placement within a building is illustrative.
#
# Run with: python3 scripts/sheets/generate-batch2.py
# (rewrites src/lib/venues/{barts,st-marys,rlh,nuh,meh}.ts)

import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.join(HERE, "..", "..")

FLOOR_LABELS = {0: "Ground Floor", 1: "First Floor", 2: "Second Floor", 3: "Third Floor"}


def slugify(s):
    s = s.lower().replace("’", "").replace("'", "")
    return re.sub(r"[^a-z0-9]+", "-", s).strip("-") or "wp"


def wtype(name):
    n = name.lower()
    if "entrance" in n or "gate" in n:
        return "exit"
    if "pharmac" in n:
        return "pharmacy"
    if "restaurant" in n or "café" in n or "cafe" in n:
        return "canteen"
    if "reception" in n:
        return "reception"
    if "toilet" in n:
        return "toilet"
    if re.search(r"\bward\b|\bwards\b", n) or "unit (acu)" in n or "(hdu)" in n or "(icu)" in n:
        return "ward"
    if any(k in n for k in ("clinic", "imaging", "x-ray", "theatre", "outpatient", "department",
                            "centre", "unit", "suite", "medicine", "radiotherapy", "phlebotomy",
                            "pathology", "therapy", "therapies", "office", "services", "reception",
                            "lab", "hospital", "wing", "building")):
        return "department"
    return "other"


def emit(cfg, wps, outfile):
    (latS, lngW), (latN, lngE) = cfg["bounds"]
    L = []
    A = L.append
    A('import { Venue } from "../types"')
    A("")
    for line in cfg["comment"]:
        A(f"// {line}")
    A("// Generated by scripts/sheets/generate-batch2.py — edit that, not this.")
    A("")
    A(f"export const {cfg['const']}: Venue = {{")
    A(f'  id: "{cfg["id"]}",')
    A(f'  slug: "{cfg["slug"]}",')
    A(f'  name: "{cfg["name"]}",')
    A(f'  subtitle: "{cfg["subtitle"]}",')
    A('  category: "hospital",')
    A(f"  center: {{ lat: {cfg['center'][0]}, lng: {cfg['center'][1]} }},")
    A("  defaultZoom: 17,")
    A('  visibility: "public",')
    A("  verified: false,")
    if cfg.get("accessibility"):
        A(f"  accessibility: {{ stepFreeRoute: true, accessibleToilets: true, notes: \"{cfg['accessibility']}\" }},")
    A("  quickAccess: [" + ", ".join(f'"{q}"' for q in cfg["quick"]) + "],")
    A("  floorPlans: [")
    for f in cfg["floors"]:
        A(f'    {{ id: "f{f}", floor: {f}, label: "{FLOOR_LABELS[f]}", imageUrl: "{cfg["plan"]}", '
          f"bounds: [[{latS}, {lngW}], [{latN}, {lngE}]] }},")
    A("  ],")
    A("  waypoints: [")
    used = {}
    group = None
    for w in wps:
        if w.get("group") and w["group"] != group:
            group = w["group"]
            A(f"    // ── {group} " + "─" * max(1, 66 - len(group)))
        base = f"{slugify(w['name'])}-f{w.get('floor', 0)}"
        n = used.get(base, 0)
        used[base] = n + 1
        wid = base if n == 0 else f"{base}-{n + 1}"
        x, y = w["pos"]
        lat = round(latN - y * (latN - latS), 6)
        lng = round(lngW + x * (lngE - lngW), 6)
        name = w["name"].replace('"', '\\"')
        desc = (w.get("desc") or "").replace('"', '\\"')
        dpart = f', description: "{desc}"' if desc else ""
        A(f'    {{ id: "{wid}", name: "{name}", type: "{w.get("type") or wtype(w["name"])}", '
          f'coordinates: {{ lat: {lat}, lng: {lng} }}, floor: {w.get("floor", 0)}{dpart} }},')
    A("  ],")
    A("}")
    A("")
    open(outfile, "w").write("\n".join(L))
    print(f"wrote {os.path.relpath(outfile, REPO)} ({len(wps)} waypoints)")


# ══ St Bartholomew's ══════════════════════════════════════════════════════════
# Sheet crop (PDF pts): (30,120)-(758,830); normalise into that frame.
def bx(x, y):
    return ((x - 30) / 728, (y - 120) / 710)

# Wing anchor points (the wing's label on the sheet) and lettered spots.
B_ANCHOR = {
    "K&L": bx(348, 262), "EW": bx(452, 415), "WW": bx(300, 570), "SW": bx(180, 460),
    "GW": bx(120, 655), "RBC": bx(230, 618), "NW": bx(283, 428), "MA": bx(357, 345),
    "KGV": bx(500, 600),
    "A": bx(335, 259), "B": bx(384, 307), "C": bx(394, 198), "D": bx(337, 379),
    "E": bx(366, 687), "F": bx(506, 544), "i": bx(655, 752),
}
# Directory: (name, wing-code, anchor-letter-or-None, group)
B_DIR = [
    ("Breast Unit Diagnostic Imaging", "WW", None), ("Bronchoscopy", "KGV", None),
    ("Cardiac Imaging", "KGV", None), ("Centre for Reproductive Medicine", "K&L", "C"),
    ("Clinic 1", "KGV", None), ("Clinic 2", "KGV", None), ("Clinic 3", "KGV", None),
    ("Clinic 4", "KGV", None), ("Clinic 5", "KGV", None), ("Clinic 6", "EW", None),
    ("Clinic 7", "K&L", "C"), ("Clinic 8", "EW", None), ("Clinical Psychology", "K&L", "B"),
    ("Giltspur Wing Clinics", "GW", None), ("Imaging (CT, MRI, X-ray)", "KGV", None),
    ("Imaging (CT, MRI)", "SW", None), ("Lung Function", "KGV", None),
    ("Minor Injuries", "K&L", "B"), ("Nuclear Medicine", "KGV", None),
    ("PET Centre", "EW", None), ("Radiotherapy", "KGV", None),
    ("Rehabilitation Unit", "K&L", "A"), ("Theatres (KGV)", "KGV", None),
    ("Theatres (SW)", "SW", None), ("Vascular Lab", "KGV", None),
    ("West Wing Clinics", "WW", None),
]
B_WARDS = [("Percival Pott Ward", "EW", None)] + [
    (f"Ward {w}", "KGV", None)
    for w in ["1C", "1D", "1E", "3A East", "3A West", "3C", "3D", "4A", "4B", "4C", "4D", "4E",
              "5A", "5B", "5C", "5D", "5E", "6A", "6C", "6D", "6D Annex", "7A"]
] + [("SW Ward 01", "SW", None), ("SW Ward 02", "SW", None)]
B_OTHER = [
    ("Bereavement and Medical Examiner's Office", "WW", None),
    ("Botley Scott Rooms (hostel)", "EW", None), ("Maggie's Centre, Barts", "MA", None),
    ("Macmillan Information Centre", "WW", None), ("Archives", "K&L", "C"),
    ("Main Reception", "KGV", "i"), ("Phlebotomy (blood tests)", "KGV", None),
    ("Cafe and Restaurant", "KGV", "F"), ("Patient Transport Lounge", "KGV", "E"),
    ("Robin Brook Centre", "RBC", None), ("Museum", "NW", "D"),
]

def barts_wps():
    wps = []
    # Spread same-wing entries in a small grid around the wing anchor; KGV, with
    # dozens of entries, fans across the whole building's two blocks instead.
    kgv_cells = []
    for i in range(40):
        col, row = i % 8, i // 8
        # two KGV blocks: NE block (x 540-720, y 480-620) and S block (x 380-700, y 640-760)
        if row < 2:
            kgv_cells.append(bx(548 + col * 24, 500 + row * 55))
        else:
            kgv_cells.append(bx(395 + col * 40, 650 + (row - 2) * 45))
    kgv_i = 0
    seen_per_wing = {}
    for group, rows in (("Clinical Services", B_DIR), ("Wards", B_WARDS), ("Other Services", B_OTHER)):
        for name, wing, letter in rows:
            if letter:
                pos = B_ANCHOR[letter]
            elif wing == "KGV":
                pos = kgv_cells[kgv_i % len(kgv_cells)]
                kgv_i += 1
            else:
                k = seen_per_wing.get(wing, 0)
                seen_per_wing[wing] = k + 1
                ax, ay = B_ANCHOR[wing]
                pos = (ax + (k % 3) * 0.022 - 0.022, ay + (k // 3) * 0.02)
            wps.append({"name": name, "pos": pos, "desc": f"{wing} — {group}", "group": group,
                        "type": "ward" if group == "Wards" else None})
    wps += [
        {"name": "King Henry VIII Gate (from Giltspur St / West Smithfield)", "type": "exit", "pos": bx(330, 300), "group": "Entrances"},
        {"name": "From Little Britain", "type": "exit", "pos": bx(660, 205), "group": "Entrances"},
        {"name": "From King Edward Street (Main Reception)", "type": "exit", "pos": bx(700, 770), "group": "Entrances"},
        {"name": "From Giltspur Street", "type": "exit", "pos": bx(60, 720), "group": "Entrances"},
        {"name": "The Square", "type": "other", "pos": bx(390, 490), "group": "Entrances"},
        {"name": "Cafe (North-East corner)", "type": "canteen", "pos": bx(520, 315), "group": "Entrances"},
        {"name": "St Bartholomew's-the-Less", "type": "other", "pos": bx(262, 315), "group": "Entrances"},
        {"name": "Pet CT Scanner (mobile)", "type": "department", "pos": bx(322, 750), "group": "Entrances"},
    ]
    return wps


BARTS = {
    "const": "BARTS_VENUE", "id": "st-bartholomews", "slug": "st-bartholomews",
    "name": "St Bartholomew's Hospital",
    "subtitle": "Barts Health NHS Trust · West Smithfield, London EC1A 7BE",
    "center": (51.51775, -0.10039),
    "bounds": ((51.516436, -0.102555), (51.519064, -0.098225)),
    "floors": [0], "plan": "/floorplans/barts/sitemap.svg",
    "quick": ["Main Reception", "Minor Injuries", "Cafe and Restaurant", "Phlebotomy (blood tests)", "Maggie's Centre, Barts"],
    "accessibility": "Disabled access via all entrances; on-site Blue Badge parking. Main reception at the King Edward Street entrance.",
    "comment": [
        "St Bartholomew's Hospital — Barts Health NHS Trust. The floor plan is the",
        "trust's own 'Getting around the hospital site' sheet (building-code zones:",
        "KGV, K&L, SW, EW, WW, GW, RBC, NW, MA). Waypoints are the sheet's full",
        "directory; lettered spots (A-F, i) sit at their exact marks, KGV entries",
        "fan across the KGV building, and other wings' entries sit at their wing.",
        "The sheet gives no floor numbers, so everything is floor 0.",
    ],
}

# ══ St Mary's, Paddington ═════════════════════════════════════════════════════
def sx(x, y):
    return (x / 612, (y - 115) / 500)

SMH_WPS = [
    {"name": "Queen Elizabeth the Queen Mother Building (Main Reception)", "type": "reception", "pos": sx(297, 350)},
    {"name": "A&E", "type": "department", "pos": sx(231, 292), "desc": "Emergency Department"},
    {"name": "Urgent Treatment Centre", "type": "department", "pos": sx(385, 366)},
    {"name": "Main Outpatients", "type": "department", "pos": sx(131, 460)},
    {"name": "Fracture Clinic", "type": "department", "pos": sx(455, 512)},
    {"name": "Lindo Wing", "type": "department", "pos": sx(243, 417)},
    {"name": "Paterson Building", "type": "department", "pos": sx(123, 243)},
    {"name": "Jefferiss Wing", "type": "department", "pos": sx(144, 509)},
    {"name": "Mary Stanford Building", "type": "department", "pos": sx(200, 441)},
    {"name": "Cambridge Wing", "type": "ward", "pos": sx(258, 487)},
    {"name": "Clarence Wing", "type": "ward", "pos": sx(245, 554)},
    {"name": "Albert Ward", "type": "ward", "pos": sx(509, 554)},
    {"name": "Salton House", "type": "other", "pos": sx(454, 538)},
    {"name": "Winston Churchill Wing", "type": "other", "pos": sx(139, 567)},
    {"name": "Dumbell House", "type": "other", "pos": sx(563, 568)},
    {"name": "Mint Wing", "type": "department", "pos": sx(56, 357)},
    {"name": "Mint Wing (South)", "type": "department", "pos": sx(114, 402)},
    {"name": "The Bays", "type": "other", "pos": sx(72, 185)},
    {"name": "Mortuary", "type": "other", "pos": sx(516, 447)},
    {"name": "Imperial College Medical School", "type": "other", "pos": sx(375, 519)},
]

SMH = {
    "const": "ST_MARYS_VENUE", "id": "st-marys-paddington", "slug": "st-marys-paddington",
    "name": "St Mary's Hospital, Paddington",
    "subtitle": "Imperial College Healthcare NHS Trust · Praed Street, London W2 1NY",
    "center": (51.516972, -0.173555),
    "bounds": ((51.515321, -0.176802), (51.518623, -0.170308)),
    "floors": [0], "plan": "/floorplans/smh/sitemap.svg",
    "quick": ["Queen Elizabeth the Queen Mother Building (Main Reception)", "A&E", "Urgent Treatment Centre", "Main Outpatients", "Lindo Wing"],
    "accessibility": "Step-free routes shown on the trust's site map; nearest step-free stations at Paddington.",
    "comment": [
        "St Mary's Hospital, Paddington — Imperial College Healthcare NHS Trust.",
        "The floor plan is the trust's own site map sheet (February 2024 update);",
        "every building label on the sheet is a waypoint at its printed position.",
    ],
}

# ══ The Royal London Hospital (cycle map) ═════════════════════════════════════
# Sheet is drawn SOUTH-UP (its compass points N downward) — kept as designed.
def rx(x, y):
    return (x / 574, y / 721)

RLH_WPS = [
    {"name": "Main Building", "type": "department", "pos": rx(150, 345), "group": "Buildings"},
    {"name": "Main Building (South)", "type": "department", "pos": rx(185, 431), "group": "Buildings"},
    {"name": "Grahame Hayton Unit", "type": "department", "pos": rx(404, 470), "desc": "Building 1", "group": "Buildings"},
    {"name": "Ambrose King Centre", "type": "department", "pos": rx(404, 484), "desc": "Building 2", "group": "Buildings"},
    {"name": "Outpatients Department", "type": "department", "pos": rx(437, 425), "desc": "Building 3", "group": "Buildings"},
    {"name": "Outpatients Annexe", "type": "department", "pos": rx(465, 458), "desc": "Building 4", "group": "Buildings"},
    {"name": "Museum", "type": "other", "pos": rx(331, 340), "desc": "Building 5", "group": "Buildings"},
    {"name": "Dental Hospital", "type": "department", "pos": rx(452, 353), "desc": "Building 6", "group": "Buildings"},
    {"name": "Mortuary Service", "type": "other", "pos": rx(123, 272), "desc": "Building 7", "group": "Buildings"},
    {"name": "East London Counselling Services", "type": "department", "pos": rx(262, 268), "desc": "Building 8", "group": "Buildings"},
    {"name": "Health and Wellness Centre", "type": "department", "pos": rx(315, 264), "desc": "Building 9", "group": "Buildings"},
    {"name": "Smokers Clinic", "type": "department", "pos": rx(258, 194), "desc": "Building 10", "group": "Buildings"},
    {"name": "Weight Clinic", "type": "department", "pos": rx(266, 199), "desc": "Building 10", "group": "Buildings"},
    {"name": "James Hora Home", "type": "other", "pos": rx(315, 212), "desc": "Building 11", "group": "Buildings"},
    {"name": "Emergency Entrance", "type": "exit", "pos": rx(158, 463), "desc": "Main Building entrance A", "group": "Entrances"},
    {"name": "Main Entrance", "type": "exit", "pos": rx(178, 463), "desc": "Main Building entrance B", "group": "Entrances"},
    {"name": "Stepney Way Entrance", "type": "exit", "pos": rx(240, 424), "desc": "Main Building entrance C", "group": "Entrances"},
    {"name": "Luckes Entrance", "type": "exit", "pos": rx(135, 372), "desc": "Main Building entrance D", "group": "Entrances"},
    {"name": "Clinics 2 and 3 Entrance", "type": "exit", "pos": rx(194, 355), "desc": "Main Building entrance E", "group": "Entrances"},
    {"name": "Drop Off (Blue Badge)", "type": "other", "pos": rx(204, 399), "group": "Entrances"},
    {"name": "Cycle parking — Varden Street", "type": "other", "pos": rx(261, 157), "group": "Cycle parking"},
    {"name": "Cycle parking — Clinics 2 & 3", "type": "other", "pos": rx(206, 341), "group": "Cycle parking"},
    {"name": "Cycle parking — Stepney Way", "type": "other", "pos": rx(250, 456), "group": "Cycle parking"},
    {"name": "Cycle parking — Cavell Street", "type": "other", "pos": rx(94, 380), "group": "Cycle parking"},
    {"name": "Cycle parking — Mount Terrace", "type": "other", "pos": rx(472, 538), "group": "Cycle parking"},
    {"name": "Cycle parking — Newark Street", "type": "other", "pos": rx(455, 318), "group": "Cycle parking"},
]

RLH = {
    "const": "RLH_VENUE", "id": "royal-london", "slug": "royal-london-hospital",
    "name": "The Royal London Hospital",
    "subtitle": "Barts Health NHS Trust · Whitechapel Road, London E1 1BB",
    "center": (51.51886, -0.05913),
    "bounds": ((51.516479, -0.062176), (51.521241, -0.056084)),
    "floors": [0], "plan": "/floorplans/rlh/sitemap.png",
    "quick": ["Main Entrance", "Emergency Entrance", "Outpatients Department", "Dental Hospital"],
    "accessibility": "Blue Badge drop-off by the main entrances; step-free entrances marked on the sheet.",
    "comment": [
        "The Royal London Hospital, Whitechapel — Barts Health NHS Trust. The floor",
        "plan is the trust's cycle-parking site map: numbered buildings, lettered",
        "main-building entrances (A-E) and cycle parking, all at the sheet's marked",
        "positions. NOTE: the sheet is drawn SOUTH-UP (its compass points N down);",
        "kept in the designed orientation like the other trust sheets.",
    ],
}

# ══ Newham University Hospital ════════════════════════════════════════════════
def nx(x, y):
    return (x / 1249, y / 834)

# Zone circles 1-12 along the main building spine (read off the sheet).
NUH_Z = {
    1: (745, 228), 2: (699, 212), 3: (663, 207), 4: (632, 199), 5: (600, 189), 6: (566, 183),
    7: (531, 178), 8: (497, 172), 9: (466, 166), 10: (443, 159), 11: (417, 154), 12: (392, 149),
}
# Directory: (name, floor, zone). floor -1 == "External access only" -> 0.
NUH_DEPTS = [
    ("Ante Natal Clinic", 0, 12), ("Baby Change Facilities", 0, 1), ("Baby Change Facilities", 1, 4),
    ("Baby Change Facilities", 0, 6), ("Bilingual Health Advocacy Service", 0, 12), ("Birthing Centre", 1, 2),
    ("Café Health Central", 0, 6), ("Cash Machine", 0, 1), ("Cash Machine", 0, 10),
    ("Change Machine (for Parking)", 0, 1), ("Chemotherapy Day Unit", 1, 10),
    ("Clinical Measurement (Foxglove)", 0, 9), ("Clinical Site Managers", 1, 6),
    ("Canning Town Unit (Staff Areas)", 1, 12), ("Delivery Suite", 1, 4),
    ("Dermatology (West Wing Centre)", 0, None), ("Dietitians (West Wing Centre)", 0, None),
    ("Discharge Lounge", 1, 10), ("Early Pregnancy Assessment Unit (EPAU)", 1, 10),
    ("Education Centre", 0, 2), ("Emergency Department", 0, 10),
    ("Emergency Gynaecology Assessment Service (EGAS)", 1, 10), ("Estates Department", 0, 5),
    ("Fetal Medicine Unit (FMU)", 0, 4), ("Foxglove (Clinical Measurement)", 0, 9),
    ("General Office", 0, 6), ("GP Services", 0, None), ("Greenway Centre", 0, None),
    ("Gynaecology (West Wing Centre)", 0, None), ("Health Central (Outpatients)", 0, 6),
    ("Health Central Day Care (Jasmine Ward)", 1, 6), ("Health Central Operating Theatres", 1, 6),
    ("Library", 1, 2), ("Macmillan Info and Support Centre", 0, 1),
    ("Main Reception St Andrews Wing", 0, 1), ("Main Theatres & Anaesthesia", 1, 8),
    ("Maternity Assessment Unit (MAU)", 0, 4), ("Maternity Emergencies", 1, 4),
    ("Neonatal Unit", 1, 2), ("Nostalgia Room", 0, 1), ("Occupational Health Department", 0, 12),
    ("Occupational Therapy", 0, 1), ("Orthopaedics Office", 1, 11), ("PALS Office", 0, 1),
    ("Pathology Department", 0, 3), ("Patient Transport Service", 0, 6), ("Pharmacy", 0, 4),
    ("Pine Therapies", 0, 1), ("Podiatry Office", 1, 11), ("Prayer and Quiet Room", 1, 12),
    ("Restaurant", 1, 4), ("Social Work Team", 1, 5), ("St Andrews Wing", 0, 1),
    ("Stroke Unit (Heather Ward)", 0, 1), ("The Ark Children's Outpatients Dept", 0, None),
    ("Toilets", 0, 1), ("Toilets", 0, 12), ("Toilets", 1, 4), ("Urgent Care Centre (UCC)", 0, None),
    ("Voluntary Services", 0, 1), ("Women's & Paediatric Clinic", 0, 12),
    ("X-Ray, Imaging and Radiology", 0, 8),
]
NUH_WARDS = [
    ("Acute Care Unit (ACU)", 0, 8), ("Beckton Ward", 1, 12), ("Critical Care Unit", 1, 10),
    ("East Ham Ward", 1, 10), ("Forest Ward", 1, 10), ("Heather Ward (Stroke Unit)", 0, 1),
    ("High Dependency Unit (HDU)", 1, 10), ("Intensive Care Unit (ICU)", 1, 10),
    ("Jasmine Ward", 1, 6), ("Larch Ward (Antenatal/Postnatal)", 0, 2),
    ("Observation Ward", 0, 10), ("Plashet Ward", 1, 12), ("Rainbow Ward", 0, 10),
    ("Silvertown Ward", 1, 8), ("Stratford Ward", 1, 8), ("Tayberry Ward", 1, 1),
    ("Thistle Ward", 1, 1), ("West Ham Ward", 1, 10),
]
NUH_GARDENS = [
    ("Japanese Garden", 0, 7), ("Moorish Garden", 0, 5), ("Healing Garden", 0, 3),
    ("Therapies Garden", 0, 1), ("Globe Garden (via St Andrews Wing)", 0, 1),
]
NUH_GATEWAY = [  # (name, floor) — all in the Gateway Surgical Centre building
    ("Breast Unit", 0), ("Gateway Clinics", 0), ("Clove Daycare", 3), ("Colposcopy", 3),
    ("Fracture Clinic", 0), ("Gateway Main Reception", 0), ("Maple Ward", 2),
    ("Newham Renal Unit", 1), ("Gateway Prayer and Quiet Room", 3), ("Gateway Theatres", 3),
    ("The Café (Gateway)", 0), ("Gateway Toilets", 0), ("Gateway X-Ray", 0),
]
# "External access only" entries anchor near the relevant entrance instead.
NUH_EXT = {
    "Dermatology (West Wing Centre)": (198, 225), "Dietitians (West Wing Centre)": (202, 232),
    "GP Services": (335, 182), "Greenway Centre": (240, 185),
    "Gynaecology (West Wing Centre)": (194, 218), "The Ark Children's Outpatients Dept": (556, 140),
    "Urgent Care Centre (UCC)": (327, 175),
}

def nuh_wps():
    wps = []
    zcount = {}
    for group, rows in (("Departments", NUH_DEPTS), ("Wards", NUH_WARDS), ("Gardens", NUH_GARDENS)):
        for name, floor, zone in rows:
            if name in NUH_EXT:
                pos = nx(*NUH_EXT[name])
                desc = "External access — see entrance"
            elif zone:
                k = zcount.get(zone, 0)
                zcount[zone] = k + 1
                zxp, zyp = NUH_Z[zone]
                pos = nx(zxp + (k % 3) * 16 - 16, zyp + (k // 3) * 13 + 14)
                desc = f"Zone {zone}"
            else:
                pos = nx(443, 175)
                desc = None
            wps.append({"name": name, "floor": floor, "pos": pos, "desc": desc, "group": group,
                        "type": "ward" if group == "Wards" else ("other" if group == "Gardens" else None)})
    for i, (name, floor) in enumerate(NUH_GATEWAY):
        pos = nx(1060 + (i % 4) * 28, 690 + (i // 4) * 24)
        wps.append({"name": name, "floor": floor, "pos": pos, "desc": "Gateway Surgical Centre", "group": "Gateway Surgical Centre"})
    wps += [
        {"name": "Main Hospital Entrance", "type": "exit", "pos": nx(935, 318), "group": "Entrances & buildings"},
        {"name": "Emergency Dept, Urgent Care Centre & GP Services Entrance", "type": "exit", "pos": nx(330, 178), "group": "Entrances & buildings"},
        {"name": "West Entrance", "type": "exit", "pos": nx(363, 160), "group": "Entrances & buildings"},
        {"name": "Greenway Centre and Executive Offices Entrance", "type": "exit", "pos": nx(240, 180), "group": "Entrances & buildings"},
        {"name": "West Wing Centre Entrance", "type": "exit", "pos": nx(198, 215), "group": "Entrances & buildings"},
        {"name": "Maternity (Out of Hours) Entrance", "type": "exit", "pos": nx(722, 268), "group": "Entrances & buildings"},
        {"name": "Gateway Surgical Centre Entrance", "type": "exit", "pos": nx(975, 762), "group": "Entrances & buildings"},
        {"name": "Health Central", "type": "department", "pos": nx(687, 180), "group": "Entrances & buildings"},
        {"name": "Helena House", "type": "other", "pos": nx(893, 533), "group": "Entrances & buildings"},
        {"name": "Star Lodge", "type": "other", "pos": nx(1104, 578), "group": "Entrances & buildings"},
        {"name": "Office Annex 1-5", "type": "other", "pos": nx(683, 403), "group": "Entrances & buildings"},
        {"name": "Office Annex 6-9", "type": "other", "pos": nx(657, 518), "group": "Entrances & buildings"},
        {"name": "Office Annex 10-12", "type": "other", "pos": nx(833, 547), "group": "Entrances & buildings"},
        {"name": "Office Annex 13-16", "type": "other", "pos": nx(483, 480), "group": "Entrances & buildings"},
        {"name": "Office Annex 17-19", "type": "other", "pos": nx(492, 607), "group": "Entrances & buildings"},
        {"name": "Office Annex 20-23 (House 20)", "type": "other", "pos": nx(678, 645), "group": "Entrances & buildings"},
        {"name": "East Car Park", "type": "other", "pos": nx(1030, 363), "group": "Entrances & buildings"},
        {"name": "Cycle parking — Executive Offices entrance (6 spaces)", "type": "other", "pos": nx(218, 190), "group": "Cycle parking"},
        {"name": "Cycle parking — West entrance car park (10 spaces + 28 lockers)", "type": "other", "pos": nx(370, 150), "group": "Cycle parking"},
        {"name": "Cycle parking — Maternity out-of-hours entrance (30 spaces)", "type": "other", "pos": nx(735, 255), "group": "Cycle parking"},
        {"name": "Cycle parking — Gateway Surgical Centre entrance (14 lockers)", "type": "other", "pos": nx(990, 775), "group": "Cycle parking"},
        {"name": "Cycle parking — Gateway Surgical Centre car park (8 spaces)", "type": "other", "pos": nx(940, 790), "group": "Cycle parking"},
        {"name": "Cycle parking — House 20 (10 spaces)", "type": "other", "pos": nx(668, 650), "group": "Cycle parking"},
        {"name": "Cycle parking — Helena House (8 spaces)", "type": "other", "pos": nx(885, 545), "group": "Cycle parking"},
    ]
    return wps


NUH = {
    "const": "NUH_VENUE", "id": "newham-university-hospital", "slug": "newham-university-hospital",
    "name": "Newham University Hospital",
    "subtitle": "Barts Health NHS Trust · Glen Road, Plaistow, London E13 8SL",
    "center": (51.522778, 0.034732),
    "bounds": ((51.521278, 0.031123), (51.524278, 0.038341)),
    "floors": [0, 1, 2, 3], "plan": "/floorplans/nuh/sitemap.png",
    "quick": ["Main Hospital Entrance", "Emergency Department", "Urgent Care Centre (UCC)", "Main Reception St Andrews Wing", "Pharmacy"],
    "accessibility": "Disabled parking and drop-off marked at the main entrances; pedestrian crossings marked on the welcome map.",
    "comment": [
        "Newham University Hospital — Barts Health NHS Trust. The floor plan is the",
        "trust's own 'Welcome' sheet (aerial site view + full Department/Floor/Zone",
        "directory). Zones here are NUMBERED points (1-12) along the main building,",
        "so each directory entry sits at its zone circle on the correct floor; the",
        "Gateway Surgical Centre carries its own floors (G-3). Cycle parking and",
        "entrances come from the trust's cycle-parking edition of the same sheet.",
    ],
}

# ══ Mile End Hospital ═════════════════════════════════════════════════════════
# Overlay image is cropped to the site plan: (245,55)-(709,572) of the sheet.
def mx(x, y):
    return ((x - 245) / 464, (y - 55) / 517)

MEH_BLOCKS = [  # (block no, contents, x, y) — demolished/removed blocks omitted
    (1, "THPCT Headquarters", 340, 449), (2, "Primary Care Building", 380, 494),
    (3, "Emily Graham Building", 420, 477), (4, "Alderney Building", 375, 411),
    (5, "Bancroft Unit", 310, 264), (6, "Beaumont House (SAU)", 455, 491),
    (7, "X-Ray / Theatres / Pharmacy", 397, 350),
    (8, "RHT Rheumatology / Moorfields Eye Clinic / Foot Health / Well Women", 452, 391),
    (9, "Hospital Generator Building", 520, 428), (11, "Boiler House & Estates Workshops", 545, 381),
    (12, "The Wheelchair Centre", 610, 321), (13, "Burdett House", 589, 216),
    (14, "Restaurant", 536, 158), (15, "Therapy Unit", 497, 141), (16, "Hydrotherapy Pool", 457, 126),
    (17, "Mortuary", 426, 150), (18, "Laundry Building", 355, 206),
    (19, "Physiotherapy / Hastings Ward / Public Health & Improvement", 455, 183),
    (20, "MHU — Leadenhall / Roman Ward", 526, 228),
    (21, "Catering Department / Social Services / Chapel / Community Diabetics", 417, 209),
    (22, "MHU — Globe / Brick Lane Ward", 486, 225),
    (23, "Robinson Ward / Sports Medicine / PALS", 388, 243),
    (24, "MHU — Rosebank / Millharbour / Lea Ward", 445, 295),
    (25, "Bancroft Generator Building", 280, 392), (27, "Main Corridor", 410, 282),
    (29, "GSL / Clinical Equipment / Dietitian", 497, 183),
]
MEH_CYCLE = [  # (spaces, x, y) — positions approximate to the sheet's arrows
    (20, 500, 300), (14, 560, 240), (10, 600, 320), (14, 610, 215), (6, 525, 420),
    (10, 445, 500), (4, 395, 505), (4, 430, 455), (8, 330, 430), (6, 355, 465),
]

def meh_wps():
    wps = []
    for no, contents, x, y in MEH_BLOCKS:
        t = "canteen" if contents == "Restaurant" else ("ward" if "Ward" in contents and "MHU" in contents else None)
        wps.append({"name": contents, "pos": mx(x, y), "desc": f"Block {no}", "group": "Buildings", "type": t})
    for spaces, x, y in MEH_CYCLE:
        wps.append({"name": f"Cycle parking ({spaces} spaces)", "type": "other", "pos": mx(x, y), "group": "Cycle parking"})
    return wps


MEH = {
    "const": "MEH_VENUE", "id": "mile-end-hospital", "slug": "mile-end-hospital",
    "name": "Mile End Hospital",
    "subtitle": "Barts Health NHS Trust · Bancroft Road, London E1 4DG",
    "center": (51.525047, -0.042192),
    "bounds": ((51.52343, -0.044524), (51.526664, -0.03986)),
    "floors": [0], "plan": "/floorplans/meh/sitemap.png",
    "quick": ["X-Ray / Theatres / Pharmacy", "Restaurant", "Therapy Unit", "Robinson Ward / Sports Medicine / PALS"],
    "accessibility": "Level site with marked pedestrian routes between blocks.",
    "comment": [
        "Mile End Hospital — Barts Health NHS Trust. The floor plan is the trust's",
        "numbered-block site plan (from its cycle-parking sheet); each block's",
        "'Building Contents' entry is a waypoint at the block's marker. Demolished",
        "or removed blocks (10, 26, 28) are omitted. Cycle-parking positions are",
        "approximate to the sheet's photo arrows.",
    ],
}

for cfg, wps, fname in (
    (BARTS, barts_wps(), "barts.ts"),
    (SMH, SMH_WPS, "st-marys.ts"),
    (RLH, RLH_WPS, "rlh.ts"),
    (NUH, nuh_wps(), "nuh.ts"),
    (MEH, meh_wps(), "meh.ts"),
):
    emit(cfg, wps, os.path.join(REPO, "src", "lib", "venues", fname))
