#!/usr/bin/env python3
# Four more hospitals from their own published maps. Each is built to its
# sheet's design; fidelity is matched to the source:
#   queens.ts   Queen's Hospital, Romford (BHRUT) — site map overlay with the
#               entrances placed exactly, and the tower wards from the sheet's
#               floor schematic grouped by floor at the tower.
#   kgh.ts      King George Hospital (BHRUT) — two real interior floor plans
#               (Ground + First) as a 2-floor venue; every labelled ward and
#               department placed at its room on the plan.
#   broomfield.ts Broomfield Hospital (Mid & South Essex) — the trust's
#               colour-zoned wayfinding map (Zones A-E, Levels 1-4). Key
#               departments placed on their zone; the sheet's code (e.g. A204 =
#               Zone A, Level 2) gives zone + floor.
#   basildon.ts Basildon & Thurrock University Hospital (Mid & South Essex) —
#               the trust's isometric site map; the buildings it labels are
#               placed at their positions.
#
# Positions are read off each sheet; within a building/zone they're
# illustrative (as with the other trust venues). Run:
#   python3 scripts/sheets/generate-batch4.py

import os, re, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.join(HERE, "..", "..")
SP = "/tmp/claude-0/-home-user-wayfinder/70a4249f-d2c9-5851-8c9e-14d91ba68624/scratchpad"

FLOOR_LABELS = {-1: "Lower Ground", 0: "Ground Floor", 1: "First Floor", 2: "Second Floor",
                3: "Third Floor", 4: "Fourth Floor", 5: "Fifth Floor"}


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower().replace("’", "").replace("'", "")).strip("-") or "wp"


def wtype(name):
    n = name.lower()
    if "entrance" in n:
        return "exit"
    if "pharmac" in n:
        return "pharmacy"
    if "restaurant" in n or "café" in n or "cafe" in n or "coffee" in n or "costa" in n:
        return "canteen"
    if "reception" in n:
        return "reception"
    if "toilet" in n:
        return "toilet"
    if re.search(r"\bward\b|\bunit\b|\bitu\b|\bicu\b|\bhdu\b|suite", n) and "outpatient" not in n and "day unit" not in n:
        return "ward"
    return "department"


def emit(cfg, wps, fname):
    (latS, lngW), (latN, lngE) = cfg["bounds"]
    L = []; A = L.append
    A('import { Venue } from "../types"')
    A("")
    for line in cfg["comment"]:
        A(f"// {line}")
    A("// Generated by scripts/sheets/generate-batch4.py — edit that, not this.")
    A("")
    A(f"export const {cfg['const']}: Venue = {{")
    A(f'  id: "{cfg["id"]}",')
    A(f'  slug: "{cfg["slug"]}",')
    A(f'  name: "{cfg["name"]}",')
    A(f'  subtitle: "{cfg["subtitle"]}",')
    A('  category: "hospital",')
    A(f"  center: {{ lat: {cfg['center'][0]}, lng: {cfg['center'][1]} }},")
    A("  defaultZoom: 17,")
    A('  visibility: "public",')
    A("  verified: false,")
    A(f'  accessibility: {{ stepFreeRoute: true, accessibleToilets: true, notes: "{cfg["access"]}" }},')
    A("  quickAccess: [" + ", ".join(f'"{q}"' for q in cfg["quick"]) + "],")
    A("  floorPlans: [")
    for f in cfg["floors"]:
        img = cfg["plan"] if isinstance(cfg["plan"], str) else cfg["plan"][f]
        A(f'    {{ id: "f{f}", floor: {f}, label: "{FLOOR_LABELS[f]}", imageUrl: "{img}", '
          f"bounds: [[{latS}, {lngW}], [{latN}, {lngE}]] }},")
    A("  ],")
    A("  waypoints: [")
    used = {}; grp = None
    for w in wps:
        if w.get("group") != grp:
            grp = w.get("group")
            if grp:
                A(f"    // ── {grp} " + "─" * max(1, 62 - len(grp)))
        base = f"{slug(w['name'])}-f{w['floor']}"
        n = used.get(base, 0); used[base] = n + 1
        wid = base if n == 0 else f"{base}-{n+1}"
        lat = round(latN - w["ny"] * (latN - latS), 6)
        lng = round(lngW + w["nx"] * (lngE - lngW), 6)
        nm = w["name"].replace('"', '\\"')
        desc = w.get("desc", "")
        dpart = f', description: "{desc}"' if desc else ""
        A(f'    {{ id: "{wid}", name: "{nm}", type: "{w.get("type") or wtype(w["name"])}", '
          f'coordinates: {{ lat: {lat}, lng: {lng} }}, floor: {w["floor"]}{dpart} }},')
    A("  ],")
    A("}")
    A("")
    open(os.path.join(REPO, "src", "lib", "venues", fname), "w").write("\n".join(L))
    print(f"wrote src/lib/venues/{fname} ({len(wps)} waypoints)")


# ══ Queen's Hospital, Romford ═════════════════════════════════════════════════
# Overlay = page-0 site map, frame 1191x905. Entrances at exact PDF positions.
def qx(x, y): return (x / 1191, y / 905)
QUEENS_ENTR = [
    ("Main Entrance", 568, 406, "exit"), ("Renal Unit Entrance", 652, 406, "exit"),
    ("Maternity Emergency Entrance", 644, 515, "exit"),
    ("Urgent and Emergency Care", 787, 514, "department"),
    ("Haematology", 1040, 367, "department"), ("Oncology", 1040, 386, "department"),
    ("Multi-storey paid parking", 444, 406, "other"),
    ("Little Explorers Creche", 258, 520, "other"),
    ("Bus Station (5, 128, 175, 193, 365, 496, 498, 499)", 700, 470, "other"),
]
# Tower wards from the floor schematic (page 1), grouped by floor, clustered at
# the tower complex (~centre-top of the site map).
QUEENS_TOWER = {
    4: ["Harvest A", "Harvest B", "Sky A", "Sky B"],
    3: ["Sunrise A", "Sunrise B", "Early Pregnancy Unit", "Coronary Care Unit",
        "Mandarin A", "Mandarin B", "Cornflower A", "Cornflower B", "Jubilee ITU"],
    2: ["Frailty Units", "Medical Receiving", "Amber A", "Amber B"],
    1: ["Ambulatory Care Unit", "Antenatal", "Sahara A", "Sahara B"],
    0: ["Sunflower Suite Outpatient Clinic", "Nuclear Medicine", "Majors", "Resus",
        "RAFTing", "SDEC", "Urgent Treatment Centre", "Discharge Lounge",
        "Medical Incident Office"],
}


def queens_wps():
    wps = []
    for n, x, y, t in QUEENS_ENTR:
        wps.append({"name": n, "nx": qx(x, y)[0], "ny": qx(x, y)[1], "floor": 0, "type": t,
                    "group": "Entrances & site"})
    tcx, tcy = 830, 415  # tower cluster centre on the site map
    for fl, wards in QUEENS_TOWER.items():
        for i, w in enumerate(wards):
            col, row = i % 3, i // 3
            x = tcx + (col - 1) * 34 + (fl - 2) * 4
            y = tcy + (row - len(wards) / 6) * 24
            wps.append({"name": w, "nx": qx(x, y)[0], "ny": qx(x, y)[1], "floor": fl,
                        "desc": f"Tower — floor {fl if fl else 'G'}", "group": "Tower wards & departments"})
    return wps


QUEENS = {
    "const": "QUEENS_VENUE", "id": "queens-hospital-romford", "slug": "queens-hospital-romford",
    "name": "Queen's Hospital, Romford",
    "subtitle": "Barking, Havering and Redbridge University Hospitals NHS Trust · Rom Valley Way, Romford RM7 0AG",
    "center": (51.569427, 0.180405),
    "bounds": ((51.567927, 0.176515), (51.570927, 0.184295)),
    "floors": [0, 1, 2, 3, 4], "plan": "/floorplans/queens/sitemap.svg",
    "quick": ["Main Entrance", "Urgent and Emergency Care", "Maternity Emergency Entrance", "Coronary Care Unit", "Multi-storey paid parking"],
    "access": "Blue Badge and drop-off bays at the main and maternity entrances; step-free routes marked on the site map. Lifts to all tower floors.",
    "comment": [
        "Queen's Hospital, Romford — Barking, Havering and Redbridge University",
        "Hospitals NHS Trust. The floor plan is the trust's site map; entrances sit",
        "at their exact positions and the tower wards (from the sheet's floor",
        "schematic) are grouped by floor at the tower. A curated set — extend via",
        "the in-app plan importer.",
    ],
}


# ══ King George Hospital ══════════════════════════════════════════════════════
# Two interior floor plans, native ~2480x2030. kx normalises to that frame.
def kx(x, y): return (x / 2480, y / 2030)
KGH_GROUND = [
    ("The Elm Breast Care Centre", 186, 267), ("Erica Ward", 372, 254), ("Dahlia Ward", 657, 254),
    ("X-Ray (Radiology) & Ultrasound", 911, 260), ("Theatres", 1327, 254), ("Cedar Centre", 1507, 254),
    ("SDEC / Clover Ward", 1724, 260), ("Medical Secretariat", 2120, 236), ("Chest Clinic", 2300, 254),
    ("PALS", 1342, 453), ("Discharge Lounge", 469, 626), ("MRI Scanner", 688, 626),
    ("Antenatal", 279, 732), ("Blood Tests", 434, 794), ("Emergency Department", 1023, 818),
    ("Urgent Treatment Centre", 1494, 641), ("Fracture Clinic", 1479, 690), ("Medical Offices", 1817, 624),
    ("Beech Ward", 2145, 555), ("Outpatient Departments", 1510, 810), ("Main Entrance", 1358, 880),
    ("Medical Receiving Unit (MRU)", 2164, 779), ("Practice Plus", 833, 1116), ("Ash Ward", 2139, 1107),
    ("Rehabilitation / Speech Therapy", 1786, 1190), ("Rheumatology / Physiotherapy / Occupational Therapy", 1808, 1290),
    ("Renal Unit", 2143, 1324), ("Pharmacy Department", 1773, 1637), ("Post Room & Porters Stores", 2158, 1637),
    ("Catering Services", 1767, 1786), ("Mortuary", 2143, 1786),
]
KGH_FIRST = [
    ("Japonica Ward", 161, 248), ("Jasmine Ward", 384, 254), ("Juniper Endoscopy", 663, 254),
    ("Theatres", 1135, 254), ("Holly Ward", 1513, 254), ("Heather Ward", 1736, 254),
    ("Stephen Curtis Cardiology & Lung Function", 2213, 254), ("Angiography Suite", 2195, 298),
    ("Laurel Unit", 159, 626), ("Maple Suite", 384, 626), ("Adult Day Care / Eye Unit", 911, 626),
    ("Iris Ward", 1116, 626), ("Intensive Therapy Unit (ITU)", 1550, 626), ("Management Suite", 1761, 626),
    ("Bereavement Office", 1953, 744), ("Gardenia Ward", 2176, 546), ("Gentian Ward", 2164, 769),
    ("Medical Secretaries", 1810, 1104), ("Foxglove Ward", 2164, 1104), ("Pathology", 1779, 1314),
    ("Fern Ward", 2133, 1314), ("Restaurant", 1779, 1637), ("Education Centre / James Fawcett Centre", 2176, 1637),
    ("Catering Services", 1773, 1786), ("Goldberg Library", 2170, 1786),
]


def kgh_wps():
    wps = []
    for n, x, y in KGH_GROUND:
        wps.append({"name": n, "nx": kx(x, y)[0], "ny": kx(x, y)[1], "floor": 0, "group": "Ground Floor"})
    for n, x, y in KGH_FIRST:
        wps.append({"name": n, "nx": kx(x, y)[0], "ny": kx(x, y)[1], "floor": 1, "group": "First Floor"})
    return wps


KGH = {
    "const": "KGH_VENUE", "id": "king-george-hospital", "slug": "king-george-hospital",
    "name": "King George Hospital",
    "subtitle": "Barking, Havering and Redbridge University Hospitals NHS Trust · Barley Lane, Goodmayes, Ilford IG3 8YB",
    "center": (51.580544, 0.112121),
    "bounds": ((51.579044, 0.10876), (51.582044, 0.115482)),
    "floors": [0, 1],
    "plan": {0: "/floorplans/kgh/ground.png", 1: "/floorplans/kgh/first.png"},
    "quick": ["Main Entrance", "Emergency Department", "Urgent Treatment Centre", "Outpatient Departments", "Theatres"],
    "access": "Level entrance from the main car park; lifts (junctions B, G, H, I) serve both floors; accessible toilets throughout.",
    "comment": [
        "King George Hospital, Goodmayes — Barking, Havering and Redbridge University",
        "Hospitals NHS Trust. The floor plans are the trust's real interior plans",
        "(Ground + First floor), each serving as that floor's map; every labelled",
        "ward and department is a waypoint at its room.",
    ],
}


# ══ Broomfield Hospital ═══════════════════════════════════════════════════════
# Overlay = wayfinding zone map (raster), frame 789x1185. Zone building centres
# read off the sheet; code like "A204" => Zone A, Level 2 (floor = 2nd char).
def bx(x, y): return (x / 842, y / 1088)
BRM_ZONE = {  # zone -> (centre x, y) on the tightened map crop (842x1088)
    "A": (120, 730), "B": (60, 340), "C": (120, 150), "D": (270, 470), "E": (470, 700),
}
BRM_ENTR = [
    ("Main Entrance", 265, 930), ("South Entrance", 195, 170), ("East Entrance", 525, 790),
    ("A&E Entrance", 45, 830), ("Central Corridor", 265, 620),
]
# Curated department list with codes (Department, code). Floor = 2nd char of code.
BRM_DIR = [
    ("A&E / Accident & Emergency", "A200"), ("Acute Medical Unit (AMU)", "A204"),
    ("Ambulatory Care Unit (ACU)", "A205"), ("Main Outpatients", "A101"), ("Audiology", "A101"),
    ("Birthing Unit", "A402"), ("Labour Ward", "A402"), ("Neonatal Unit", "A406"),
    ("Antenatal Day Assessment Unit", "A404"), ("Maternity", "A404"), ("Fracture Clinic", "A111"),
    ("Gynaecology Outpatients", "A111"), ("General Theatres", "A325"), ("Renal Unit", "A208"),
    ("Endoscopy", "A301"), ("Cardiac Centre", "A210"), ("Chemotherapy Day Unit", "A206"),
    ("Breast Unit", "A104"), ("Children's Ward", "E122"), ("Children's Outpatients", "A101"),
    ("Burns Adults' Ward", "E221"), ("Burns Children's Ward", "E225"), ("Burns ITU", "E220"),
    ("Burns Outpatients", "E224"), ("Phoenix Unit - Children's Ward", "E122"),
    ("Gosfield Ward", "A203"), ("Heybridge Ward", "A303"), ("Braxted Ward", "C254"),
    ("Baddow Ward", "C250"), ("Bardfield Ward", "C350"), ("Billericay Ward", "E321"),
    ("Writtle Ward", "C450"), ("Wizard Ward", "A301"), ("Village Room", "A407"),
    ("Radiology / X-ray Outpatients", "D140"), ("X-ray Inpatients", "B343"), ("MRI", "B342"),
    ("CT Scan", "B448"), ("Ultrasound", "B446"), ("Pathology", "D228"), ("Pharmacy Shop", "A103"),
    ("Discharge Lounge", "A204"), ("Day Stay Unit (DSU)", "B448"), ("Stroke Unit", "A302"),
    ("Emergency Department", "A200"), ("General Intensive Care Unit (GICU)", "E226"),
    ("Surgical Emergency Ward (SEW)", "B344"), ("Cardiology", "A210"), ("Diabetes Centre", "C453"),
]


def brm_wps():
    wps = []
    for n, x, y, *rest in [(e[0], e[1], e[2]) for e in BRM_ENTR]:
        wps.append({"name": n, "nx": bx(x, y)[0], "ny": bx(x, y)[1], "floor": 0, "type": "exit" if "Entrance" in n else "department",
                    "group": "Entrances"})
    zc = {}
    for name, code in BRM_DIR:
        zone = code[0]
        floor = (int(code[1]) - 1) if code[1].isdigit() else 0
        cx, cy = BRM_ZONE.get(zone, (250, 430))
        k = zc.get(zone, 0); zc[zone] = k + 1
        x = cx + (k % 4) * 24 - 36
        y = cy + (k // 4) * 20 - 30
        lvl = code[1] if code[1].isdigit() else "?"
        wps.append({"name": name, "nx": bx(x, y)[0], "ny": bx(x, y)[1], "floor": floor,
                    "desc": f"Zone {zone} · Level {lvl} ({code})", "group": f"Zone {zone}"})
    return wps


BROOMFIELD = {
    "const": "BROOMFIELD_VENUE", "id": "broomfield-hospital", "slug": "broomfield-hospital",
    "name": "Broomfield Hospital",
    "subtitle": "Mid and South Essex NHS Foundation Trust · Court Road, Broomfield, Chelmsford CM1 7ET",
    "center": (51.766262, 0.464002),
    "bounds": ((51.764762, 0.460512), (51.767762, 0.467492)),
    "floors": [0, 1, 2, 3, 4], "plan": "/floorplans/broomfield/sitemap.png",
    "quick": ["Main Entrance", "A&E / Accident & Emergency", "Main Outpatients", "Maternity", "Radiology / X-ray Outpatients"],
    "access": "Colour-coded zones (A-E) with lifts and stairs in every zone; Blue Badge parking near the Main and A&E entrances.",
    "comment": [
        "Broomfield Hospital — Mid and South Essex NHS Foundation Trust. The floor",
        "plan is the trust's colour-zoned wayfinding map (Zones A-E, Levels 1-4).",
        "Each department sits on its zone; the trust's destination code (e.g. A204",
        "= Zone A, Level 2) gives the zone and floor. A curated set from the sheet's",
        "directory — extend via the in-app plan importer.",
    ],
}


# ══ Basildon & Thurrock University Hospital ═══════════════════════════════════
# Overlay = isometric site map, frame 2610x1570. Buildings labelled on the map.
def sx(x, y): return (x / 2610, y / 1570)
BAS_BUILDINGS = [
    ("Main Entrance", 990, 900, 0, "exit"), ("Emergency Department", 1310, 800, 0, "department"),
    ("Children's Wards", 810, 490, 0, "ward"), ("Ante-Natal", 720, 570, 0, "department"),
    ("Children's Outpatients", 640, 630, 0, "department"), ("Renal Unit", 690, 760, 0, "department"),
    ("Restaurant", 970, 640, 0, "canteen"), ("X-Ray", 1470, 690, 0, "department"),
    ("Pharmacy", 1610, 680, 0, "pharmacy"), ("ENT", 1760, 690, 0, "department"),
    ("Blood Testing", 1990, 760, 0, "department"), ("Fracture Clinic", 2300, 780, 0, "department"),
    ("Physiotherapy", 2320, 860, 0, "department"), ("Breast Care Unit", 2320, 940, 0, "department"),
    ("Dermatology Unit", 2050, 1010, 0, "department"), ("Ward Block", 1720, 540, 0, "ward"),
    ("Jubilee Wing", 2080, 550, 0, "ward"), ("The Essex Cardiothoracic Centre", 1830, 340, 0, "department"),
    ("Basildon Day Unit", 1650, 490, 0, "department"), ("Day Nursery", 1220, 190, 0, "other"),
    ("Education Centre", 2560, 850, 0, "department"),
    ("Endoscopy Entrance", 1560, 940, 0, "exit"), ("Outpatients Entrance", 1830, 930, 0, "exit"),
]
# A few wards from the Level directory (Level A=0, B=1, C=2, D=3), clustered on
# the Ward Block / Jubilee Wing since the iso map doesn't place them individually.
BAS_WARDS = [
    ("Orsett Ward", "C"), ("Osler Ward", "A"), ("Katherine Monk Ward", "A"),
    ("Kingswood Ward", "A"), ("Laindon Ward", "A"), ("Linford Ward", "A"),
    ("Nethermayne Ward", "D"), ("Chelmer Ward", "D"), ("Cardiac Rehab", "A"),
    ("Cardiac Catheter Labs", "B"), ("Neonatal Intensive Care Unit (NICU)", "A"),
    ("Critical Care Unit", "A"), ("Elizabeth Fry Ward", "D"), ("Edith Cavell Ward", "C"),
]
LEVEL_FLOOR = {"A": 0, "B": 1, "C": 2, "D": 3}


def bas_wps():
    wps = []
    for n, x, y, f, t in BAS_BUILDINGS:
        wps.append({"name": n, "nx": sx(x, y)[0], "ny": sx(x, y)[1], "floor": f, "type": t,
                    "group": "Buildings & entrances"})
    for i, (n, lvl) in enumerate(BAS_WARDS):
        f = LEVEL_FLOOR.get(lvl, 0)
        x = 1780 + (i % 4) * 60 - 90
        y = 560 + (i // 4) * 40
        wps.append({"name": n, "nx": sx(x, y)[0], "ny": sx(x, y)[1], "floor": f, "type": "ward",
                    "desc": f"Level {lvl}", "group": "Wards (Ward Block / Jubilee Wing)"})
    return wps


BASILDON = {
    "const": "BASILDON_VENUE", "id": "basildon-hospital", "slug": "basildon-hospital",
    "name": "Basildon & Thurrock University Hospital",
    "subtitle": "Mid and South Essex NHS Foundation Trust · Nethermayne, Basildon SS16 5NL",
    "center": (51.556289, 0.461),
    "bounds": ((51.554789, 0.457), (51.557789, 0.465)),
    "floors": [0, 1, 2, 3], "plan": "/floorplans/basildon/sitemap.svg",
    "quick": ["Main Entrance", "Emergency Department", "X-Ray", "The Essex Cardiothoracic Centre", "Outpatients Entrance"],
    "access": "Level isometric site with marked entrances, accessible parking and information points; levels A-D served by lifts.",
    "comment": [
        "Basildon & Thurrock University Hospital — Mid and South Essex NHS",
        "Foundation Trust. The floor plan is the trust's isometric site map; the",
        "buildings it labels are placed at their positions, and a set of wards from",
        "the Level/Area directory (Level A-D = floors 0-3) sits on the Ward Block.",
        "A curated set — extend via the in-app plan importer.",
    ],
}


def stage_assets():
    def cp(src, dst):
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy(src, dst)
    cp(f"{SP}/QUEENS_map.svg", os.path.join(REPO, "public/floorplans/queens/sitemap.svg"))
    cp(f"{SP}/KGH_ground.png", os.path.join(REPO, "public/floorplans/kgh/ground.png"))
    cp(f"{SP}/KGH_first.png", os.path.join(REPO, "public/floorplans/kgh/first.png"))
    cp(f"{SP}/BRM_mapimg.png", os.path.join(REPO, "public/floorplans/broomfield/sitemap.png"))
    cp(f"{SP}/BAS_map.svg", os.path.join(REPO, "public/floorplans/basildon/sitemap.svg"))
    print("staged overlays")


stage_assets()
emit(QUEENS, queens_wps(), "queens.ts")
emit(KGH, kgh_wps(), "kgh.ts")
emit(BROOMFIELD, brm_wps(), "broomfield.ts")
emit(BASILDON, bas_wps(), "basildon.ts")
